<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',

            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.view',
            'roles.manage',
            'approval.view',
            'approval.settings',

            'cabang.view',
            'cabang.create',
            'cabang.update',
            'cabang.delete',
            'perumahan.view',
            'perumahan.create',
            'perumahan.update',
            'perumahan.delete',
            'detail-rumah.view',
            'detail-rumah.create',
            'detail-rumah.update',
            'detail-rumah.delete',

            'customer.view',
            'customer.create',
            'customer.update',
            'customer.delete',
            'customer.follow-up',
            'booking.view',
            'booking.create',
            'booking.update',
            'booking.delete',
            'booking.manage',
            'spr-payment.view',
            'spr-payment.create',
            'spr-payment.update',
            'spr-payment.delete',
            'kpr.view',
            'kpr.create',
            'kpr.update',
            'kpr.delete',
            'kpr-akad.view',
            'kpr-akad.create',
            'kpr-akad.update',
            'kpr-akad.delete',
            'handover-customer.view',
            'handover-customer.create',
            'handover-customer.update',
            'handover-customer.delete',
            'payment-simulation.view',
            'pricelist.view',
            'unit-stock.view',
            'marketing.lead-source.manage',
            'marketing.lead-report.view',
            'marketing.pipeline.view',
            'marketing.campaign.manage',
            'marketing.reminder.manage',
            'marketing.document-review.manage',
            'marketing.template.manage',
            'marketing.performance.view',
            'marketing.pipeline-report.view',
            'marketing.receivable.view',
            'marketing.target-commission.manage',
            'marketing.leaderboard.view',

            'dokumen-legalitas.view',
            'dokumen-legalitas.create',
            'dokumen-legalitas.update',
            'dokumen-legalitas.delete',
            'dokumen-customer.view',
            'dokumen-customer.create',
            'dokumen-customer.update',

            'progress.view',
            'progress.create',
            'progress.update',
            'progress.delete',
            'site-schedule.view',
            'site-schedule.create',
            'site-schedule.update',
            'site-schedule.delete',
            'site-report.view',
            'site-report.create',
            'site-report.update',
            'site-report.delete',
            'quality-inspection.view',
            'quality-inspection.create',
            'quality-inspection.update',
            'quality-inspection.delete',
            'field-supervision.view',
            'field-supervision.create',
            'field-supervision.update',
            'field-supervision.delete',
            'field-supervision.approve',
            'material-request.view',
            'material-request.create',
            'material-request.update',
            'material-request.delete',
            'material-usage.view',
            'material-usage.create',
            'material-usage.update',
            'material-usage.delete',
            'material-return.view',
            'material-return.create',
            'material-return.update',
            'site-material-stock.view',
            'asset-inventory.view',
            'asset-inventory.request',
            'asset-inventory.usage',

            'keuangan.view',
            'keuangan.create',
            'keuangan.update',
            'keuangan.delete',
            'hpp.view',
            'hpp.create',
            'hpp.update',
            'hpp.delete',
            'laporan.view',
            'laporan.export',

            'master-bank.manage',
            'bank-account-ledger.view',
            'tipe-post.manage',
            'kelompok-hpp.manage',
            'settings.manage',
        ];

        $matrixActions = [
            'view', 'create', 'update', 'delete', 'unlock',
        ];
        $matrixModules = [
            'dashboard' => ['view'],
            'users' => $matrixActions,
            'roles' => ['view', 'create', 'update', 'delete', 'unlock'],
            'cabang' => $matrixActions,
            'perumahan' => $matrixActions,
            'detail-rumah' => $matrixActions,
            'dokumen-legalitas' => $matrixActions,
            'dokumen-customer' => $matrixActions,
            'master-bank' => ['view', 'create', 'update', 'delete', 'unlock'],
            'tipe-post' => ['view', 'create', 'update', 'delete', 'unlock'],
            'kelompok-hpp' => ['view', 'create', 'update', 'delete', 'unlock'],
            'customer' => $matrixActions,
            'customer-follow-up' => ['view', 'create', 'update', 'delete', 'unlock'],
            'booking' => ['view', 'create', 'update', 'delete', 'unlock'],
            'spr-payment' => ['view', 'create', 'update', 'delete', 'unlock'],
            'kpr' => ['view', 'create', 'update', 'delete', 'unlock'],
            'cash-purchase' => $matrixActions,
            'kpr-akad' => ['view', 'create', 'update', 'delete', 'unlock'],
            'handover-customer' => ['view', 'create', 'update', 'delete', 'unlock'],
            'payment-simulation' => ['view', 'create', 'update', 'delete', 'unlock'],
            'pricelist' => ['view', 'create', 'update', 'delete', 'unlock'],
            'unit-stock' => ['view'],
            'marketing-lead-source' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-report' => ['view'],
            'marketing-pipeline' => ['view'],
            'marketing-campaign' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-reminder' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-document-review' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-template' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-lead-distribution' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-activity' => ['view'],
            'marketing-target' => ['view', 'create', 'update', 'delete', 'unlock'],
            'site-schedule' => ['view', 'create', 'update', 'delete', 'unlock'],
            'progress' => ['view', 'create', 'update', 'delete', 'unlock'],
            'site-report' => ['view', 'create', 'update', 'delete', 'unlock'],
            'quality-inspection' => ['view', 'create', 'update', 'delete', 'unlock'],
            'field-supervision' => ['view', 'create', 'update', 'delete', 'unlock'],
            'spk-kontraktor' => ['view', 'create', 'update', 'delete', 'unlock'],
            'spk-payment' => ['view', 'create', 'update'],
            'asset-inventory' => ['view', 'create', 'update', 'delete', 'unlock'],
            'master-material' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-request' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-usage' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-return' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-purchase' => ['view', 'create', 'update', 'delete', 'unlock'],
            'site-material-stock' => ['view'],
            'keuangan' => $matrixActions,
            'bank-account-ledger' => ['view'],
            'refund-spr' => ['view', 'create', 'update', 'delete'],
            'hpp' => ['view', 'create', 'update', 'delete'],
            'laporan' => ['view'],
        ];
        foreach ($matrixModules as $module => $actions) {
            foreach ($actions as $action) {
                $permissions[] = $module.'.'.$action;
            }
        }
        $permissions = array_values(array_unique($permissions));
        $deprecatedApprovalPermissions = ['approve_manager', 'approve_owner', 'approve_finance', 'approve_admin'];
        Permission::query()
            ->whereIn('name', $deprecatedApprovalPermissions)
            ->delete();
        $ownerBlockedPrefixes = [
            'marketing.lead-source.',
            'marketing-lead-source.',
            'marketing.campaign.',
            'marketing-campaign.',
            'marketing.document-review.',
            'marketing-document-review.',
            'marketing.lead-distribution.',
            'marketing-lead-distribution.',
            'marketing.target-commission.',
            'marketing-target.',
        ];
        $ownerAllowedWritePermissions = [
            'roles.manage',
            'approval.settings',
        ];
        $ownerPermissions = array_values(array_filter($permissions, function (string $permission) use ($ownerAllowedWritePermissions, $ownerBlockedPrefixes) {
            if (in_array($permission, $ownerAllowedWritePermissions, true)) {
                return true;
            }

            if (str_ends_with($permission, '.create') || str_ends_with($permission, '.update') || str_ends_with($permission, '.delete') || str_ends_with($permission, '.unlock') || str_ends_with($permission, '.manage')) {
                return false;
            }

            return ! collect($ownerBlockedPrefixes)->contains(fn (string $prefix) => str_starts_with($permission, $prefix));
        }));

        foreach ($permissions as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        Role::query()
            ->whereIn('name', [
                'admin_keuangan',
                'admin_konsumen',
                'admin_kpr',
                'area_marketing',
                'bag_legal',
                'supervisor_marketing',
                'teknik',
                'user_area_gudang',
            ])
            ->delete();

        $rolePermissions = [
            'super_admin' => $permissions,
            'owner' => $ownerPermissions,
            'admin' => [
                'dashboard.view',
                'approval.view',
                'cabang.view',
                'perumahan.view',
                'perumahan.create',
                'perumahan.update',
                'detail-rumah.view',
                'detail-rumah.create',
                'detail-rumah.update',
                'customer.view',
                'customer.create',
                'customer.update',
                'customer.follow-up',
                'booking.view',
                'booking.create',
                'booking.update',
                'spr-payment.view',
                'spr-payment.create',
                'spr-payment.update',
                'kpr.view',
                'kpr.create',
                'kpr.update',
                'kpr-akad.view',
                'kpr-akad.create',
                'kpr-akad.update',
                'handover-customer.view',
                'handover-customer.create',
                'handover-customer.update',
                'unit-stock.view',
                'pricelist.view',
                'payment-simulation.view',
                'refund-spr.view',
                'marketing.lead-source.manage',
                'marketing.lead-report.view',
                'marketing.pipeline.view',
                'marketing.pipeline-report.view',
                'marketing.campaign.manage',
                'marketing.reminder.manage',
                'marketing.document-review.manage',
                'marketing.lead-distribution.manage',
                'marketing.activity.view',
                'marketing.target-commission.manage',
                'marketing.leaderboard.view',
                'marketing.receivable.view',
                'dokumen-legalitas.view',
                'dokumen-legalitas.create',
                'dokumen-legalitas.update',
                'dokumen-customer.view',
                'dokumen-customer.create',
                'dokumen-customer.update',
                'progress.view',
                'site-schedule.view',
                'site-report.view',
                'quality-inspection.view',
                'field-supervision.view',
                'spk-kontraktor.view',
                'spk-payment.view',
                'kpr.view',
                'kpr-akad.view',
                'handover-customer.view',
                'master-material.view',
                'material-request.view',
                'material-purchase.view',
                'material-usage.view',
                'material-return.view',
                'site-material-stock.view',
                'asset-inventory.view',
                'keuangan.view',
                'keuangan.create',
                'bank-account-ledger.view',
                'buku-besar.view',
                'neraca-saldo.view',
                'laba-rugi.view',
                'neraca.view',
                'arus-kas.view',
                'piutang.view',
                'hutang.view',
                'hpp.view',
                'laporan.view',
                'master-bank.manage',
                'tipe-post.manage',
                'kelompok-hpp.manage',
            ],
            'manajer_pimpro' => [
                'dashboard.view',
                'approval.view',
                'cabang.view',
                'perumahan.view',
                'perumahan.create',
                'perumahan.update',
                'detail-rumah.view',
                'detail-rumah.create',
                'detail-rumah.update',
                'customer.view',
                'customer.update',
                'dokumen-legalitas.view',
                'dokumen-customer.view',
                'progress.view',
                'progress.create',
                'progress.update',
                'asset-inventory.view',
                'keuangan.view',
                'hpp.view',
                'laporan.view',
            ],
            'marketing' => [
                'dashboard.view',
                'perumahan.view',
                'detail-rumah.view',
                'unit-stock.view',
                'pricelist.view',
                'payment-simulation.view',
                'customer.view',
                'customer.create',
                'customer.update',
                'customer-follow-up.view',
                'customer-follow-up.create',
                'customer-follow-up.update',
                'customer.follow-up',
                'booking.view',
                'booking.create',
                'booking.update',
                'booking.manage',
                'spr-payment.view',
                'spr-payment.create',
                'spr-payment.update',
                'kpr.view',
                'kpr.update',
                'kpr-akad.view',
                'handover-customer.view',
                'marketing-reminder.view',
                'marketing-reminder.create',
                'marketing-reminder.update',
                'dokumen-customer.view',
                'dokumen-customer.create',
                'dokumen-customer.update',
                'progress.view',
            ],
            'keuangan' => [
                'dashboard.view',
                'customer.view',
                'perumahan.view',
                'detail-rumah.view',
                'keuangan.view',
                'keuangan.create',
                'keuangan.update',
                'keuangan.delete',
                'hpp.view',
                'hpp.create',
                'hpp.update',
                'hpp.delete',
                'master-bank.manage',
                'tipe-post.manage',
                'kelompok-hpp.manage',
                'laporan.view',
                'laporan.export',
                'spk-payment.view',
                'spk-payment.create',
                'spk-payment.update',
            ],
            'pengawas' => [
                'dashboard.view',
                'perumahan.view',
                'detail-rumah.view',
                'progress.view',
                'progress.create',
                'progress.update',
                'site-schedule.view',
                'site-schedule.create',
                'site-schedule.update',
                'site-report.view',
                'site-report.create',
                'site-report.update',
                'quality-inspection.view',
                'quality-inspection.create',
                'quality-inspection.update',
                'field-supervision.view',
                'field-supervision.create',
                'field-supervision.update',
                'material-request.view',
                'material-request.create',
                'material-request.update',
                'material-usage.view',
                'material-usage.create',
                'material-usage.update',
                'material-return.view',
                'material-return.create',
                'site-material-stock.view',
                'asset-inventory.view',
                'asset-inventory.request',
                'asset-inventory.usage',
                'laporan.view',
            ],
        ];

        foreach ($rolePermissions as $roleName => $rolePermissionNames) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions(
                Permission::query()
                    ->where('guard_name', 'web')
                    ->whereIn('name', $rolePermissionNames)
                    ->get(),
            );
        }

        User::query()
            ->where('email', 'marketing@ptali.com')
            ->first()
            ?->assignRole('marketing');

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
