<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',

            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.view',
            'roles.manage',
            'approval.view',
            'approval.settings',
            'document-template.view',
            'payroll.view',
            'payroll.manage',
            'attendance.view',
            'attendance.settings',

            'cabang.view',
            'cabang.create',
            'cabang.update',
            'cabang.delete',
            'perumahan.view',
            'perumahan.create',
            'perumahan.update',
            'perumahan.delete',
            'detail-rumah.view',
            'detail-rumah.create',
            'detail-rumah.update',
            'detail-rumah.delete',

            'customer.view',
            'customer.create',
            'customer.update',
            'customer.delete',
            'customer.follow-up',
            'booking.view',
            'booking.create',
            'booking.update',
            'booking.delete',
            'booking.manage',
            'housing-reservation.view',
            'housing-reservation.create',
            'housing-reservation.update',
            'housing-reservation.delete',
            'housing-reservation.lock',
            'housing-reservation.print',
            'kpr.view',
            'kpr.create',
            'kpr.update',
            'kpr.delete',
            'payment-simulation.view',
            'pricelist.view',
            'unit-stock.view',
            'marketing.lead-source.manage',
            'marketing.lead-report.view',
            'marketing.pipeline.view',
            'marketing.campaign.manage',
            'marketing.reminder.manage',
            'marketing.document-review.manage',
            'marketing.template.manage',
            'marketing.performance.view',
            'marketing.pipeline-report.view',
            'marketing.receivable.view',
            'marketing.target-commission.manage',
            'marketing.leaderboard.view',

            'dokumen-legalitas.view',
            'dokumen-legalitas.create',
            'dokumen-legalitas.update',
            'dokumen-legalitas.delete',
            'dokumen-customer.view',
            'dokumen-customer.create',
            'dokumen-customer.update',

            'progress.view',
            'progress.create',
            'progress.update',
            'progress.delete',
            'site-schedule.view',
            'site-schedule.create',
            'site-schedule.update',
            'site-schedule.delete',
            'spk-kontraktor.approve',
            'spk-template-perumahan.view',
            'spk-template-perumahan.create',
            'spk-template-perumahan.update',
            'spk-template-perumahan.delete',
            'spk-template-unit.view',
            'spk-template-unit.create',
            'spk-template-unit.update',
            'spk-template-unit.delete',
            'site-report.view',
            'site-report.create',
            'site-report.update',
            'site-report.delete',
            'quality-inspection.view',
            'quality-inspection.create',
            'quality-inspection.update',
            'quality-inspection.delete',
            'field-supervision.view',
            'field-supervision.create',
            'field-supervision.update',
            'field-supervision.delete',
            'field-supervision.approve',
            'material-request.view',
            'material-request.create',
            'material-request.update',
            'material-request.delete',
            'material-usage.view',
            'material-usage.create',
            'material-usage.update',
            'material-usage.delete',
            'material-return.view',
            'material-return.create',
            'material-return.update',
            'site-material-stock.view',
            'material-price.view',
            'material-price.create',
            'material-price.delete',
            'material-opening-balance.view',
            'material-opening-balance.create',
            'material-opening-balance.update',
            'material-opening-balance.delete',
            'material-opening-balance.unlock',

            'keuangan.view',
            'keuangan.create',
            'keuangan.update',
            'keuangan.delete',
            'rab-perumahan.view',
            'rab-perumahan.create',
            'rab-perumahan.update',
            'rab-perumahan.delete',
            'rab-perumahan.manage',
            'rab-unit.view',
            'rab-unit.create',
            'rab-unit.update',
            'rab-unit.delete',
            'rab-unit.manage',
            'laporan.view',
            'laporan.export',
            'laporan-master-data.view',
            'laporan-pembelian.view',
            'laporan-persediaan-material.view',
            'laporan-marketing.view',

            'master-bank.manage',
            'bank-account-ledger.view',
            'tipe-post.manage',
            'settings.manage',
            'tukang.view',
            'tukang.create',
            'tukang.update',
            'tukang.delete',
        ];

        $matrixActions = [
            'view', 'create', 'update', 'delete', 'unlock',
        ];
        $matrixModules = [
            'dashboard' => ['view'],
            'users' => $matrixActions,
            'roles' => ['view', 'create', 'update', 'delete', 'unlock'],
            'cabang' => $matrixActions,
            'perumahan' => $matrixActions,
            'detail-rumah' => $matrixActions,
            'unit-ownership' => $matrixActions,
            'dokumen-legalitas' => $matrixActions,
            'dokumen-customer' => $matrixActions,
            'master-bank' => ['view', 'create', 'update', 'delete', 'unlock'],
            'tipe-post' => ['view', 'create', 'update', 'delete', 'unlock'],
            'customer' => $matrixActions,
            'customer-follow-up' => ['view', 'create', 'update', 'delete', 'unlock'],
            'booking' => ['view', 'create', 'update', 'delete', 'unlock'],
            'housing-reservation' => ['view', 'create', 'update', 'delete', 'lock', 'print'],
            'kpr' => ['view', 'create', 'update', 'delete', 'unlock'],
            'cash-purchase' => $matrixActions,
            'payment-simulation' => ['view', 'create', 'update', 'delete', 'unlock'],
            'pricelist' => ['view', 'create', 'update', 'delete', 'unlock'],
            'unit-stock' => ['view'],
            'marketing-lead-source' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-report' => ['view'],
            'marketing-pipeline' => ['view'],
            'marketing-campaign' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-reminder' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-document-review' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-template' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-lead-distribution' => ['view', 'create', 'update', 'delete', 'unlock'],
            'marketing-activity' => ['view'],
            'marketing-target' => ['view', 'create', 'update', 'delete', 'unlock'],
            'site-schedule' => ['view', 'create', 'update', 'delete', 'unlock'],
            'progress' => ['view', 'create', 'update', 'delete', 'unlock'],
            'site-report' => ['view', 'create', 'update', 'delete', 'unlock'],
            'quality-inspection' => ['view', 'create', 'update', 'delete', 'unlock'],
            'field-supervision' => ['view', 'create', 'update', 'delete', 'unlock'],
            'spk-kontraktor' => ['view', 'create', 'update', 'delete', 'unlock'],
            'spk-template-perumahan' => ['view', 'create', 'update', 'delete'],
            'spk-template-unit' => ['view', 'create', 'update', 'delete'],
            'spk-payment' => ['view', 'create', 'update'],
            'company-inventory' => ['view', 'create', 'update', 'delete', 'export', 'verify', 'approve', 'print'],
            'heavy-equipment' => ['view', 'create', 'update', 'delete', 'export', 'approve', 'print'],
            'master-material' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-type' => ['view', 'create', 'update', 'delete'],
            'material-brand' => ['view', 'create', 'update', 'delete'],
            'material-unit' => ['view', 'create', 'update', 'delete'],
            'material-group' => ['view', 'create', 'update', 'delete'],
            'bank-credit-master' => ['view', 'create', 'update', 'delete', 'submit', 'approve', 'reject'],
            'bank-branch' => ['view', 'create', 'update', 'delete', 'submit', 'approve', 'reject'],
            'bank-credit-product' => ['view', 'create', 'update', 'delete', 'submit', 'approve', 'reject'],
            'bank-housing-partnership' => ['view', 'create', 'update', 'delete', 'submit', 'approve', 'reject'],
            'bank-document-requirement' => ['view', 'create', 'update', 'delete'],
            'bank-partnership-history' => ['view'],
            'supplier' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-price' => ['view', 'create', 'delete', 'unlock'],
            'material-opening-balance' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-request' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-usage' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-return' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-purchase' => ['view', 'create', 'update', 'delete', 'unlock'],
            'material-stock-opname' => ['view', 'create', 'update', 'delete', 'view-all'],
            'site-material-stock' => ['view'],
            'tukang' => ['view', 'create', 'update', 'delete'],
            'rab-perumahan' => ['view', 'create', 'update', 'delete', 'manage'],
            'rab-unit' => ['view', 'create', 'update', 'delete', 'manage'],
            'keuangan' => $matrixActions,
            'petty-cash' => ['view', 'create', 'approve', 'disburse'],
            'bank-account-ledger' => ['view'],
            'laporan' => ['view'],
            'laporan-master-data' => ['view'],
            'laporan-pembelian' => ['view'],
            'laporan-persediaan-material' => ['view'],
            'laporan-marketing' => ['view'],
        ];
        $sectionActions = ['view', 'create', 'update', 'delete', 'export', 'verify', 'approve', 'print'];
        foreach (['company-inventory' => ['dashboard', 'categories', 'items', 'units', 'locations', 'receipts', 'loans', 'returns', 'transfers', 'damages', 'losses', 'stock-opname', 'ledger', 'reports'], 'heavy-equipment' => ['dashboard', 'equipment', 'types', 'components', 'replacements', 'usage', 'operators', 'maintenance', 'damages', 'fuel', 'reports']] as $prefix => $sections) {
            foreach ($sections as $section) {
                $matrixModules["{$prefix}.{$section}"] = $sectionActions;
            }
        }
        $integratedSalesPages = [
            'sales' => ['transactions', 'transaction-detail', 'payment-schedules', 'payments', 'handover', 'after-sales', 'reports'],
            'cash-installment' => ['schemes', 'scheme-detail', 'scheme-housing', 'scheme-steps', 'scheme-fees', 'scheme-requirements', 'scheme-documents', 'scheme-versions', 'scheme-history', 'scheme-reports', 'contracts', 'contract-detail', 'approvals', 'schedules', 'billings', 'arrears', 'payment-history', 'settlements', 'restructuring', 'cancellations', 'reports'],
            'developer-kpr' => ['products', 'product-detail', 'product-housing', 'financing-terms', 'margins', 'fees', 'requirements', 'documents', 'risk-approval', 'penalties', 'early-settlement', 'product-versions', 'product-history', 'product-reports', 'applications', 'application-detail', 'affordability-analysis', 'document-validation', 'internal-approval', 'contracts', 'schedules', 'receivables', 'arrears', 'payments', 'restructuring', 'cancellations', 'reports'],
            'bank-kpr' => ['applications', 'application-detail', 'document-validation', 'slik', 'appraisal', 'bank-decision', 'sp3k', 'financing', 'contract-preparation', 'contract-schedule', 'contract-execution', 'disbursement', 'bank-change', 'rejections', 'reports'],
        ];
        foreach ($integratedSalesPages as $prefix => $pages) {
            foreach ($pages as $page) {
                $matrixModules["{$prefix}.{$page}"] = ['view', 'create', 'update', 'delete', 'submit', 'approve', 'reject', 'print', 'export'];
            }
        }
        foreach (['summary', 'schedules', 'payments', 'construction', 'handover', 'after-sales', 'history'] as $tab) {
            $matrixModules["sales.transaction-detail.{$tab}"] = ['view'];
        }
        $matrixModules['receivables'] = ['view', 'print', 'settings'];
        $matrixModules['customer-receipts'] = ['view', 'create', 'update', 'lock', 'unlock', 'print'];
        $matrixModules['customer-charges'] = ['view', 'create', 'update', 'lock', 'unlock', 'print', 'reverse'];
        $matrixModules['customer-refunds'] = ['view', 'update', 'lock', 'unlock', 'print'];
        $matrixModules['sales-process'] = ['view', 'update', 'lock', 'unlock', 'print'];
        foreach ($matrixModules as $module => $actions) {
            foreach ($actions as $action) {
                $permissions[] = $module.'.'.$action;
            }
        }
        $permissions = array_values(array_unique($permissions));
        $deprecatedApprovalPermissions = ['approve_manager', 'approve_owner', 'approve_finance', 'approve_admin'];
        Permission::query()
            ->whereIn('name', $deprecatedApprovalPermissions)
            ->delete();
        $ownerBlockedPrefixes = [
            'marketing.lead-source.',
            'marketing-lead-source.',
            'marketing.campaign.',
            'marketing-campaign.',
            'marketing.document-review.',
            'marketing-document-review.',
            'marketing.lead-distribution.',
            'marketing-lead-distribution.',
            'marketing.target-commission.',
            'marketing-target.',
        ];
        $ownerAllowedWritePermissions = [
            'roles.manage',
            'approval.settings',
            'payroll.manage',
            'supplier.create',
            'supplier.update',
            'supplier.delete',
            'supplier.unlock',
            'petty-cash.approve',
        ];
        $ownerPermissions = array_values(array_filter($permissions, function (string $permission) use ($ownerAllowedWritePermissions, $ownerBlockedPrefixes) {
            if (in_array($permission, $ownerAllowedWritePermissions, true)) {
                return true;
            }

            if (str_ends_with($permission, '.create') || str_ends_with($permission, '.update') || str_ends_with($permission, '.delete') || str_ends_with($permission, '.unlock') || str_ends_with($permission, '.manage')) {
                return false;
            }

            return ! collect($ownerBlockedPrefixes)->contains(fn (string $prefix) => str_starts_with($permission, $prefix));
        }));

        $now = now();
        Permission::query()->upsert(
            collect($permissions)->map(fn (string $permission) => ['name' => $permission, 'guard_name' => 'web', 'created_at' => $now, 'updated_at' => $now])->all(),
            ['name', 'guard_name'],
            ['updated_at'],
        );
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        Role::query()
            ->whereIn('name', [
                'admin_keuangan',
                'admin_konsumen',
                'admin_kpr',
                'area_marketing',
                'bag_legal',
                'supervisor_marketing',
                'teknik',
                'user_area_gudang',
            ])
            ->delete();

        $rolePermissions = [
            'super_admin' => $permissions,
            'owner' => $ownerPermissions,
            'admin' => [
                'dashboard.view',
                'approval.view',
                'cabang.view',
                'perumahan.view',
                'perumahan.create',
                'perumahan.update',
                'detail-rumah.view',
                'detail-rumah.create',
                'detail-rumah.update',
                'unit-ownership.view',
                'unit-ownership.create',
                'unit-ownership.update',
                'unit-ownership.delete',
                'unit-ownership.unlock',
                'customer.view',
                'customer.create',
                'customer.update',
                'customer.follow-up',
                'booking.view',
                'booking.create',
                'booking.update',
                'kpr.view',
                'kpr.create',
                'kpr.update',
                'unit-stock.view',
                'pricelist.view',
                'payment-simulation.view',
                'marketing.lead-source.manage',
                'marketing.lead-report.view',
                'marketing.pipeline.view',
                'marketing.pipeline-report.view',
                'marketing.campaign.manage',
                'marketing.reminder.manage',
                'marketing.document-review.manage',
                'marketing.lead-distribution.manage',
                'marketing.activity.view',
                'marketing.target-commission.manage',
                'marketing.leaderboard.view',
                'marketing.receivable.view',
                'dokumen-legalitas.view',
                'dokumen-legalitas.create',
                'dokumen-legalitas.update',
                'dokumen-customer.view',
                'dokumen-customer.create',
                'dokumen-customer.update',
                'progress.view',
                'site-schedule.view',
                'site-report.view',
                'quality-inspection.view',
                'field-supervision.view',
                'spk-kontraktor.view',
                'spk-kontraktor.approve',
                'spk-template-perumahan.view',
                'spk-template-perumahan.create',
                'spk-template-perumahan.update',
                'spk-template-perumahan.delete',
                'spk-template-unit.view',
                'spk-template-unit.create',
                'spk-template-unit.update',
                'spk-template-unit.delete',
                'spk-payment.view',
                'kpr.view',
                'master-material.view',
                'supplier.view',
                'supplier.create',
                'supplier.update',
                'supplier.delete',
                'supplier.unlock',
                'material-price.view',
                'material-opening-balance.view',
                'material-request.view',
                'material-purchase.view',
                'material-purchase.create',
                'material-purchase.update',
                'material-usage.view',
                'material-return.view',
                'site-material-stock.view',
                'keuangan.view',
                'keuangan.create',
                'bank-account-ledger.view',
                'buku-besar.view',
                'neraca-saldo.view',
                'laba-rugi.view',
                'neraca.view',
                'arus-kas.view',
                'piutang.view',
                'hutang.view',
                'rab-perumahan.view',
                'rab-unit.view',
                'laporan.view',
                'laporan.export',
                'laporan-master-data.view',
                'laporan-pembelian.view',
                'laporan-persediaan-material.view',
                'laporan-marketing.view',
                'master-bank.manage',
                'tipe-post.manage',
                'tukang.view',
                'tukang.create',
                'tukang.update',
                'tukang.delete',
            ],
            'manager' => [
                'dashboard.view',
                'approval.view',
                'petty-cash.view',
                'petty-cash.create',
                'petty-cash.approve',
                'payroll.view',
                'payroll.manage',
                'perumahan.view',
                'perumahan.create',
                'perumahan.update',
                'detail-rumah.view',
                'detail-rumah.create',
                'detail-rumah.update',
                'customer.view',
                'customer.update',
                'dokumen-legalitas.view',
                'dokumen-customer.view',
                'progress.view',
                'progress.create',
                'progress.update',
                'site-schedule.view',
                'site-schedule.create',
                'site-schedule.update',
                'site-report.view',
                'site-report.create',
                'site-report.update',
                'quality-inspection.view',
                'quality-inspection.create',
                'quality-inspection.update',
                'field-supervision.view',
                'field-supervision.create',
                'field-supervision.update',
                'spk-kontraktor.view',
                'spk-kontraktor.approve',
                'spk-template-perumahan.view',
                'spk-template-perumahan.create',
                'spk-template-perumahan.update',
                'spk-template-perumahan.delete',
                'spk-template-unit.view',
                'spk-template-unit.create',
                'spk-template-unit.update',
                'spk-template-unit.delete',
                'rab-perumahan.view',
                'rab-perumahan.create',
                'rab-perumahan.update',
                'rab-perumahan.manage',
                'rab-unit.view',
                'rab-unit.create',
                'rab-unit.update',
                'rab-unit.manage',
                'laporan.view',
                'supplier.view',
                'supplier.create',
                'supplier.update',
                'supplier.delete',
                'supplier.unlock',
                'material-purchase.view',
                'material-stock-opname.view',
                'bank-credit-master.view', 'bank-credit-master.create', 'bank-credit-master.update', 'bank-credit-master.delete', 'bank-credit-master.submit',
                'bank-branch.view', 'bank-branch.create', 'bank-branch.update', 'bank-branch.delete', 'bank-branch.submit',
                'bank-credit-product.view', 'bank-credit-product.create', 'bank-credit-product.update', 'bank-credit-product.delete', 'bank-credit-product.submit',
                'bank-housing-partnership.view', 'bank-housing-partnership.create', 'bank-housing-partnership.update', 'bank-housing-partnership.delete', 'bank-housing-partnership.submit',
                'bank-document-requirement.view', 'bank-document-requirement.create', 'bank-document-requirement.update', 'bank-document-requirement.delete',
                'bank-partnership-history.view',
            ],
            'manajer_pimpro' => [
                'dashboard.view',
                'company-inventory.view',
                'company-inventory.create',
                'company-inventory.update',
                'company-inventory.delete',
                'company-inventory.export',
                'company-inventory.verify',
                'heavy-equipment.view',
                'heavy-equipment.create',
                'heavy-equipment.update',
                'heavy-equipment.delete',
                'heavy-equipment.export',
                'approval.view',
                'cabang.view',
                'perumahan.view',
                'perumahan.create',
                'perumahan.update',
                'detail-rumah.view',
                'detail-rumah.create',
                'detail-rumah.update',
                'customer.view',
                'customer.update',
                'dokumen-legalitas.view',
                'dokumen-customer.view',
                'progress.view',
                'progress.create',
                'progress.update',
                'keuangan.view',
                'rab-perumahan.view',
                'rab-unit.view',
                'laporan.view',
                'spk-kontraktor.approve',
                'spk-template-perumahan.view',
                'spk-template-perumahan.create',
                'spk-template-perumahan.update',
                'spk-template-perumahan.delete',
                'spk-template-unit.view',
                'spk-template-unit.create',
                'spk-template-unit.update',
                'spk-template-unit.delete',
                'rab-perumahan.create',
                'rab-perumahan.update',
                'rab-perumahan.manage',
                'rab-unit.create',
                'rab-unit.update',
                'rab-unit.manage',
                'supplier.view',
                'supplier.create',
                'supplier.update',
                'supplier.delete',
                'supplier.unlock',
                'material-purchase.view',
                'material-stock-opname.view',
            ],
            'marketing' => [
                'dashboard.view',
                'perumahan.view',
                'detail-rumah.view',
                'unit-stock.view',
                'pricelist.view',
                'payment-simulation.view',
                'customer.view',
                'customer.create',
                'customer.update',
                'customer-follow-up.view',
                'customer-follow-up.create',
                'customer-follow-up.update',
                'customer.follow-up',
                'booking.view',
                'booking.create',
                'booking.update',
                'booking.manage',
                'kpr.view',
                'kpr.update',
                'marketing-reminder.view',
                'marketing-reminder.create',
                'marketing-reminder.update',
                'dokumen-customer.view',
                'dokumen-customer.create',
                'dokumen-customer.update',
                'progress.view',
            ],
            'keuangan' => [
                'dashboard.view',
                'payroll.view',
                'payroll.manage',
                'petty-cash.view',
                'petty-cash.create',
                'customer.view',
                'perumahan.view',
                'detail-rumah.view',
                'keuangan.view',
                'keuangan.create',
                'keuangan.update',
                'keuangan.delete',
                'rab-perumahan.view',
                'rab-perumahan.create',
                'rab-perumahan.update',
                'rab-perumahan.delete',
                'rab-perumahan.manage',
                'rab-unit.view',
                'rab-unit.create',
                'rab-unit.update',
                'rab-unit.delete',
                'rab-unit.manage',
                'master-bank.manage',
                'tipe-post.manage',
                'laporan.view',
                'laporan.export',
                'spk-payment.view',
                'spk-payment.create',
                'spk-payment.update',
                'material-purchase.view',
                'material-purchase.create',
                'material-purchase.update',
            ],
            'pengawas' => [
                'dashboard.view',
                'perumahan.view',
                'detail-rumah.view',
                'progress.view',
                'progress.create',
                'progress.update',
                'site-schedule.view',
                'site-schedule.create',
                'site-schedule.update',
                'site-report.view',
                'site-report.create',
                'site-report.update',
                'quality-inspection.view',
                'quality-inspection.create',
                'quality-inspection.update',
                'field-supervision.view',
                'field-supervision.create',
                'field-supervision.update',
                'material-request.view',
                'material-request.create',
                'material-request.update',
                'material-usage.view',
                'material-usage.create',
                'material-usage.update',
                'material-return.view',
                'material-return.create',
                'site-material-stock.view',
                'rab-perumahan.view',
                'rab-perumahan.create',
                'rab-perumahan.update',
                'rab-perumahan.delete',
                'rab-perumahan.manage',
                'rab-unit.view',
                'rab-unit.create',
                'rab-unit.update',
                'rab-unit.delete',
                'rab-unit.manage',
                'laporan.view',
                'supplier.view',
                'supplier.create',
                'supplier.update',
                'supplier.delete',
                'supplier.unlock',
                'material-purchase.view',
                'material-group.view',
                'material-group.create',
                'material-group.update',
                'material-group.delete',
            ],
            'user_area_gudang' => [
                'dashboard.view',
                'company-inventory.view',
                'company-inventory.create',
                'company-inventory.update',
                'company-inventory.delete',
                'company-inventory.export',
                'company-inventory.verify',
                'heavy-equipment.view',
                'heavy-equipment.create',
                'heavy-equipment.update',
                'heavy-equipment.delete',
                'heavy-equipment.export',
                'master-material.view',
                'master-material.create',
                'master-material.update',
                'master-material.delete',
                'material-type.view',
                'material-type.create',
                'material-type.update',
                'material-type.delete',
                'material-brand.view',
                'material-brand.create',
                'material-brand.update',
                'material-brand.delete',
                'material-unit.view',
                'material-unit.create',
                'material-unit.update',
                'material-unit.delete',
                'material-price.view',
                'material-price.create',
                'material-price.delete',
                'material-opening-balance.view',
                'material-opening-balance.create',
                'material-opening-balance.update',
                'material-opening-balance.delete',
                'material-opening-balance.unlock',
                'material-request.view',
                'material-request.create',
                'material-request.update',
                'material-request.delete',
                'material-purchase.view',
                'material-purchase.create',
                'material-purchase.update',
                'material-purchase.delete',
                'material-usage.view',
                'material-usage.create',
                'material-usage.update',
                'material-usage.delete',
                'material-return.view',
                'material-return.create',
                'material-return.update',
                'material-return.delete',
                'site-material-stock.view',
            ],
            'petugas' => [
                'dashboard.view',
                'laporan.view',
                'laporan.export',
                'laporan-master-data.view',
                'laporan-pembelian.view',
                'laporan-persediaan-material.view',
                'laporan-marketing.view',
            ],
        ];

        $integratedViewPermissions = collect($integratedSalesPages)->flatMap(fn ($pages, $prefix) => collect($pages)->map(fn ($page) => "{$prefix}.{$page}.view"))->values()->all();
        $integratedMasterPermissions = collect([
            'cash-installment' => ['schemes', 'scheme-steps'],
            'developer-kpr' => ['products'],
        ])->flatMap(fn ($pages, $prefix) => collect($pages)->flatMap(fn ($page) => collect(['view', 'create', 'update', 'delete', 'submit', 'print'])->map(fn ($action) => "{$prefix}.{$page}.{$action}")))->values()->all();
        $integratedReviewPermissions = collect($integratedSalesPages)->flatMap(fn ($pages, $prefix) => collect($pages)->flatMap(fn ($page) => collect(['view', 'approve', 'reject', 'print', 'export'])->map(fn ($action) => "{$prefix}.{$page}.{$action}")))->values()->all();
        $transactionDetailViews = collect(['summary', 'schedules', 'payments', 'construction', 'handover', 'after-sales', 'history'])->map(fn ($tab) => "sales.transaction-detail.{$tab}.view")->all();
        $customerChargePermissions = collect(['view', 'create', 'update', 'lock', 'unlock', 'print', 'reverse'])->map(fn ($action) => "customer-charges.{$action}")->all();
        $customerRefundPermissions = collect(['view', 'update', 'lock', 'unlock', 'print'])->map(fn ($action) => "customer-refunds.{$action}")->all();
        $reservationManage = collect(['view', 'create', 'update', 'delete', 'lock', 'print'])->map(fn ($action) => "housing-reservation.{$action}")->all();
        $reservationRead = ['housing-reservation.view', 'housing-reservation.print'];
        $rolePermissions['admin'] = array_values(array_unique([...$rolePermissions['admin'], ...$reservationManage, ...$integratedViewPermissions, ...$integratedMasterPermissions, ...$transactionDetailViews, ...$customerChargePermissions, ...$customerRefundPermissions, 'document-template.view', 'receivables.view', 'receivables.print', 'customer-receipts.view', 'customer-receipts.create', 'customer-receipts.update', 'customer-receipts.lock', 'customer-receipts.unlock', 'customer-receipts.print', 'sales-process.view', 'sales-process.update', 'sales-process.lock', 'sales-process.unlock', 'sales-process.print']));
        $rolePermissions['manager'] = array_values(array_unique([...$rolePermissions['manager'], ...$reservationRead, ...$integratedReviewPermissions, ...$transactionDetailViews, ...$customerChargePermissions, ...$customerRefundPermissions, 'document-template.view', 'receivables.view', 'receivables.print', 'receivables.settings', 'customer-receipts.view', 'customer-receipts.print', 'sales-process.view', 'sales-process.unlock', 'sales-process.print']));
        $rolePermissions['marketing'] = array_values(array_unique([...$rolePermissions['marketing'], ...$reservationManage, 'document-template.view', 'sales.transactions.view', 'sales.transaction-detail.view', ...$transactionDetailViews, 'cash-installment.schemes.view', 'cash-installment.contracts.view', 'developer-kpr.products.view', 'developer-kpr.applications.view', 'bank-kpr.applications.view', 'bank-kpr.application-detail.view', 'bank-kpr.document-validation.view', 'bank-kpr.slik.view', 'bank-kpr.appraisal.view', 'bank-kpr.bank-decision.view', 'bank-kpr.sp3k.view', 'sales-process.view', 'sales-process.update', 'sales-process.lock', 'sales-process.print', 'bank-document-requirement.view']));
        $rolePermissions['keuangan'] = array_values(array_unique([...$rolePermissions['keuangan'], ...$reservationRead, ...$integratedViewPermissions, ...$transactionDetailViews, ...$customerChargePermissions, ...$customerRefundPermissions, 'receivables.view', 'receivables.print', 'receivables.settings', 'customer-receipts.view', 'customer-receipts.create', 'customer-receipts.update', 'customer-receipts.lock', 'customer-receipts.unlock', 'customer-receipts.print', 'sales-process.view', 'sales-process.print']));
        foreach (['manajer_pimpro', 'pengawas'] as $roleName) {
            $rolePermissions[$roleName] = array_values(array_unique([...$rolePermissions[$roleName], 'sales.transactions.view', 'sales.transaction-detail.view', 'sales.transaction-detail.summary.view', 'sales.transaction-detail.construction.view', 'sales.transaction-detail.handover.view', 'sales-process.view', 'sales-process.update', 'sales-process.lock', 'sales-process.print']));
        }

        foreach ($rolePermissions as $roleName => $rolePermissionNames) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions(
                Permission::query()
                    ->where('guard_name', 'web')
                    ->whereIn('name', $rolePermissionNames)
                    ->get(),
            );
            foreach (['company-inventory' => ['dashboard', 'categories', 'items', 'units', 'locations', 'receipts', 'loans', 'returns', 'transfers', 'damages', 'losses', 'stock-opname', 'ledger', 'reports'], 'heavy-equipment' => ['dashboard', 'equipment', 'types', 'components', 'replacements', 'usage', 'operators', 'maintenance', 'damages', 'fuel', 'reports']] as $prefix => $sections) {
                foreach ($sectionActions as $action) {
                    if (in_array("{$prefix}.{$action}", $rolePermissionNames, true)) {
                        $role->givePermissionTo(collect($sections)->map(fn ($section) => "{$prefix}.{$section}.{$action}")->all());
                    }
                }
                foreach ($sectionActions as $action) {
                    if (Permission::where('name', "{$prefix}.{$action}")->where('guard_name', 'web')->exists() && $role->hasPermissionTo("{$prefix}.{$action}")) {
                        $role->revokePermissionTo("{$prefix}.{$action}");
                    }
                }
            }
        }

        foreach ([
            'owner@ptali.com' => 'owner',
            'admin@ptali.com' => 'admin',
            'keuangan@ptali.com' => 'keuangan',
            'marketing@ptali.com' => 'marketing',
            'manager@ptali.com' => 'manager',
            'pimpro@ptali.com' => 'manajer_pimpro',
            'pengawas@ptali.com' => 'pengawas',
            'gudang@ptali.com' => 'user_area_gudang',
        ] as $email => $roleName) {
            User::query()->where('email', $email)->first()?->syncRoles([$roleName]);
        }

        DB::table('model_has_permissions')
            ->where('model_type', User::class)
            ->delete();

        Permission::query()
            ->where('guard_name', 'web')
            ->where('name', 'like', 'asset-inventory.%')
            ->delete();

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
