import { Head, router } from '@inertiajs/react';
import { FileText, Filter, LayoutDashboard, Search } from 'lucide-react';
import { useState } from 'react';
import Pagination from '../../../Components/Pagination';
import { Button, Dropdown, Input } from '../../../Components/UI';
import AdminLayout from '../../../Layouts/AdminLayout';

const humanize = (value) => String(value ?? '-').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function Ledger({ title, baseUrl, menu = [], filters, rows = { data: [], links: [] }, options = {} }) {
    const [query, setQuery] = useState(filters);
    const update = (key, value) => setQuery((current) => ({ ...current, [key]: value }));
    const apply = (event) => { event.preventDefault(); router.get(baseUrl, query, { preserveState: true }); };

    return <><Head title={title} /><div className="grid gap-6">
        <section className="rounded-xl border border-white/80 bg-white/80 p-6 shadow-soft dark:border-white/10 dark:bg-white/8"><p className="text-xs font-black uppercase tracking-[0.16em] text-ink-soft">Ledger Inventaris</p><h1 className="mt-2 font-display text-3xl font-black">Kartu Pergerakan Stok dan Aset</h1><p className="mt-2 text-sm text-ink-soft">Jejak immutable untuk pengambilan, pengembalian, mutasi, kerusakan, kehilangan, dan koreksi stock opname.</p></section>
        <nav className="flex gap-2 overflow-x-auto rounded-lg border border-white/80 bg-white/78 p-3 shadow-soft dark:border-white/10 dark:bg-white/8">{menu.map((item) => <Button key={item.key} size="sm" variant={item.key === 'ledger' ? 'primary' : 'ghost'} className="shrink-0" onClick={() => router.get(`/admin/inventaris-perusahaan/${item.key}`)}>{item.key === 'dashboard' ? <LayoutDashboard size={15} /> : <FileText size={15} />}{item.label}</Button>)}</nav>
        <form className="rounded-xl border border-white/80 bg-white/80 p-5 shadow-soft dark:border-white/10 dark:bg-white/8" onSubmit={apply}><h2 className="mb-4 flex items-center gap-2 font-black"><Filter size={18} /> Filter Kartu Pergerakan</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Input label="Cari barang/unit/referensi" value={query.search} onChange={(event) => update('search', event.target.value)} /><Input label="Dari Tanggal" type="date" value={query.date_from} onChange={(event) => update('date_from', event.target.value)} /><Input label="Sampai Tanggal" type="date" value={query.date_to} onChange={(event) => update('date_to', event.target.value)} /><div className="grid gap-2"><span className="text-sm font-extrabold">Barang</span><Dropdown value={String(query.inventory_item_id)} label="Semua barang" options={[{ value: '', label: 'Semua Barang' }, ...(options.items ?? [])]} onChange={(value) => update('inventory_item_id', value)} /></div><div className="grid gap-2"><span className="text-sm font-extrabold">Lokasi</span><Dropdown value={String(query.inventory_location_id)} label="Semua lokasi" options={[{ value: '', label: 'Semua Lokasi' }, ...(options.locations ?? [])]} onChange={(value) => update('inventory_location_id', value)} /></div><div className="grid gap-2"><span className="text-sm font-extrabold">Jenis Pergerakan</span><Dropdown value={query.movement_type} label="Semua pergerakan" options={[{ value: '', label: 'Semua Pergerakan' }, { value: 'issue', label: 'Pengambilan' }, { value: 'consumption', label: 'Pemakaian Habis' }, { value: 'return_good', label: 'Kembali Baik' }, { value: 'return_damaged', label: 'Kembali Rusak' }, { value: 'return_lost', label: 'Dinyatakan Hilang' }, { value: 'transfer', label: 'Mutasi' }, { value: 'damage', label: 'Kerusakan' }, { value: 'loss', label: 'Kehilangan' }, { value: 'stock_opname_adjustment', label: 'Koreksi Opname' }]} onChange={(value) => update('movement_type', value)} /></div></div><div className="mt-4 flex justify-end"><Button type="submit"><Search size={16} /> Terapkan Filter</Button></div></form>
        <section className="overflow-hidden rounded-xl border border-white/80 bg-white/80 shadow-soft dark:border-white/10 dark:bg-white/8"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-silver-soft/70 text-left text-xs uppercase tracking-wider text-ink-soft"><tr><th className="px-4 py-3">Waktu</th><th className="px-4 py-3">Pergerakan</th><th className="px-4 py-3">Nama Barang</th><th className="px-4 py-3">Unit Aset</th><th className="px-4 py-3">Dari</th><th className="px-4 py-3">Ke</th><th className="px-4 py-3">Jumlah</th><th className="px-4 py-3">Kondisi</th><th className="px-4 py-3">Referensi</th><th className="px-4 py-3">Petugas</th></tr></thead><tbody>{(rows.data ?? []).map((row) => <tr className="border-t border-silver-deep/50" key={row.id}><td className="whitespace-nowrap px-4 py-3">{row.occurred_at}</td><td className="px-4 py-3 font-bold">{humanize(row.movement_type)}</td><td className="px-4 py-3"><strong>{row.item_name}</strong><span className="ml-2 text-xs text-ink-soft">({row.item_code})</span></td><td className="px-4 py-3">{row.kode_aset ? `Unit ${row.kode_aset}` : '-'}</td><td className="px-4 py-3">{row.source_location || '-'}</td><td className="px-4 py-3">{row.destination_location || '-'}</td><td className="px-4 py-3 font-black">{row.quantity} {row.unit}</td><td className="px-4 py-3">{humanize(row.condition_bucket)}</td><td className="px-4 py-3">{row.reference_no || '-'}</td><td className="px-4 py-3">{row.performed_by_name || '-'}</td></tr>)}{!(rows.data ?? []).length && <tr><td className="px-5 py-12 text-center font-semibold text-ink-soft" colSpan="10">Belum ada pergerakan pada filter ini.</td></tr>}</tbody></table></div><Pagination links={rows.links ?? []} /></section>
    </div></>;
}

Ledger.layout = (page) => <AdminLayout title={page?.props?.title ?? 'Kartu Pergerakan'}>{page}</AdminLayout>;
