import { Head, Link, router } from '@inertiajs/react';
import AdminLayout from '../../../../Layouts/AdminLayout';
import { useState } from 'react';

export default function Index({ title, rows }) {
    const [responding, setResponding] = useState(null);
    const [note, setNote] = useState('');
    const respond = () => {
        if (!responding || (responding.decision === 'rejected' && !note.trim())) return;
        router.post(`/admin/admin-sales/assignments/${responding.id}/respond`, { decision: responding.decision, note }, { onFinish: () => { setResponding(null); setNote(''); } });
    };
    return <><Head title={title} /><div className="grid gap-5"><header className="rounded-3xl border bg-white p-6"><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-ink-soft">Terima Lead terlebih dahulu, kemudian lakukan follow-up sebelum batas respons.</p></header><section className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-silver-soft text-left"><tr><th className="p-4">Lead</th><th className="p-4">Dibagikan</th><th className="p-4">Batas respons</th><th className="p-4">Status</th><th className="p-4">Aksi</th></tr></thead><tbody className="divide-y">{rows.data.map((x) => <tr key={x.id}><td className="p-4"><Link className="font-bold text-gold-deep" href={`/admin/marketing/leads/${x.lead?.id}`}>{x.lead?.lead_no} · {x.lead?.name}</Link><p>{x.lead?.phone || '-'} · prioritas {x.lead?.priority || 'normal'}</p></td><td className="p-4">{x.assigner?.name || 'Sistem'}<p className="text-xs">{x.assigned_at}</p></td><td className="p-4">{x.response_due_at || '-'}</td><td className="p-4">{x.status}</td><td className="p-4">{x.status === 'offered' && <div className="flex gap-2"><button onClick={() => setResponding({ id: x.id, decision: 'accepted' })} className="rounded-lg bg-ink px-3 py-2 font-bold text-white">Terima</button><button onClick={() => setResponding({ id: x.id, decision: 'rejected' })} className="rounded-lg border px-3 py-2 font-bold text-red-600">Tolak</button></div>}</td></tr>)}{!rows.data.length && <tr><td colSpan="5" className="p-10 text-center text-ink-soft">Belum ada penugasan Lead.</td></tr>}</tbody></table></section></div>{responding && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={(e) => { e.preventDefault(); respond(); }} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-black">{responding.decision === 'rejected' ? 'Tolak penugasan Lead' : 'Terima penugasan Lead'}</h2><label className="mt-4 grid gap-2 text-sm font-bold">Catatan {responding.decision === 'rejected' && <span className="text-red-600">(wajib)</span>}<textarea autoFocus value={note} onChange={(e) => setNote(e.target.value)} required={responding.decision === 'rejected'} className="min-h-28 rounded-lg border p-3" /></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => { setResponding(null); setNote(''); }} className="rounded-lg border px-4 py-2">Batal</button><button className="rounded-lg bg-ink px-4 py-2 font-bold text-white">Simpan</button></div></form></div>}</>;
}
Index.layout = (page) => <AdminLayout title={page?.props?.title ?? 'Penugasan Lead'}>{page}</AdminLayout>;
