DAFTAR MENU

MANAGER
# APPROVAL
  # APPROVAL KWITANSI
  # APPROVAL PENGELUARAN
  # HUTANG
  # SURAT
# TRANSAKSI
# LAPORAN
# SETTING PROYEK
  # PRYOEK (INPUT DATA KAPLING)
  # INPUT UNIT PERUMAHAN  -> input hpp unit rumah, input harga jual unit rumah
  # SET KONTRAKTOR 
  

MARKETING
# KONSUMEN (input data calon konsumen)
   # CALON KONSUMEN
   # Jejak Follow Up
   # Konsumen (hasil follow up)
# TRANSAKSI SPR (Transaksi Surat Pemesanan Rumah) meliputi: opsi pemilihan pembayaran Cash, Cash Bertahap, KPR Bank, KPR Developer,
# OPERASIONAL
# LAPORAN
   # LAPORAN JEJAK KONSUMEN
   # SALES PRICELIST
   # LAPORAN SPR () INCLUDE DETAIL PEMBAYARAN KONSUMEN

#ADMIN
    # TRANSAKSI
    # PEMBAYARAN
    # OPERASIONAL
    # KEUANGAN
      # PEMASUKAN
        # ITEM PEMASUKAN
        # LIST JENIS PEMASUKAN
      # PENGELUARAN
        # ITEM PENGELUARAN
        # LIST JENIS PENGELUARAN
    # LAPORAN
    # SETTING PROYEK

# TEKNIK
  # INPUT SPK (SAAT SPK SUDAH DI INPUT DAN DIAJUKAN MAKA BIAYA SPK INI AKAN MENJADI HUTANG DEVELOPER)
  # PROSES BANGUN
  # PROSES BAYAR untuk melakukan pembayaran kepada kontraktor yang sudah mengajukan SPK, proses bayar ini akan menjadi pengeluaran untuk proyek
  # STATUS BANGUNAN
  # LAPORAN

# ADMIN PROYEK
    # KEUNGAN
        # PENGELUARAN
            # DRAFT PENGELUARAN (TRANSAKSI PENGELUARAN UNTUK UNIT/KAPLING) HARUS DI APPROVAL OLEH MANAGER // APROVAL PENGELUARAN OLEH OWNER PROYEK
            # ITEM PENGELUARAN
            # DATA REJECT
        # PROSES MONITOR  (YANG DIMONITOR ADALAH PROSES PENGELUARAN BARANG YANG SUDAH DIBELI ) SERTA MELAKUKAN PENAMBAHAN PENGELUARAN BARU
        # STATUS BANGUNAN (MENAMBAHKAN PROGRESS BANGUNAN PER UNIT/KAPLING ISINNYA STATUS BANGUNAN TANGGAL INPUT LINK GAMBAR)
            # LAPORAN KEUANGAN
                # LAPORAN PENGELUARAN
# ADMIN KEUANGAN
# USER LOGISTIK  