import { Head, Link, router } from "@inertiajs/react";
import { Banknote, FileText, Lock, Pencil, PlusCircle, Search, Users, WalletCards } from "lucide-react";
import { useState } from "react";
import { Button, Dropdown, Input, TableActions } from "../../../Components/UI";
import AdminLayout from "../../../Layouts/AdminLayout";

const rp = (v) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Number(v || 0));
const labels = { draft: "Draft", pending_approval: "Menunggu Approval", approved: "Disetujui" };
export default function Index({ title, baseUrl, createUrl, filters, statistics, trend, rows, canManage }) {
 const [search,setSearch]=useState(filters.search??""); const [status,setStatus]=useState(filters.status??"all");const[fromPeriod,setFromPeriod]=useState(filters.from_period);const[toPeriod,setToPeriod]=useState(filters.to_period);
 const submit=e=>{e.preventDefault();router.get(baseUrl,{search,status,from_period:fromPeriod,to_period:toPeriod},{preserveState:true,replace:true})};
 const action=(id,name,data={})=>router.post(`${baseUrl}/${id}/${name}`,data,{preserveScroll:true});
 return <><Head title={title}/><div className="grid gap-5">
  <section className="flex flex-col gap-4 rounded-2xl bg-gradient-to-br from-ink to-graphite p-6 text-white md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-champagne">Keuangan · Penggajian</p><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-white/65">Satu transaksi dapat memuat slip gaji banyak pegawai.</p></div>{canManage&&<Button as={Link} href={createUrl}><PlusCircle size={18}/> Buat Penggajian</Button>}</section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[WalletCards,"Total transaksi",statistics.transactions],[Users,"Pegawai pernah dibayar",statistics.employees_paid],[Banknote,"Gaji periode berjalan",rp(statistics.current_period_total)],[Banknote,"Total gaji disetujui",rp(statistics.approved_total)]].map(([Icon,l,v])=><div key={l} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5"><Icon size={20} className="text-gold-deep"/><p className="mt-3 text-xs font-bold uppercase text-ink-soft">{l}</p><p className="mt-1 text-2xl font-black">{v}</p></div>)}</section>
  <section className="rounded-2xl border bg-white p-5 dark:border-white/10 dark:bg-white/5"><form onSubmit={submit} className="mb-5 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><Input type="month" label="Dari Bulan" value={fromPeriod} onChange={e=>setFromPeriod(e.target.value)}/><Input type="month" label="Sampai Bulan" value={toPeriod} onChange={e=>setToPeriod(e.target.value)}/><Button>Terapkan Grafik</Button></form><h2 className="font-black">Tren Penggajian Bulanan</h2><div className="mt-5 flex min-h-64 items-end gap-2 overflow-x-auto border-b pb-1">{trend.map(x=>{const max=Math.max(...trend.map(y=>Number(y.total)),1);return <div key={x.period} className="flex min-w-16 flex-1 flex-col items-center justify-end"><span className="mb-2 text-[10px] font-bold">{rp(x.total)}</span><div className="w-full rounded-t bg-emerald-500" style={{height:`${Math.max(x.total?8:2,(x.total/max)*180)}px`}}/><span className="mt-2 text-[10px] text-ink-soft">{x.label}</span></div>})}</div><p className="mt-3 text-xs text-ink-soft">Bulan tanpa transaksi disetujui tetap ditampilkan dengan nilai Rp0.</p></section>
  <section className="overflow-hidden rounded-2xl border bg-white dark:border-white/10 dark:bg-white/5"><form onSubmit={submit} className="grid gap-3 border-b p-4 md:grid-cols-[1fr_220px_auto] md:items-end"><Input label="Cari transaksi / pegawai" value={search} onChange={e=>setSearch(e.target.value)}/><div><span className="mb-2 block text-sm font-extrabold">Status</span><Dropdown value={status} onChange={setStatus} options={[{value:"all",label:"Semua"},{value:"draft",label:"Draft"},{value:"pending_approval",label:"Menunggu Approval"},{value:"approved",label:"Disetujui"}]}/></div><Button><Search size={16}/> Cari</Button></form>
   <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-silver-soft text-left text-xs uppercase"><tr><th className="p-4">Transaksi</th><th className="p-4">Pegawai</th><th className="p-4">Nilai</th><th className="p-4">Status</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody className="divide-y">{rows.data.map(r=><tr key={r.id}><td className="p-4"><b>{r.batch_number}</b><div className="text-xs text-ink-soft">Periode {r.period} · Bayar {r.payment_date}</div></td><td className="p-4 font-bold">{r.employee_count} pegawai</td><td className="p-4"><b className="text-emerald-700">{rp(r.total_net)}</b><div className="text-xs text-ink-soft">Bruto {rp(r.total_gross)} · Potongan {rp(r.total_deductions)}</div></td><td className="p-4"><span className="rounded-full bg-silver-soft px-2.5 py-1 text-xs font-bold">{labels[r.status]??r.status}</span><div className="mt-2 text-xs">{r.approval_label}</div></td><td className="p-4"><TableActions>{r.record_status==="draft"&&canManage&&<Button as={Link} href={r.edit_url} size="sm" variant="outline"><Pencil size={14}/> Edit</Button>}{r.record_status==="draft"&&canManage&&<Button size="sm" onClick={()=>action(r.id,"lock")}><Lock size={14}/> Finalisasi</Button>}{r.status==="pending_approval"&&canManage&&<Button size="sm" variant="outline" onClick={()=>action(r.id,"unlock")}>Unlock</Button>}{r.can_review&&<><Button size="sm" onClick={()=>action(r.id,"review/approve")}>Approve</Button><Button size="sm" variant="danger" onClick={()=>action(r.id,"review/reject",{note:"Ditolak dari daftar penggajian"})}>Reject</Button></>}<Button as="a" target="_blank" href={r.invoice_url} size="sm" variant="outline"><FileText size={14}/> {r.status==="approved"?"Invoice":"Preview"}</Button></TableActions></td></tr>)}{!rows.data.length&&<tr><td colSpan="5" className="p-10 text-center font-bold text-ink-soft">Belum ada transaksi penggajian.</td></tr>}</tbody></table></div>
  </section></div></>;
}
Index.layout=page=><AdminLayout title={page?.props?.title??"Penggajian Pegawai"}>{page}</AdminLayout>;
