<?php

use App\Http\Controllers\Admin\ActivePerumahanController;
use App\Http\Controllers\Admin\Approval\ApprovalRequestController;
use App\Http\Controllers\Admin\Approval\ApprovalSettingController;
use App\Http\Controllers\Admin\AreaController;
use App\Http\Controllers\Admin\Bank\BankBranchController;
use App\Http\Controllers\Admin\Bank\BankCreditMasterController;
use App\Http\Controllers\Admin\Bank\BankCreditProductController;
use App\Http\Controllers\Admin\Bank\BankHousingPartnershipController;
use App\Http\Controllers\Admin\Bank\BankPartnershipHistoryController;
use App\Http\Controllers\Admin\BankAccountLedgerController;
use App\Http\Controllers\Admin\BusinessOptionController;
use App\Http\Controllers\Admin\ChatController;
use App\Http\Controllers\Admin\ConstructionProgressReportController;
use App\Http\Controllers\Admin\CustomerChargeController;
use App\Http\Controllers\Admin\CustomerRefundController;
use App\Http\Controllers\Admin\CustomerDocumentRepositoryController;
use App\Http\Controllers\Admin\CustomerReceivableController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\AttendanceAdminController;
use App\Http\Controllers\Admin\AttendanceSettingController;
use App\Http\Controllers\Admin\DocumentRequirementSetController;
use App\Http\Controllers\Admin\DocumentTemplateController;
use App\Http\Controllers\Admin\EmployeeSalaryController;
use App\Http\Controllers\Admin\EmployeeSalaryMasterController;
use App\Http\Controllers\Admin\EmployeeAdvanceController;
use App\Http\Controllers\Admin\FieldSupervisionController;
use App\Http\Controllers\Admin\FinanceController;
use App\Http\Controllers\Admin\GudangController;
use App\Http\Controllers\Admin\HeavyEquipmentController;
use App\Http\Controllers\Admin\IntegratedSalesController;
use App\Http\Controllers\Admin\InventoryCompanyController;
use App\Http\Controllers\Admin\KontraktorController;
use App\Http\Controllers\Admin\Kpr\BankKprFinancialController;
use App\Http\Controllers\Admin\Logistik\TransaksiLogistikController;
use App\Http\Controllers\Admin\Management\CabangPerusahaan\CabangPerusahaanController as AdminCabangPerusahaanController;
use App\Http\Controllers\Admin\Management\DokumenCostumer\DokumenCostumerController as AdminDokumenCostumerController;
use App\Http\Controllers\Admin\Management\DokumenLegalitas\DokumenLegalitasController as AdminDokumenLegalitasController;
use App\Http\Controllers\Admin\Management\DokumenLegalitasRumah\DokumenLegalitasRumahController as AdminDokumenLegalitasRumahController;
use App\Http\Controllers\Admin\Management\MasterBank\MasterBankController as AdminMasterBankController;
use App\Http\Controllers\Admin\Management\Overview\ManagementOverviewController as AdminManagementOverviewController;
use App\Http\Controllers\Admin\Management\Perumahan\PerumahanController as AdminPerumahanController;
use App\Http\Controllers\Admin\Management\RolePermission\RolePermissionController as AdminRolePermissionController;
use App\Http\Controllers\Admin\Management\TipePost\TipePostController as AdminTipePostController;
use App\Http\Controllers\Admin\Management\User\UserController as AdminUserController;
use App\Http\Controllers\Admin\Marketing\CashSaleController as AdminCashSaleController;
use App\Http\Controllers\Admin\Marketing\CostumerController as AdminCostumerController;
use App\Http\Controllers\Admin\Marketing\FollowUpController as AdminFollowUpController;
use App\Http\Controllers\Admin\Marketing\LeadReportController as AdminLeadReportController;
use App\Http\Controllers\Admin\Marketing\LeadSourceController as AdminLeadSourceController;
use App\Http\Controllers\Admin\Marketing\MarketingController as AdminMarketingController;
use App\Http\Controllers\Admin\Marketing\MarketingOperationsController as AdminMarketingOperationsController;
use App\Http\Controllers\Admin\Marketing\HousingReservationController;
use App\Http\Controllers\Admin\Marketing\MarketingToolsController as AdminMarketingToolsController;
use App\Http\Controllers\Admin\Marketing\PipelineReportController as AdminPipelineReportController;
use App\Http\Controllers\Admin\Marketing\SprController as AdminSprController;
use App\Http\Controllers\Admin\Marketing\SurveyScheduleController as AdminSurveyScheduleController;
use App\Http\Controllers\Admin\MasterMaterialController;
use App\Http\Controllers\Admin\MaterialGroupController;
use App\Http\Controllers\Admin\MaterialOpeningBalanceController;
use App\Http\Controllers\Admin\MaterialPriceController;
use App\Http\Controllers\Admin\MaterialPurchaseController;
use App\Http\Controllers\Admin\MaterialPurchaseRequestController;
use App\Http\Controllers\Admin\MaterialReferenceController;
use App\Http\Controllers\Admin\MaterialRequestController;
use App\Http\Controllers\Admin\MaterialReturnController;
use App\Http\Controllers\Admin\MaterialStockOpnameController;
use App\Http\Controllers\Admin\MaterialUsageController;
use App\Http\Controllers\Admin\MaterialUsageReportController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\OperationTransactionArchiveController;
use App\Http\Controllers\Admin\PettyCashController;
use App\Http\Controllers\Admin\PrintTemplateController;
use App\Http\Controllers\Admin\ProfileController as AdminProfileController;
use App\Http\Controllers\Admin\ProgressPembangunanController;
use App\Http\Controllers\Admin\QualityInspectionController;
use App\Http\Controllers\Admin\ReportCenterController;
use App\Http\Controllers\Admin\SalesProcessController;
use App\Http\Controllers\Admin\SalesResolutionController;
use App\Http\Controllers\Admin\SiteMaterialStockController;
use App\Http\Controllers\Admin\SiteReportController;
use App\Http\Controllers\Admin\SiteScheduleController;
use App\Http\Controllers\Admin\SpkKontraktorController;
use App\Http\Controllers\Admin\SpkTemplateController as AdminSpkTemplateController;
use App\Http\Controllers\Admin\StokMaterialController;
use App\Http\Controllers\Admin\SupplierController;
use App\Http\Controllers\Admin\TukangController;
use App\Http\Controllers\Admin\TukangGajiController;
use App\Http\Controllers\Admin\UnitOwnershipController;
use App\Http\Controllers\Admin\UnitRumahController as AdminUnitRumahController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AttendanceController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/media/{path}', function (string $path) {
    abort_if(str_contains($path, '..'), 404);

    $file = storage_path('app/public/'.$path);

    abort_unless(is_file($file), 404);

    return response()->file($file);
})->where('path', '.*')->name('media');

Route::get('/', function () {
    return Inertia::render('Guest/Home');
})->name('home');

Route::middleware('guest')->group(function () {
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->name('login.store');
});

Route::post('/logout', [LoginController::class, 'destroy'])
    ->name('logout');

Route::get('/absensi/masuk', [AttendanceController::class, 'loginForm'])->name('attendance.login');
Route::post('/absensi/check', [AttendanceController::class, 'login'])->middleware('throttle:6,1')->name('attendance.authenticate');
Route::post('/absensi/keluar', [AttendanceController::class, 'logout'])->name('attendance.logout');
Route::get('/absensi', [AttendanceController::class, 'index'])->name('attendance.index');
Route::post('/absensi', [AttendanceController::class, 'store'])->middleware('throttle:10,1')->name('attendance.store');

Route::prefix('admin/area')->group(function () {
    Route::get('{slug}', [AreaController::class, 'show'])->name('admin.area.show');
});

Route::get('/profil', function () {
    return Inertia::render('Guest/Profile');
})->name('profile');

Route::get('/tipe-rumah', function () {
    return Inertia::render('Guest/Units');
})->name('units');

Route::get('/galeri', function () {
    return Inertia::render('Guest/Gallery');
})->name('gallery');

Route::get('/kontak', function () {
    return Inertia::render('Guest/Contact');
})->name('contact');

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/absensi-pegawai', [AttendanceAdminController::class, 'index'])->name('admin.attendance.index');
    Route::get('/absensi-pegawai/{attendance}', [AttendanceAdminController::class, 'show'])->name('admin.attendance.show');
    Route::get('/pengaturan-absensi', [AttendanceSettingController::class, 'index'])->name('admin.attendance-settings.index');
    Route::post('/pengaturan-absensi', [AttendanceSettingController::class, 'store'])->name('admin.attendance-settings.store');
    Route::post('/arsip-transaksi/{module}/{section}/{id}/submit', [OperationTransactionArchiveController::class, 'submit'])->name('admin.transaction-archive.submit');
    Route::post('/arsip-transaksi/{module}/{section}/{id}/decision', [OperationTransactionArchiveController::class, 'decide'])->name('admin.transaction-archive.decision');
    Route::get('/arsip-transaksi/{module}/{section}/{id}/print', [OperationTransactionArchiveController::class, 'print'])->name('admin.transaction-archive.print');
    Route::prefix('options')->name('admin.options.')->group(function () {
        Route::get('/housing-projects', [BusinessOptionController::class, 'housings'])->name('housings');
        Route::get('/units', [BusinessOptionController::class, 'units'])->name('units');
        Route::get('/credit-banks', [BusinessOptionController::class, 'creditBanks'])->name('credit-banks');
        Route::get('/credit-bank-branches', [BusinessOptionController::class, 'bankBranches'])->name('bank-branches');
        Route::get('/credit-products', [BusinessOptionController::class, 'creditProducts'])->name('credit-products');
        Route::get('/document-requirements', [BusinessOptionController::class, 'documentRequirements'])->name('document-requirements');
    });
    Route::middleware('auth')->prefix('gaji-pegawai')->name('admin.employee-salaries.')->group(function () {
        Route::get('/', [EmployeeSalaryController::class, 'index'])->name('index');
        Route::get('/create', [EmployeeSalaryController::class, 'create'])->name('create');
        Route::get('/{employeeSalary}/edit', [EmployeeSalaryController::class, 'edit'])->name('edit');
        Route::post('/', [EmployeeSalaryController::class, 'store'])->name('store');
        Route::put('/{employeeSalary}', [EmployeeSalaryController::class, 'update'])->name('update');
        Route::post('/{employeeSalary}/lock', [EmployeeSalaryController::class, 'lock'])->name('lock');
        Route::post('/{employeeSalary}/unlock', [EmployeeSalaryController::class, 'unlock'])->name('unlock');
        Route::post('/{employeeSalary}/review/{decision}', [EmployeeSalaryController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('review');
        Route::get('/{employeeSalary}/invoice', [EmployeeSalaryController::class, 'invoice'])->name('invoice');
        Route::get('/lookup/active-salaries', [EmployeeSalaryController::class, 'activeSalaries'])->name('active-salaries');
    });
    Route::middleware('auth')->prefix('daftar-gaji-pegawai')->name('admin.salary-master.')->group(function () {
        Route::get('/', [EmployeeSalaryMasterController::class, 'index'])->name('index');
        Route::get('/create', [EmployeeSalaryMasterController::class, 'create'])->name('create');
        Route::post('/', [EmployeeSalaryMasterController::class, 'store'])->name('store');
        Route::get('/{salary}/edit', [EmployeeSalaryMasterController::class, 'edit'])->name('edit');
        Route::put('/{salary}', [EmployeeSalaryMasterController::class, 'update'])->name('update');
        Route::patch('/{salary}/status', [EmployeeSalaryMasterController::class, 'toggle'])->name('toggle');
    });
    Route::middleware('auth')->prefix('panjar-pegawai')->name('admin.employee-advances.')->group(function(){
        Route::get('/',[EmployeeAdvanceController::class,'index'])->name('index');Route::get('/create',[EmployeeAdvanceController::class,'create'])->name('create');Route::post('/',[EmployeeAdvanceController::class,'store'])->name('store');Route::get('/{advance}/edit',[EmployeeAdvanceController::class,'edit'])->name('edit');Route::put('/{advance}',[EmployeeAdvanceController::class,'update'])->name('update');Route::post('/{advance}/lock',[EmployeeAdvanceController::class,'lock'])->name('lock');Route::post('/{advance}/unlock',[EmployeeAdvanceController::class,'unlock'])->name('unlock');Route::post('/{advance}/review/{decision}',[EmployeeAdvanceController::class,'review'])->whereIn('decision',['approve','reject'])->name('review');
    });

    Route::middleware('auth')->prefix('chat')->name('admin.chat.')->group(function () {
        Route::get('/bootstrap', [ChatController::class, 'bootstrap'])->name('bootstrap');
        Route::post('/direct', [ChatController::class, 'direct'])->name('direct');
        Route::get('/conversations/{conversation}/messages', [ChatController::class, 'messages'])->name('messages');
        Route::post('/conversations/{conversation}/messages', [ChatController::class, 'store'])->name('store');
        Route::post('/conversations/{conversation}/read', [ChatController::class, 'read'])->name('read');
        Route::post('/conversations/{conversation}/mute', [ChatController::class, 'mute'])->name('mute');
        Route::delete('/conversations/{conversation}', [ChatController::class, 'clear'])->name('clear');
        Route::delete('/messages/{message}', [ChatController::class, 'deleteMessage'])->name('message.delete');
        Route::post('/messages/{message}/recall', [ChatController::class, 'recall'])->name('message.recall');
        Route::get('/messages/{message}/attachment', [ChatController::class, 'attachment'])->name('message.attachment');
    });
    Route::get('/dashboard', DashboardController::class)->name('admin.dashboard');
    Route::get('/bank-kredit', [BankCreditMasterController::class, 'index'])->name('admin.bank-master.index');
    Route::get('/bank-kredit/tambah', [BankCreditMasterController::class, 'create'])->name('admin.bank-master.create');
    Route::get('/bank-kredit/{bank}/edit', [BankCreditMasterController::class, 'edit'])->name('admin.bank-master.edit');
    Route::post('/bank-kredit', [BankCreditMasterController::class, 'store'])->name('admin.bank-master.store');
    Route::put('/bank-kredit/{bank}', [BankCreditMasterController::class, 'update'])->name('admin.bank-master.update');
    Route::delete('/bank-kredit/{bank}', [BankCreditMasterController::class, 'destroy'])->name('admin.bank-master.destroy');
    Route::post('/bank-kredit/{id}/lock', [BankCreditMasterController::class, 'lock'])->name('admin.bank-master.lock');
    Route::post('/bank-kredit/{id}/unlock', [BankCreditMasterController::class, 'unlock'])->name('admin.bank-master.unlock');
    Route::post('/bank-kredit/{id}/review/{decision}', [BankCreditMasterController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.bank-master.review');
    Route::resource('/cabang-bank', BankBranchController::class)->parameters(['cabang-bank' => 'branch'])->except(['show'])->names('admin.bank-branch');
    Route::post('/cabang-bank/{id}/lock', [BankBranchController::class, 'lock'])->name('admin.bank-branch.lock');
    Route::post('/cabang-bank/{id}/unlock', [BankBranchController::class, 'unlock'])->name('admin.bank-branch.unlock');
    Route::post('/cabang-bank/{id}/review/{decision}', [BankBranchController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.bank-branch.review');
    Route::resource('/produk-kredit-bank', BankCreditProductController::class)->parameters(['produk-kredit-bank' => 'product'])->except(['show'])->names('admin.bank-product');
    Route::post('/produk-kredit-bank/{id}/lock', [BankCreditProductController::class, 'lock'])->name('admin.bank-product.lock');
    Route::post('/produk-kredit-bank/{id}/unlock', [BankCreditProductController::class, 'unlock'])->name('admin.bank-product.unlock');
    Route::post('/produk-kredit-bank/{id}/review/{decision}', [BankCreditProductController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.bank-product.review');
    Route::resource('/kerja-sama-bank', BankHousingPartnershipController::class)->parameters(['kerja-sama-bank' => 'partnership'])->except(['show'])->names('admin.bank-partnership');
    Route::post('/kerja-sama-bank/{id}/lock', [BankHousingPartnershipController::class, 'lock'])->name('admin.bank-partnership.lock');
    Route::post('/kerja-sama-bank/{id}/unlock', [BankHousingPartnershipController::class, 'unlock'])->name('admin.bank-partnership.unlock');
    Route::post('/kerja-sama-bank/{id}/review/{decision}', [BankHousingPartnershipController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.bank-partnership.review');
    Route::get('/paket-persyaratan-dokumen', [DocumentRequirementSetController::class, 'index'])->name('admin.document-sets.index');
    Route::get('/paket-persyaratan-dokumen/tambah', [DocumentRequirementSetController::class, 'create'])->name('admin.document-sets.create');
    Route::post('/paket-persyaratan-dokumen', [DocumentRequirementSetController::class, 'store'])->name('admin.document-sets.store');
    Route::get('/paket-persyaratan-dokumen/{set}/edit', [DocumentRequirementSetController::class, 'edit'])->name('admin.document-sets.edit');
    Route::put('/paket-persyaratan-dokumen/{set}', [DocumentRequirementSetController::class, 'update'])->name('admin.document-sets.update');
    Route::post('/paket-persyaratan-dokumen/{set}/lock', [DocumentRequirementSetController::class, 'lock'])->name('admin.document-sets.lock');
    Route::post('/paket-persyaratan-dokumen/{set}/unlock', [DocumentRequirementSetController::class, 'unlock'])->name('admin.document-sets.unlock');
    Route::post('/paket-persyaratan-dokumen/{set}/review/{decision}', [DocumentRequirementSetController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.document-sets.review');
    Route::get('/riwayat-kerja-sama-bank', [BankPartnershipHistoryController::class, 'index'])->name('admin.bank-partnership-history.index');
    Route::get('/profile', [AdminProfileController::class, 'show'])->middleware('auth')->name('admin.profile');
    Route::put('/profile', [AdminProfileController::class, 'update'])->middleware('auth')->name('admin.profile.update');
    Route::put('/profile/password', [AdminProfileController::class, 'updatePassword'])->middleware('auth')->name('admin.profile.password.update');
    Route::post('/active-perumahan', [ActivePerumahanController::class, 'update'])->name('admin.active-perumahan.update');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('admin.notifications.index');
    Route::post('/notifications/{id}/read', [NotificationController::class, 'markRead'])->name('admin.notifications.read');
    Route::get('/laporan', [ReportCenterController::class, 'index'])->name('admin.reports.index');
    Route::get('/laporan-progress-pembangunan', [ConstructionProgressReportController::class, 'index'])->name('admin.construction-progress-report.index');
    Route::get('/laporan-progress-pembangunan/cetak', [ConstructionProgressReportController::class, 'print'])->name('admin.construction-progress-report.print');
    Route::get('/laporan-pemakaian-barang', [MaterialUsageReportController::class, 'index'])->name('admin.material-usage-report.index');
    Route::get('/laporan-pemakaian-barang/cetak', [MaterialUsageReportController::class, 'print'])->name('admin.material-usage-report.print');
    Route::get('/laporan/{group}', [ReportCenterController::class, 'show'])->name('admin.reports.show');
    Route::get('/laporan/{group}/cetak', [ReportCenterController::class, 'print'])->name('admin.reports.print');
    Route::prefix('kas-kecil')->name('admin.petty-cash.')->group(function () {
        Route::get('/{section?}', [PettyCashController::class, 'index'])->name('index');
        Route::post('/pengisian', [PettyCashController::class, 'storeFunding'])->name('fundings.store');
        Route::post('/pengisian/{funding}/kirim', [PettyCashController::class, 'submitFunding'])->name('fundings.submit');
        Route::post('/pengisian/{funding}/unlock', [PettyCashController::class, 'unlockFunding'])->name('fundings.unlock');
        Route::post('/pengisian/{funding}/setujui', [PettyCashController::class, 'approveFunding'])->name('fundings.approve');
        Route::post('/pengisian/{funding}/tolak', [PettyCashController::class, 'rejectFunding'])->name('fundings.reject');
        Route::post('/pengisian/{funding}/cairkan', [PettyCashController::class, 'disburseFunding'])->name('fundings.disburse');
        Route::post('/pengeluaran', [PettyCashController::class, 'storeExpense'])->name('expenses.store');
        Route::post('/penyetoran', [PettyCashController::class, 'storeDeposit'])->name('deposits.store');
        Route::post('/penyetoran/{deposit}/kirim', [PettyCashController::class, 'submitDeposit'])->name('deposits.submit');
        Route::post('/penyetoran/{deposit}/unlock', [PettyCashController::class, 'unlockDeposit'])->name('deposits.unlock');
        Route::post('/penyetoran/{deposit}/setujui', [PettyCashController::class, 'approveDeposit'])->name('deposits.approve');
        Route::post('/penyetoran/{deposit}/tolak', [PettyCashController::class, 'rejectDeposit'])->name('deposits.reject');
    });
    Route::get('/pemilik-unit', [UnitOwnershipController::class, 'index'])->name('admin.unit-ownership.index');
    Route::post('/pemilik-unit', [UnitOwnershipController::class, 'store'])->name('admin.unit-ownership.store');
    Route::put('/pemilik-unit/{id}', [UnitOwnershipController::class, 'update'])->name('admin.unit-ownership.update');
    Route::post('/pemilik-unit/{id}/deactivate', [UnitOwnershipController::class, 'deactivate'])->name('admin.unit-ownership.deactivate');
    Route::post('/pemilik-unit/{id}/lock', [UnitOwnershipController::class, 'lock'])->name('admin.unit-ownership.lock');
    Route::post('/pemilik-unit/{id}/unlock', [UnitOwnershipController::class, 'unlock'])->name('admin.unit-ownership.unlock');
    Route::prefix('inventaris-perusahaan')->group(function () {
        Route::post('/divisi', [InventoryCompanyController::class, 'storeDivision'])->name('admin.company-inventory.divisions.store');
        Route::get('/{section}/create', [InventoryCompanyController::class, 'create'])->name('admin.company-inventory.create');
        Route::get('/{section}/records/{id}/edit', [InventoryCompanyController::class, 'edit'])->name('admin.company-inventory.edit');
        Route::get('/{section}/records/{id}', [InventoryCompanyController::class, 'show'])->name('admin.company-inventory.show');
        Route::get('/{section?}', [InventoryCompanyController::class, 'index'])->name('admin.company-inventory.index');
        Route::post('/{section}/records', [InventoryCompanyController::class, 'store'])->name('admin.company-inventory.store');
        Route::put('/{section}/records/{id}', [InventoryCompanyController::class, 'update'])->name('admin.company-inventory.update');
        Route::delete('/{section}/records/{id}', [InventoryCompanyController::class, 'destroy'])->name('admin.company-inventory.destroy');
        Route::post('/stock-opname/{id}/verify', [InventoryCompanyController::class, 'verifyStockOpname'])->name('admin.company-inventory.stock-opname.verify');
        Route::get('/{section}/export/{format}', [InventoryCompanyController::class, 'export'])->name('admin.company-inventory.export');
    });
    Route::prefix('alat-berat')->group(function () {
        Route::get('/{section}/create', [HeavyEquipmentController::class, 'create'])->name('admin.heavy-equipment.create');
        Route::get('/{section}/records/{id}/edit', [HeavyEquipmentController::class, 'edit'])->name('admin.heavy-equipment.edit');
        Route::get('/equipment/{id}', [HeavyEquipmentController::class, 'show'])->name('admin.heavy-equipment.show');
        Route::get('/{section?}', [HeavyEquipmentController::class, 'index'])->name('admin.heavy-equipment.index');
        Route::post('/{section}/records', [HeavyEquipmentController::class, 'store'])->name('admin.heavy-equipment.store');
        Route::put('/{section}/records/{id}', [HeavyEquipmentController::class, 'update'])->name('admin.heavy-equipment.update');
        Route::delete('/{section}/records/{id}', [HeavyEquipmentController::class, 'destroy'])->name('admin.heavy-equipment.destroy');
        Route::get('/{section}/export/{format}', [HeavyEquipmentController::class, 'export'])->name('admin.heavy-equipment.export');
    });

    Route::get('/gudang', [GudangController::class, 'index'])->name('admin.gudang.index');
    Route::post('/gudang', [GudangController::class, 'store'])->name('admin.gudang.store');
    Route::put('/gudang/{id}', [GudangController::class, 'update'])->name('admin.gudang.update');
    Route::delete('/gudang/{id}', [GudangController::class, 'destroy'])->name('admin.gudang.destroy');
    Route::post('/gudang/{id}/lock', [GudangController::class, 'lock'])->name('admin.gudang.lock');
    Route::post('/gudang/{id}/unlock', [GudangController::class, 'unlock'])->name('admin.gudang.unlock');
    Route::get('/supplier', [SupplierController::class, 'index'])->name('admin.supplier.index');
    Route::post('/supplier', [SupplierController::class, 'store'])->name('admin.supplier.store');
    Route::put('/supplier/{id}', [SupplierController::class, 'update'])->name('admin.supplier.update');
    Route::delete('/supplier/{id}', [SupplierController::class, 'destroy'])->name('admin.supplier.destroy');
    Route::post('/supplier/{id}/lock', [SupplierController::class, 'lock'])->name('admin.supplier.lock');
    Route::post('/supplier/{id}/unlock', [SupplierController::class, 'unlock'])->name('admin.supplier.unlock');
    Route::get('/master-material', [MasterMaterialController::class, 'index'])->name('admin.master-material.index');
    Route::get('/master-material/create', [MasterMaterialController::class, 'create'])->name('admin.master-material.create');
    Route::get('/master-material/{id}/edit', [MasterMaterialController::class, 'edit'])->name('admin.master-material.edit');
    Route::post('/master-material', [MasterMaterialController::class, 'store'])->name('admin.master-material.store');
    Route::put('/master-material/{id}', [MasterMaterialController::class, 'update'])->name('admin.master-material.update');
    Route::delete('/master-material/{id}', [MasterMaterialController::class, 'destroy'])->name('admin.master-material.destroy');
    Route::post('/master-material/{id}/lock', [MasterMaterialController::class, 'lock'])->name('admin.master-material.lock');
    Route::post('/master-material/{id}/unlock', [MasterMaterialController::class, 'unlock'])->name('admin.master-material.unlock');
    Route::get('/kelompok-material', [MaterialGroupController::class, 'index'])->name('admin.material-group.index');
    Route::get('/kelompok-material/create', [MaterialGroupController::class, 'create'])->name('admin.material-group.create');
    Route::get('/kelompok-material/{materialGroup}/edit', [MaterialGroupController::class, 'edit'])->name('admin.material-group.edit');
    Route::post('/kelompok-material', [MaterialGroupController::class, 'store'])->name('admin.material-group.store');
    Route::put('/kelompok-material/{materialGroup}', [MaterialGroupController::class, 'update'])->name('admin.material-group.update');
    Route::delete('/kelompok-material/{materialGroup}', [MaterialGroupController::class, 'destroy'])->name('admin.material-group.destroy');
    Route::get('/referensi-material/{section}', [MaterialReferenceController::class, 'index'])->name('admin.material-reference.index');
    Route::post('/referensi-material/{section}', [MaterialReferenceController::class, 'store'])->name('admin.material-reference.store');
    Route::put('/referensi-material/{section}/{id}', [MaterialReferenceController::class, 'update'])->name('admin.material-reference.update');
    Route::delete('/referensi-material/{section}/{id}', [MaterialReferenceController::class, 'destroy'])->name('admin.material-reference.destroy');
    Route::get('/harga-material', [MaterialPriceController::class, 'index'])->name('admin.harga-material.index');
    Route::post('/harga-material/sync', [MaterialPriceController::class, 'sync'])->name('admin.harga-material.sync');
    Route::post('/harga-material', [MaterialPriceController::class, 'store'])->name('admin.harga-material.store');
    Route::delete('/harga-material/{id}', [MaterialPriceController::class, 'destroy'])->name('admin.harga-material.destroy');
    Route::post('/harga-material/{id}/lock', [MaterialPriceController::class, 'lock'])->name('admin.harga-material.lock');
    Route::post('/harga-material/{id}/unlock', [MaterialPriceController::class, 'unlock'])->name('admin.harga-material.unlock');
    Route::get('/saldo-awal-material', [MaterialOpeningBalanceController::class, 'index'])->name('admin.saldo-awal-material.index');
    Route::post('/saldo-awal-material/sync', [MaterialOpeningBalanceController::class, 'sync'])->name('admin.saldo-awal-material.sync');
    Route::post('/saldo-awal-material', [MaterialOpeningBalanceController::class, 'store'])->name('admin.saldo-awal-material.store');
    Route::put('/saldo-awal-material/{id}', [MaterialOpeningBalanceController::class, 'update'])->name('admin.saldo-awal-material.update');
    Route::delete('/saldo-awal-material/{id}', [MaterialOpeningBalanceController::class, 'destroy'])->name('admin.saldo-awal-material.destroy');
    Route::post('/saldo-awal-material/{id}/lock', [MaterialOpeningBalanceController::class, 'lock'])->name('admin.saldo-awal-material.lock');
    Route::post('/saldo-awal-material/{id}/unlock', [MaterialOpeningBalanceController::class, 'unlock'])->name('admin.saldo-awal-material.unlock');
    Route::get('/stok-material', [StokMaterialController::class, 'index'])->name('admin.stok-material.index');
    Route::get('/stok-material/data', [StokMaterialController::class, 'indexData'])->name('admin.stok-material.data');
    Route::get('/kartu-stok', [StokMaterialController::class, 'kartuStok'])->name('admin.kartu-stok.index');
    Route::get('/kartu-stok/data', [StokMaterialController::class, 'kartuStokData'])->name('admin.kartu-stok.data');
    Route::get('/stock-opname', [MaterialStockOpnameController::class, 'index'])->name('admin.material-stock-opname.index');
    Route::get('/stock-opname/create', [MaterialStockOpnameController::class, 'create'])->name('admin.material-stock-opname.create');
    Route::post('/stock-opname', [MaterialStockOpnameController::class, 'store'])->name('admin.material-stock-opname.store');
    Route::get('/logistik', [TransaksiLogistikController::class, 'index'])->name('admin.logistik.index');
    Route::get('/kontraktor', [KontraktorController::class, 'index'])->name('admin.kontraktor.index');
    Route::post('/kontraktor', [KontraktorController::class, 'store'])->name('admin.kontraktor.store');
    Route::put('/kontraktor/{id}', [KontraktorController::class, 'update'])->name('admin.kontraktor.update');
    Route::delete('/kontraktor/{id}', [KontraktorController::class, 'destroy'])->name('admin.kontraktor.destroy');
    Route::post('/kontraktor/{id}/lock', [KontraktorController::class, 'lock'])->name('admin.kontraktor.lock');
    Route::post('/kontraktor/{id}/unlock', [KontraktorController::class, 'unlock'])->name('admin.kontraktor.unlock');
    Route::get('/tukang', [TukangController::class, 'index'])->name('admin.tukang.index');
    Route::post('/tukang', [TukangController::class, 'store'])->name('admin.tukang.store');
    Route::put('/tukang/{tukang}', [TukangController::class, 'update'])->name('admin.tukang.update');
    Route::delete('/tukang/{tukang}', [TukangController::class, 'destroy'])->name('admin.tukang.destroy');
    Route::get('/tukang/{tukang}/gaji', [TukangGajiController::class, 'index'])->name('admin.tukang.gaji.index');
    Route::post('/tukang/{tukang}/gaji', [TukangGajiController::class, 'store'])->name('admin.tukang.gaji.store');
    Route::put('/tukang/{tukang}/gaji/{gaji}', [TukangGajiController::class, 'update'])->name('admin.tukang.gaji.update');
    Route::post('/tukang/{tukang}/gaji/{gaji}/aktifkan', [TukangGajiController::class, 'activate'])->name('admin.tukang.gaji.activate');
    Route::delete('/tukang/{tukang}/gaji/{gaji}', [TukangGajiController::class, 'destroy'])->name('admin.tukang.gaji.destroy');
    Route::get('/spk-kontraktor', [SpkKontraktorController::class, 'index'])->name('admin.spk-kontraktor.index');
    Route::get('/spk-kontraktor/approval', [SpkKontraktorController::class, 'approvalIndex'])->name('admin.spk-kontraktor.approval.index');
    Route::get('/spk-kontraktor/pencairan', [SpkKontraktorController::class, 'disbursementIndex'])->name('admin.spk-kontraktor.disbursement.index');
    Route::get('/keuangan/pembayaran-spk', [SpkKontraktorController::class, 'paymentIndex'])->name('admin.spk-kontraktor.payment.index');
    Route::get('/spk-kontraktor/{id}', [SpkKontraktorController::class, 'show'])->name('admin.spk-kontraktor.show');
    Route::post('/spk-kontraktor', [SpkKontraktorController::class, 'store'])->name('admin.spk-kontraktor.store');
    Route::put('/spk-kontraktor/{id}', [SpkKontraktorController::class, 'update'])->name('admin.spk-kontraktor.update');
    Route::delete('/spk-kontraktor/{id}', [SpkKontraktorController::class, 'destroy'])->name('admin.spk-kontraktor.destroy');
    Route::post('/spk-kontraktor/{id}/approve', [SpkKontraktorController::class, 'approve'])->name('admin.spk-kontraktor.approve');
    Route::post('/spk-kontraktor/{id}/cancel', [SpkKontraktorController::class, 'cancel'])->name('admin.spk-kontraktor.cancel');
    Route::post('/spk-kontraktor/{id}/lock', [SpkKontraktorController::class, 'lock'])->name('admin.spk-kontraktor.lock');
    Route::post('/spk-kontraktor/{id}/unlock', [SpkKontraktorController::class, 'unlock'])->name('admin.spk-kontraktor.unlock');
    Route::post('/spk-kontraktor/{id}/payments/{paymentId}/request', [SpkKontraktorController::class, 'requestPayment'])->name('admin.spk-kontraktor.payment.request');
    Route::post('/spk-kontraktor/{id}/payments/{paymentId}/approve', [SpkKontraktorController::class, 'approvePayment'])->name('admin.spk-kontraktor.payment.approve');
    Route::post('/spk-kontraktor/{id}/payments/{paymentId}/release', [SpkKontraktorController::class, 'releasePayment'])->name('admin.spk-kontraktor.payment.release');
    Route::get('/spk-template', [AdminSpkTemplateController::class, 'index'])->name('admin.spk-template.index');
    Route::get('/spk-template/create', [AdminSpkTemplateController::class, 'create'])->name('admin.spk-template.create');
    Route::post('/spk-template', [AdminSpkTemplateController::class, 'store'])->name('admin.spk-template.store');
    Route::get('/spk-template/{id}/edit', [AdminSpkTemplateController::class, 'edit'])->name('admin.spk-template.edit');
    Route::put('/spk-template/{id}', [AdminSpkTemplateController::class, 'update'])->name('admin.spk-template.update');
    Route::delete('/spk-template/{id}', [AdminSpkTemplateController::class, 'destroy'])->name('admin.spk-template.destroy');
    Route::get('/spk-template/perumahan', [AdminSpkTemplateController::class, 'index'])->name('admin.spk-template.perumahan.index');
    Route::post('/spk-template/perumahan', [AdminSpkTemplateController::class, 'store'])->name('admin.spk-template.perumahan.store');
    Route::put('/spk-template/perumahan/{id}', [AdminSpkTemplateController::class, 'update'])->name('admin.spk-template.perumahan.update');
    Route::delete('/spk-template/perumahan/{id}', [AdminSpkTemplateController::class, 'destroy'])->name('admin.spk-template.perumahan.destroy');
    Route::get('/spk-template/unit', [AdminSpkTemplateController::class, 'index'])->name('admin.spk-template.unit.index');
    Route::post('/spk-template/unit', [AdminSpkTemplateController::class, 'store'])->name('admin.spk-template.unit.store');
    Route::put('/spk-template/unit/{id}', [AdminSpkTemplateController::class, 'update'])->name('admin.spk-template.unit.update');
    Route::delete('/spk-template/unit/{id}', [AdminSpkTemplateController::class, 'destroy'])->name('admin.spk-template.unit.destroy');
    Route::get('/spk-template/{id}', [AdminSpkTemplateController::class, 'show'])->name('admin.spk-template.show');
    Route::get('/hpp-unit-rumah', [AdminUnitRumahController::class, 'hppIndex'])->name('admin.hpp-unit-rumah.index');
    Route::get('/unit-rumah', [AdminUnitRumahController::class, 'index'])->name('admin.unit-rumah.index');
    Route::get('/unit-rumah/create', [AdminUnitRumahController::class, 'create'])->name('admin.unit-rumah.create');
    Route::post('/unit-rumah', [AdminUnitRumahController::class, 'store'])->name('admin.unit-rumah.store');
    Route::get('/unit-rumah/{id}/edit', [AdminUnitRumahController::class, 'edit'])->name('admin.unit-rumah.edit');
    Route::put('/unit-rumah/{id}', [AdminUnitRumahController::class, 'update'])->name('admin.unit-rumah.update');
    Route::delete('/unit-rumah/{id}', [AdminUnitRumahController::class, 'destroy'])->name('admin.unit-rumah.destroy');
    Route::post('/unit-rumah/{id}/lock', [AdminUnitRumahController::class, 'lock'])->name('admin.unit-rumah.lock');
    Route::post('/unit-rumah/{id}/unlock', [AdminUnitRumahController::class, 'unlock'])->name('admin.unit-rumah.unlock');
    Route::get('/unit-rumah/{id}/hpp', [AdminUnitRumahController::class, 'hpp'])->name('admin.unit-rumah.hpp.detail');
    Route::get('/unit-rumah/{id}/hpp/pdf', [AdminUnitRumahController::class, 'exportHppPdf'])->name('admin.unit-rumah.hpp.pdf');
    Route::put('/unit-rumah/{id}/hpp', [AdminUnitRumahController::class, 'updateHpp'])->name('admin.unit-rumah.hpp.update');
    Route::put('/unit-rumah/{id}/hpp/{itemId}', [AdminUnitRumahController::class, 'updateHpp'])->name('admin.unit-rumah.hpp.item.update');
    Route::delete('/unit-rumah/{id}/hpp/{itemId}', [AdminUnitRumahController::class, 'destroyHppItem'])->name('admin.unit-rumah.hpp.item.destroy');
    Route::get('/pemakaian-material', [MaterialUsageController::class, 'index'])->name('admin.material-usage.index');
    Route::post('/pemakaian-material', [MaterialUsageController::class, 'store'])->name('admin.material-usage.store');
    Route::put('/pemakaian-material/{id}', [MaterialUsageController::class, 'update'])->name('admin.material-usage.update');
    Route::delete('/pemakaian-material/{id}', [MaterialUsageController::class, 'destroy'])->name('admin.material-usage.destroy');
    Route::post('/pemakaian-material/{id}/lock', [MaterialUsageController::class, 'lock'])->name('admin.material-usage.lock');
    Route::post('/pemakaian-material/{id}/unlock', [MaterialUsageController::class, 'unlock'])->name('admin.material-usage.unlock');
    Route::get('/sisa-material-lokasi', [SiteMaterialStockController::class, 'index'])->name('admin.site-material-stock.index');
    Route::get('/pengembalian-material', [MaterialReturnController::class, 'index'])->name('admin.material-return.index');
    Route::post('/pengembalian-material', [MaterialReturnController::class, 'store'])->name('admin.material-return.store');
    Route::post('/pengembalian-material/{id}/receive', [MaterialReturnController::class, 'receive'])->name('admin.material-return.receive');
    Route::post('/pengembalian-material/{id}/reject', [MaterialReturnController::class, 'reject'])->name('admin.material-return.reject');
    Route::post('/pengembalian-material/{id}/lock', [MaterialReturnController::class, 'lock'])->name('admin.material-return.lock');
    Route::post('/pengembalian-material/{id}/unlock', [MaterialReturnController::class, 'unlock'])->name('admin.material-return.unlock');
    Route::get('/permintaan-barang', [MaterialRequestController::class, 'index'])->name('admin.material-request.index');
    Route::get('/permintaan-barang/create', [MaterialRequestController::class, 'create'])->name('admin.material-request.create');
    Route::get('/permintaan-barang/templates', [MaterialRequestController::class, 'templates'])->name('admin.material-request.templates');
    Route::get('/permintaan-barang/{id}/edit', [MaterialRequestController::class, 'edit'])->name('admin.material-request.edit');
    Route::post('/permintaan-barang', [MaterialRequestController::class, 'store'])->name('admin.material-request.store');
    Route::put('/permintaan-barang/{id}', [MaterialRequestController::class, 'update'])->name('admin.material-request.update');
    Route::delete('/permintaan-barang/{id}', [MaterialRequestController::class, 'destroy'])->name('admin.material-request.destroy');
    Route::post('/permintaan-barang/{id}/approve', [MaterialRequestController::class, 'approve'])->name('admin.material-request.approve');
    Route::post('/permintaan-barang/{id}/approve-owner', [MaterialRequestController::class, 'approveOwner'])->name('admin.material-request.approve-owner');
    Route::post('/permintaan-barang/{id}/issue', [MaterialRequestController::class, 'issue'])->name('admin.material-request.issue');
    Route::post('/permintaan-barang/{id}/lock', [MaterialRequestController::class, 'lock'])->name('admin.material-request.lock');
    Route::post('/permintaan-barang/{id}/unlock', [MaterialRequestController::class, 'unlock'])->name('admin.material-request.unlock');
    Route::get('/progress-pembangunan', [ProgressPembangunanController::class, 'index'])->name('admin.progress-pembangunan.index');
    Route::get('/progress-pembangunan/create', [ProgressPembangunanController::class, 'create'])->name('admin.progress-pembangunan.create');
    Route::post('/progress-pembangunan', [ProgressPembangunanController::class, 'store'])->name('admin.progress-pembangunan.store');
    Route::get('/progress-pembangunan/{id}', [ProgressPembangunanController::class, 'show'])->name('admin.progress-pembangunan.show');
    Route::put('/progress-pembangunan/{id}', [ProgressPembangunanController::class, 'update'])->name('admin.progress-pembangunan.update');
    Route::delete('/progress-pembangunan/{id}', [ProgressPembangunanController::class, 'destroy'])->name('admin.progress-pembangunan.destroy');
    Route::post('/progress-pembangunan/{id}/lock', [ProgressPembangunanController::class, 'lock'])->name('admin.progress-pembangunan.lock');
    Route::post('/progress-pembangunan/{id}/unlock', [ProgressPembangunanController::class, 'unlock'])->name('admin.progress-pembangunan.unlock');
    Route::post('/progress-pembangunan/{id}/approve', [ProgressPembangunanController::class, 'approve'])->name('admin.progress-pembangunan.approve');
    Route::get('/laporan-lapangan', [SiteReportController::class, 'index'])->name('admin.site-report.index');
    Route::post('/laporan-lapangan', [SiteReportController::class, 'store'])->name('admin.site-report.store');
    Route::put('/laporan-lapangan/{id}', [SiteReportController::class, 'update'])->name('admin.site-report.update');
    Route::delete('/laporan-lapangan/{id}', [SiteReportController::class, 'destroy'])->name('admin.site-report.destroy');
    Route::post('/laporan-lapangan/{id}/approve', [SiteReportController::class, 'approve'])->name('admin.site-report.approve');
    Route::post('/laporan-lapangan/{id}/lock', [SiteReportController::class, 'lock'])->name('admin.site-report.lock');
    Route::post('/laporan-lapangan/{id}/unlock', [SiteReportController::class, 'unlock'])->name('admin.site-report.unlock');
    Route::get('/kontrol-kualitas', [QualityInspectionController::class, 'index'])->name('admin.quality-inspection.index');
    Route::post('/kontrol-kualitas', [QualityInspectionController::class, 'store'])->name('admin.quality-inspection.store');
    Route::put('/kontrol-kualitas/{id}', [QualityInspectionController::class, 'update'])->name('admin.quality-inspection.update');
    Route::delete('/kontrol-kualitas/{id}', [QualityInspectionController::class, 'destroy'])->name('admin.quality-inspection.destroy');
    Route::post('/kontrol-kualitas/{id}/approve', [QualityInspectionController::class, 'approve'])->name('admin.quality-inspection.approve');
    Route::post('/kontrol-kualitas/{id}/lock', [QualityInspectionController::class, 'lock'])->name('admin.quality-inspection.lock');
    Route::post('/kontrol-kualitas/{id}/unlock', [QualityInspectionController::class, 'unlock'])->name('admin.quality-inspection.unlock');
    Route::get('/jadwal-lapangan', [SiteScheduleController::class, 'index'])->name('admin.site-schedule.index');
    Route::get('/jadwal-lapangan/create', [SiteScheduleController::class, 'create'])->name('admin.site-schedule.create');
    Route::get('/jadwal-lapangan/{id}/edit', [SiteScheduleController::class, 'edit'])->name('admin.site-schedule.edit');
    Route::get('/jadwal-lapangan/{id}/pdf', [SiteScheduleController::class, 'exportPdf'])->name('admin.site-schedule.pdf');
    Route::post('/jadwal-lapangan', [SiteScheduleController::class, 'store'])->name('admin.site-schedule.store');
    Route::put('/jadwal-lapangan/{id}', [SiteScheduleController::class, 'update'])->name('admin.site-schedule.update');
    Route::delete('/jadwal-lapangan/{id}', [SiteScheduleController::class, 'destroy'])->name('admin.site-schedule.destroy');
    Route::post('/jadwal-lapangan/{id}/lock', [SiteScheduleController::class, 'lock'])->name('admin.site-schedule.lock');
    Route::post('/jadwal-lapangan/{id}/unlock', [SiteScheduleController::class, 'unlock'])->name('admin.site-schedule.unlock');
    Route::get('/pengawasan/{section}', [FieldSupervisionController::class, 'show'])->name('admin.field-supervision.show');
    Route::post('/pengawasan/{section}', [FieldSupervisionController::class, 'store'])->name('admin.field-supervision.store');
    Route::put('/pengawasan/{section}/{id}', [FieldSupervisionController::class, 'update'])->name('admin.field-supervision.update');
    Route::delete('/pengawasan/{section}/{id}', [FieldSupervisionController::class, 'destroy'])->name('admin.field-supervision.destroy');
    Route::post('/pengawasan/{section}/{id}/approve', [FieldSupervisionController::class, 'approve'])->name('admin.field-supervision.approve');
    Route::post('/pengawasan/{section}/{id}/lock', [FieldSupervisionController::class, 'lock'])->name('admin.field-supervision.lock');
    Route::post('/pengawasan/{section}/{id}/unlock', [FieldSupervisionController::class, 'unlock'])->name('admin.field-supervision.unlock');
    Route::get('/pembelian-material', [MaterialPurchaseController::class, 'index'])->name('admin.material-purchase.index');
    Route::get('/pembelian-material/create', [MaterialPurchaseController::class, 'create'])->name('admin.material-purchase.create');
    Route::get('/pembelian-material/{id}/edit', [MaterialPurchaseController::class, 'edit'])->name('admin.material-purchase.edit');
    Route::post('/pembelian-material', [MaterialPurchaseController::class, 'store'])->name('admin.material-purchase.store');
    Route::put('/pembelian-material/{id}', [MaterialPurchaseController::class, 'update'])->name('admin.material-purchase.update');
    Route::post('/pembelian-material/from-request/{id}', [MaterialPurchaseController::class, 'fromRequest'])->name('admin.material-purchase.from-request');
    Route::post('/pembelian-material/{id}/approve', [MaterialPurchaseController::class, 'approve'])->name('admin.material-purchase.approve');
    Route::post('/pembelian-material/{id}/release-fund', [MaterialPurchaseController::class, 'releaseFund'])->name('admin.material-purchase.release-fund');
    Route::post('/pembelian-material/{id}/mark-purchased', [MaterialPurchaseController::class, 'markPurchased'])->name('admin.material-purchase.mark-purchased');
    Route::post('/pembelian-material/{id}/receive', [MaterialPurchaseController::class, 'receive'])->name('admin.material-purchase.receive');
    Route::post('/pembelian-material/{id}/lock', [MaterialPurchaseController::class, 'lock'])->name('admin.material-purchase.lock');
    Route::post('/pembelian-material/{id}/unlock', [MaterialPurchaseController::class, 'unlock'])->name('admin.material-purchase.unlock');
    Route::get('/pemeriksaan-barang-masuk', [MaterialPurchaseController::class, 'inspectionIndex'])->name('admin.material-purchase.inspection.index');
    Route::post('/pemeriksaan-barang-masuk/{id}/item/{detailId}', [MaterialPurchaseController::class, 'inspectItem'])->name('admin.material-purchase.inspection.item');
    Route::get('/permintaan-pembelian', [MaterialPurchaseRequestController::class, 'index'])->name('admin.material-purchase-request.index');
    Route::get('/permintaan-pembelian/create', [MaterialPurchaseRequestController::class, 'create'])->name('admin.material-purchase-request.create');
    Route::get('/permintaan-pembelian/{id}/edit', [MaterialPurchaseRequestController::class, 'edit'])->name('admin.material-purchase-request.edit');
    Route::post('/permintaan-pembelian', [MaterialPurchaseRequestController::class, 'store'])->name('admin.material-purchase-request.store');
    Route::put('/permintaan-pembelian/{id}', [MaterialPurchaseRequestController::class, 'update'])->name('admin.material-purchase-request.update');
    Route::delete('/permintaan-pembelian/{id}', [MaterialPurchaseRequestController::class, 'destroy'])->name('admin.material-purchase-request.destroy');
    Route::post('/permintaan-pembelian/{id}/approve', [MaterialPurchaseRequestController::class, 'approve'])->name('admin.material-purchase-request.approve');
    Route::post('/permintaan-pembelian/{id}/reject', [MaterialPurchaseRequestController::class, 'reject'])->name('admin.material-purchase-request.reject');
    Route::post('/permintaan-pembelian/{id}/lock', [MaterialPurchaseRequestController::class, 'lock'])->name('admin.material-purchase-request.lock');
    Route::post('/permintaan-pembelian/{id}/unlock', [MaterialPurchaseRequestController::class, 'unlock'])->name('admin.material-purchase-request.unlock');
    Route::get('/rekening-bank', [BankAccountLedgerController::class, 'index'])->name('admin.bank-account-ledger.index');
    Route::get('/keuangan/transaksi-kas-bank', fn () => redirect('/admin/keuangan/pemasukan'));
    Route::get('/keuangan/piutang', [CustomerReceivableController::class, 'receivables'])->name('admin.receivables.index');
    Route::get('/keuangan/monitoring-jatuh-tempo', [CustomerReceivableController::class, 'dueMonitor'])->name('admin.receivables.due-monitor');
    Route::put('/keuangan/monitoring-jatuh-tempo/pengaturan', [CustomerReceivableController::class, 'updateDueSetting'])->name('admin.receivables.due-setting');
    Route::get('/keuangan/piutang/{schedule}/invoice', [CustomerReceivableController::class, 'invoice'])->name('admin.receivables.invoice');
    Route::get('/keuangan/penerimaan-customer', [CustomerReceivableController::class, 'receipts'])->name('admin.customer-receipts.index');
    Route::get('/keuangan/penerimaan-customer/create', [CustomerReceivableController::class, 'create'])->name('admin.customer-receipts.create');
    Route::post('/keuangan/penerimaan-customer', [CustomerReceivableController::class, 'store'])->name('admin.customer-receipts.store');
    Route::post('/keuangan/penerimaan-customer/{receipt}/lock', [CustomerReceivableController::class, 'lock'])->name('admin.customer-receipts.lock');
    Route::post('/keuangan/penerimaan-customer/{receipt}/unlock', [CustomerReceivableController::class, 'unlock'])->name('admin.customer-receipts.unlock');
    Route::post('/keuangan/penerimaan-customer/{receipt}/review/{decision}', [CustomerReceivableController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.customer-receipts.review');
    Route::get('/keuangan/penerimaan-customer/{receipt}/preview', [CustomerReceivableController::class, 'receiptPreview'])->name('admin.customer-receipts.preview');
    Route::get('/keuangan/penerimaan-customer/{receipt}/bukti', [CustomerReceivableController::class, 'receiptProof'])->name('admin.customer-receipts.proof');
    Route::get('/keuangan/penerimaan-customer/reservasi/{reservation}/verifikasi', [HousingReservationController::class, 'reviewPayment'])->name('admin.customer-receipts.reservation-review');
    Route::post('/keuangan/penerimaan-customer/reservasi/{reservation}/verifikasi/{decision}', [HousingReservationController::class, 'decidePayment'])->whereIn('decision', ['approve', 'reject'])->name('admin.customer-receipts.reservation-decision');
    Route::get('/keuangan/tagihan-talangan-customer', [CustomerChargeController::class, 'index'])->name('admin.customer-charges.index');
    Route::get('/keuangan/refund-customer', [CustomerRefundController::class, 'index'])->name('admin.customer-refunds.index');
    Route::put('/keuangan/refund-customer/{refund}', [CustomerRefundController::class, 'update'])->name('admin.customer-refunds.update');
    Route::post('/keuangan/refund-customer/{refund}/lock', [CustomerRefundController::class, 'lock'])->name('admin.customer-refunds.lock');
    Route::post('/keuangan/refund-customer/{refund}/unlock', [CustomerRefundController::class, 'unlock'])->name('admin.customer-refunds.unlock');
    Route::post('/keuangan/refund-customer/{refund}/review/{decision}', [CustomerRefundController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.customer-refunds.review');
    Route::get('/keuangan/refund-customer/{refund}/bukti', [CustomerRefundController::class, 'proof'])->name('admin.customer-refunds.proof');
    Route::get('/keuangan/tagihan-talangan-customer/create', [CustomerChargeController::class, 'create'])->name('admin.customer-charges.create');
    Route::post('/keuangan/tagihan-talangan-customer', [CustomerChargeController::class, 'store'])->name('admin.customer-charges.store');
    Route::get('/keuangan/tagihan-talangan-customer/{charge}/edit', [CustomerChargeController::class, 'edit'])->name('admin.customer-charges.edit');
    Route::put('/keuangan/tagihan-talangan-customer/{charge}', [CustomerChargeController::class, 'update'])->name('admin.customer-charges.update');
    Route::post('/keuangan/tagihan-talangan-customer/{charge}/lock', [CustomerChargeController::class, 'lock'])->name('admin.customer-charges.lock');
    Route::post('/keuangan/tagihan-talangan-customer/{charge}/unlock', [CustomerChargeController::class, 'unlock'])->name('admin.customer-charges.unlock');
    Route::post('/keuangan/tagihan-talangan-customer/{charge}/review/{decision}', [CustomerChargeController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.customer-charges.review');
    Route::post('/keuangan/tagihan-talangan-customer/{charge}/reversal', [CustomerChargeController::class, 'requestReversal'])->name('admin.customer-charges.reversal');
    Route::get('/keuangan/tagihan-talangan-customer/{charge}/preview', [CustomerChargeController::class, 'preview'])->name('admin.customer-charges.preview');
    Route::get('/keuangan/tagihan-talangan-customer/{charge}/bukti', [CustomerChargeController::class, 'proof'])->name('admin.customer-charges.proof');
    Route::get('/keuangan/{section}', [FinanceController::class, 'show'])->name('admin.finance.show');
    Route::post('/keuangan/jurnal-umum', [FinanceController::class, 'storeJournal'])->name('admin.finance.journal.store');
    Route::post('/keuangan/transaksi-kas-bank', [FinanceController::class, 'storeTransaction'])->name('admin.finance.transaction.store');
    Route::post('/keuangan/pemasukan', [FinanceController::class, 'storeIncome'])->name('admin.finance.income.store');
    Route::post('/keuangan/pengeluaran', [FinanceController::class, 'storeExpense'])->name('admin.finance.expense.store');
    Route::post('/keuangan/daftar-akun', [FinanceController::class, 'storeAccount'])->name('admin.finance.account.store');
    Route::put('/keuangan/daftar-akun/{id}', [FinanceController::class, 'updateAccount'])->name('admin.finance.account.update');

    Route::prefix('penjualan-terintegrasi')->group(function () {
        Route::get('/tahapan/{step}', [SalesProcessController::class, 'workspace'])->name('admin.sales-process.workspace');
        Route::put('/tahapan/{step}', [SalesProcessController::class, 'update'])->name('admin.sales-process.update');
        Route::put('/tahapan/{step}/checklist', [SalesProcessController::class, 'updateChecklist'])->name('admin.sales-process.checklist.update');
        Route::post('/tahapan/{step}/lock', [SalesProcessController::class, 'lock'])->name('admin.sales-process.lock');
        Route::post('/tahapan/{step}/unlock', [SalesProcessController::class, 'unlock'])->name('admin.sales-process.unlock');
        Route::post('/tahapan/{step}/review/{decision}', [SalesProcessController::class, 'review'])->whereIn('decision', ['approve', 'reject'])->name('admin.sales-process.review');
        Route::get('/tahapan/{step}/lampiran', [SalesProcessController::class, 'attachment'])->name('admin.sales-process.attachment');
        Route::post('/tahapan/{step}/dokumen', [SalesProcessController::class, 'storeDocument'])->name('admin.sales-process.document.store');
        Route::get('/tahapan/{step}/dokumen/{document}', [SalesProcessController::class, 'document'])->name('admin.sales-process.document.show');
        Route::delete('/tahapan/{step}/dokumen/{document}', [SalesProcessController::class, 'destroyDocument'])->name('admin.sales-process.document.destroy');
        Route::get('/{section?}', [IntegratedSalesController::class, 'index'])->name('admin.integrated-sales.index');
        Route::get('/{section}/create', [IntegratedSalesController::class, 'create'])->name('admin.integrated-sales.create');
        Route::get('/{section}/records/{id}/edit', [IntegratedSalesController::class, 'edit'])->name('admin.integrated-sales.edit');
        Route::get('/{section}/records/{id}', [IntegratedSalesController::class, 'show'])->name('admin.integrated-sales.show');
        Route::get('/{section}/records/{id}/preview', [IntegratedSalesController::class, 'preview'])->name('admin.integrated-sales.preview');
        Route::get('/{section}/records/{id}/print', [IntegratedSalesController::class, 'print'])->name('admin.integrated-sales.print');
        Route::post('/{section}/records', [IntegratedSalesController::class, 'store'])->name('admin.integrated-sales.store');
        Route::put('/{section}/records/{id}', [IntegratedSalesController::class, 'update'])->name('admin.integrated-sales.update');
        Route::delete('/{section}/records/{id}', [IntegratedSalesController::class, 'destroy'])->name('admin.integrated-sales.destroy');
        Route::post('/{section}/records/{id}/lock', [IntegratedSalesController::class, 'lockProcess'])->name('admin.integrated-sales.lock');
        Route::post('/{section}/records/{id}/unlock', [IntegratedSalesController::class, 'unlockProcess'])->name('admin.integrated-sales.unlock');
        Route::post('/{section}/records/{id}/review/{decision}', [IntegratedSalesController::class, 'reviewProcess'])->whereIn('decision', ['approve', 'reject'])->name('admin.integrated-sales.review');
    });
    Route::get('/kpr', fn () => redirect()->route('admin.integrated-sales.index', 'bank-applications'))->name('admin.kpr.index');
    Route::post('/kpr/{submission}/financing', [BankKprFinancialController::class, 'saveFinancing'])->name('admin.kpr.financing.save');
    Route::post('/kpr/financing/{financing}/lock', [BankKprFinancialController::class, 'lockFinancing'])->name('admin.kpr.financing.lock');
    Route::post('/kpr/{submission}/disbursements', [BankKprFinancialController::class, 'storeDisbursement'])->name('admin.kpr.disbursement.store');
    Route::post('/kpr/disbursements/{disbursement}/lock', [BankKprFinancialController::class, 'lockDisbursement'])->name('admin.kpr.disbursement.lock');
    Route::get('/kpr/{id}', fn (string $id) => redirect()->route('admin.integrated-sales.show', ['bank-applications', $id]))->name('admin.kpr.show');

    Route::prefix('approval')->name('admin.approval.')->group(function () {
        Route::get('/', [ApprovalRequestController::class, 'index'])->name('requests.index');
        Route::get('settings', [ApprovalSettingController::class, 'index'])->name('settings.index');
        Route::put('settings', [ApprovalSettingController::class, 'update'])->name('settings.update');
        Route::post('{approvalRequest}/approve', [ApprovalRequestController::class, 'approve'])->whereNumber('approvalRequest')->name('requests.approve');
        Route::post('{approvalRequest}/reject', [ApprovalRequestController::class, 'reject'])->whereNumber('approvalRequest')->name('requests.reject');
    });
    Route::get('/pengaturan-cetak', [PrintTemplateController::class, 'index'])->name('admin.print-settings.index');
    Route::put('/pengaturan-cetak', [PrintTemplateController::class, 'update'])->name('admin.print-settings.update');
    Route::get('/master-dokumen', [DocumentTemplateController::class, 'index'])->name('admin.document-templates.index');
    Route::get('/repository-dokumen-customer', [CustomerDocumentRepositoryController::class, 'index'])->name('admin.customer-documents.index');
    Route::post('/repository-dokumen-customer', [CustomerDocumentRepositoryController::class, 'store'])->name('admin.customer-documents.store');
    Route::post('/repository-dokumen-customer/{document}/replace', [CustomerDocumentRepositoryController::class, 'replace'])->name('admin.customer-documents.replace');
    Route::get('/master-dokumen/{type}/dokumen-asli', [DocumentTemplateController::class, 'preview'])->whereIn('type', ['spr', 'ppjb', 'handover', 'signing-minutes'])->name('admin.document-templates.preview');
    Route::get('/marketing/spr/{spr}/dokumen/{type}', [DocumentTemplateController::class, 'printSpr'])->whereIn('type', ['spr', 'ppjb', 'handover', 'signing-minutes'])->name('admin.document-templates.spr.print');

    Route::prefix('management')->name('admin.management.')->group(function () {
        Route::get('/', [AdminManagementOverviewController::class, 'index'])->name('overview');
        Route::get('perumahan/{id}/hpp', [AdminPerumahanController::class, 'hpp'])->name('perumahan.hpp.detail');
        Route::get('perumahan/{id}/detail', [AdminPerumahanController::class, 'detail'])->name('perumahan.detail');
        Route::get('perumahan/{id}/rumah/{rumahId}/detail', [AdminPerumahanController::class, 'unitDetail'])->name('perumahan.rumah.detail');
        Route::get('perumahan/{id}/rumah/{rumahId}/hpp', [AdminPerumahanController::class, 'rumahHpp'])->name('perumahan.rumah.hpp.detail');
        Route::post('perumahan/{id}/rumah', [AdminPerumahanController::class, 'storeRumah'])->name('perumahan.rumah.store');
        Route::put('perumahan/{id}/rumah/{rumahId}', [AdminPerumahanController::class, 'updateRumah'])->name('perumahan.rumah.update');
        Route::post('perumahan/{id}/rumah/{rumahId}/progress', [AdminPerumahanController::class, 'storeProgress'])->name('perumahan.rumah.progress.store');
        Route::put('perumahan/{id}/hpp', [AdminPerumahanController::class, 'updateHpp'])->name('perumahan.hpp.update');
        Route::put('perumahan/{id}/hpp/{itemId}', [AdminPerumahanController::class, 'updateHppItem'])->name('perumahan.hpp.item.update');
        Route::put('perumahan/{id}/rumah/{rumahId}/hpp', [AdminPerumahanController::class, 'updateRumahHpp'])->name('perumahan.rumah.hpp.update');
        Route::put('perumahan/{id}/rumah/{rumahId}/hpp/{itemId}', [AdminPerumahanController::class, 'updateRumahHpp'])->name('perumahan.rumah.hpp.item.update');
        Route::post('tahapan-hpp', [AdminPerumahanController::class, 'storeHppStage'])->name('tahapan-hpp.store');
        Route::put('tahapan-hpp/{stage}', [AdminPerumahanController::class, 'updateHppStage'])->name('tahapan-hpp.update');
        Route::delete('tahapan-hpp/{stage}', [AdminPerumahanController::class, 'destroyHppStage'])->name('tahapan-hpp.destroy');
        Route::delete('perumahan/{id}/hpp/{itemId}', [AdminPerumahanController::class, 'destroyHppItem'])->name('perumahan.hpp.item.destroy');
        Route::delete('perumahan/{id}/rumah/{rumahId}/hpp/{itemId}', [AdminPerumahanController::class, 'destroyRumahHppItem'])->name('perumahan.rumah.hpp.item.destroy');
        Route::post('cabang-perusahaan/{id}/lock', [AdminCabangPerusahaanController::class, 'lock'])->name('cabang-perusahaan.lock');
        Route::post('cabang-perusahaan/{id}/unlock', [AdminCabangPerusahaanController::class, 'unlock'])->name('cabang-perusahaan.unlock');
        Route::post('perumahan/{id}/lock', [AdminPerumahanController::class, 'lock'])->name('perumahan.lock');
        Route::post('perumahan/{id}/unlock', [AdminPerumahanController::class, 'unlock'])->name('perumahan.unlock');
        Route::post('master-bank/{id}/lock', [AdminMasterBankController::class, 'lock'])->name('master-bank.lock');
        Route::post('master-bank/{id}/unlock', [AdminMasterBankController::class, 'unlock'])->name('master-bank.unlock');
        Route::post('dokumen-legalitas/{id}/lock', [AdminDokumenLegalitasController::class, 'lock'])->name('dokumen-legalitas.lock');
        Route::post('dokumen-legalitas/{id}/unlock', [AdminDokumenLegalitasController::class, 'unlock'])->name('dokumen-legalitas.unlock');
        Route::post('dokumen-legalitas-rumah/{id}/lock', [AdminDokumenLegalitasRumahController::class, 'lock'])->name('dokumen-legalitas-rumah.lock');
        Route::post('dokumen-legalitas-rumah/{id}/unlock', [AdminDokumenLegalitasRumahController::class, 'unlock'])->name('dokumen-legalitas-rumah.unlock');
        Route::post('master-dokumen-customer/{id}/lock', [AdminDokumenCostumerController::class, 'lock'])->name('master-dokumen-customer.lock');
        Route::post('master-dokumen-customer/{id}/unlock', [AdminDokumenCostumerController::class, 'unlock'])->name('master-dokumen-customer.unlock');
        Route::post('tipe-post/{id}/lock', [AdminTipePostController::class, 'lock'])->name('tipe-post.lock');
        Route::post('tipe-post/{id}/unlock', [AdminTipePostController::class, 'unlock'])->name('tipe-post.unlock');
        Route::post('user/{id}/lock', [AdminUserController::class, 'lock'])->name('user.lock');
        Route::post('user/{id}/unlock', [AdminUserController::class, 'unlock'])->name('user.unlock');
        Route::post('role-permission/{id}/lock', [AdminRolePermissionController::class, 'lock'])->name('role-permission.lock');
        Route::post('role-permission/{id}/unlock', [AdminRolePermissionController::class, 'unlock'])->name('role-permission.unlock');
        Route::resource('cabang-perusahaan', AdminCabangPerusahaanController::class)->parameters(['cabang-perusahaan' => 'id'])->except(['show']);
        Route::resource('perumahan', AdminPerumahanController::class)->parameters(['perumahan' => 'id'])->except(['show']);
        Route::resource('master-bank', AdminMasterBankController::class)->parameters(['master-bank' => 'id'])->except(['show']);
        Route::get('bank-kredit', fn () => redirect()->route('admin.bank-master.index'))->name('bank-kredit.index');
        Route::resource('dokumen-legalitas', AdminDokumenLegalitasController::class)->parameters(['dokumen-legalitas' => 'id'])->except(['show']);
        Route::resource('dokumen-legalitas-rumah', AdminDokumenLegalitasRumahController::class)->parameters(['dokumen-legalitas-rumah' => 'id'])->except(['create', 'show', 'edit']);
        Route::resource('master-dokumen-customer', AdminDokumenCostumerController::class)->parameters(['master-dokumen-customer' => 'id'])->except(['show']);
        Route::resource('tipe-post', AdminTipePostController::class)->parameters(['tipe-post' => 'id'])->except(['show']);
        Route::resource('user', AdminUserController::class)->parameters(['user' => 'id'])->except(['show']);
        Route::resource('role-permission', AdminRolePermissionController::class)->parameters(['role-permission' => 'id'])->except(['create', 'show', 'edit']);
    });

    Route::get('penanganan-penjualan-gagal', [SalesResolutionController::class, 'index'])->name('admin.sales-resolutions.index');
    Route::post('penanganan-penjualan-gagal', [SalesResolutionController::class, 'store'])->name('admin.sales-resolutions.store');
    Route::post('penanganan-penjualan-gagal/{resolution}/lock', [SalesResolutionController::class, 'lock'])->name('admin.sales-resolutions.lock');
    Route::post('penanganan-penjualan-gagal/{resolution}/unlock', [SalesResolutionController::class, 'unlock'])->name('admin.sales-resolutions.unlock');

    Route::prefix('marketing')->name('admin.marketing.')->group(function () {
        Route::get('reservasi-perumahan', [HousingReservationController::class, 'index'])->name('reservations.index');
        Route::get('reservasi-perumahan/create', [HousingReservationController::class, 'create'])->name('reservations.create');
        Route::post('reservasi-perumahan', [HousingReservationController::class, 'store'])->name('reservations.store');
        Route::get('reservasi-perumahan/{reservation}', [HousingReservationController::class, 'show'])->name('reservations.show');
        Route::get('reservasi-perumahan/{reservation}/edit', [HousingReservationController::class, 'edit'])->name('reservations.edit');
        Route::put('reservasi-perumahan/{reservation}', [HousingReservationController::class, 'update'])->name('reservations.update');
        Route::delete('reservasi-perumahan/{reservation}', [HousingReservationController::class, 'destroy'])->name('reservations.destroy');
        Route::post('reservasi-perumahan/{reservation}/lock', [HousingReservationController::class, 'lock'])->name('reservations.lock');
        Route::get('reservasi-perumahan/{reservation}/invoice', [HousingReservationController::class, 'invoice'])->name('reservations.invoice');
        Route::get('reservasi-perumahan/{reservation}/bukti-pembayaran', [HousingReservationController::class, 'paymentProof'])->name('reservations.payment-proof');
        Route::post('reservasi-perumahan/{reservation}/cancel', [HousingReservationController::class, 'cancel'])->name('reservations.cancel');
        Route::get('/', [AdminMarketingController::class, 'index'])->name('index');
        Route::resource('sumber-lead', AdminLeadSourceController::class)->parameters(['sumber-lead' => 'id']);
        Route::post('sumber-lead/{id}/lock', [AdminLeadSourceController::class, 'lock'])->name('sumber-lead.lock');
        Route::post('sumber-lead/{id}/unlock', [AdminLeadSourceController::class, 'unlock'])->name('sumber-lead.unlock');
        Route::get('laporan-lead', [AdminLeadReportController::class, 'index'])->name('laporan-lead.index');
        Route::get('laporan-pipeline', [AdminPipelineReportController::class, 'index'])->name('laporan-pipeline.index');
        Route::get('operasional/{section}', [AdminMarketingOperationsController::class, 'show'])->name('operasional.show');
        Route::post('operasional/{section}', [AdminMarketingOperationsController::class, 'store'])->name('operasional.store');
        Route::put('operasional/{section}/{id}', [AdminMarketingOperationsController::class, 'update'])->name('operasional.update');
        Route::delete('operasional/{section}/{id}', [AdminMarketingOperationsController::class, 'destroy'])->name('operasional.destroy');
        Route::post('operasional/{section}/{id}/lock', [AdminMarketingOperationsController::class, 'lock'])->name('operasional.lock');
        Route::post('operasional/{section}/{id}/unlock', [AdminMarketingOperationsController::class, 'unlock'])->name('operasional.unlock');
        Route::post('operasional/reminder/{id}/complete', [AdminMarketingOperationsController::class, 'completeReminder'])->name('operasional.reminder.complete');
        Route::post('operasional/dokumen/review', [AdminMarketingOperationsController::class, 'reviewDocument'])->name('operasional.document.review');
        Route::get('kwitansi/{id}', [AdminMarketingOperationsController::class, 'receipt'])->name('kwitansi.show');
        Route::get('tools/{section}', [AdminMarketingToolsController::class, 'show'])->name('tools.show');
        Route::post('tools/distribusi-lead/assign', [AdminMarketingToolsController::class, 'assignLead'])->name('tools.distribusi-lead.assign');
        Route::get('transaksi-pembelian/cash', [AdminCashSaleController::class, 'index'])->name('transaksi-pembelian.cash.index');
        Route::post('transaksi-pembelian/cash', [AdminCashSaleController::class, 'store'])->name('transaksi-pembelian.cash.store');
        Route::post('transaksi-pembelian/cash/{id}/payments', [AdminCashSaleController::class, 'storePayment'])->name('transaksi-pembelian.cash.payment.store');
        Route::post('transaksi-pembelian/cash/{id}/handover', [AdminCashSaleController::class, 'handover'])->name('transaksi-pembelian.cash.handover');
        Route::post('transaksi-pembelian/cash/{id}/lock', [AdminCashSaleController::class, 'lock'])->name('transaksi-pembelian.cash.lock');
        Route::post('transaksi-pembelian/cash/{id}/unlock', [AdminCashSaleController::class, 'unlock'])->name('transaksi-pembelian.cash.unlock');
        Route::get('calon-konsumen', [AdminCostumerController::class, 'index'])->name('calon-konsumen.index');
        Route::get('calon-konsumen/create', [AdminCostumerController::class, 'create'])->name('calon-konsumen.create');
        Route::get('calon-konsumen/{id}/edit', [AdminCostumerController::class, 'edit'])->name('calon-konsumen.edit');
        Route::get('calon-konsumen/{id}', [AdminCostumerController::class, 'show'])->name('calon-konsumen.show');
        Route::post('calon-konsumen', [AdminCostumerController::class, 'store'])->name('calon-konsumen.store');
        Route::put('calon-konsumen/{id}', [AdminCostumerController::class, 'update'])->name('calon-konsumen.update');
        Route::delete('calon-konsumen/{id}', [AdminCostumerController::class, 'destroy'])->name('calon-konsumen.destroy');
        Route::post('calon-konsumen/{id}/lock', [AdminCostumerController::class, 'lock'])->name('calon-konsumen.lock');
        Route::post('calon-konsumen/{id}/unlock', [AdminCostumerController::class, 'unlock'])->name('calon-konsumen.unlock');
        Route::get('jejak-follow-up', [AdminFollowUpController::class, 'index'])->name('jejak-follow-up.index');
        Route::get('jejak-follow-up/create', [AdminFollowUpController::class, 'create'])->name('jejak-follow-up.create');
        Route::get('jejak-follow-up/{id}', [AdminFollowUpController::class, 'show'])->name('jejak-follow-up.show');
        Route::get('jejak-follow-up/{id}/edit', [AdminFollowUpController::class, 'edit'])->name('jejak-follow-up.edit');
        Route::post('jejak-follow-up', [AdminFollowUpController::class, 'store'])->name('jejak-follow-up.store');
        Route::put('jejak-follow-up/{id}', [AdminFollowUpController::class, 'update'])->name('jejak-follow-up.update');
        Route::delete('jejak-follow-up/{id}', [AdminFollowUpController::class, 'destroy'])->name('jejak-follow-up.destroy');
        Route::post('jejak-follow-up/{id}/lock', [AdminFollowUpController::class, 'lock'])->name('jejak-follow-up.lock');
        Route::post('jejak-follow-up/{id}/unlock', [AdminFollowUpController::class, 'unlock'])->name('jejak-follow-up.unlock');
        Route::resource('jadwal-survey', AdminSurveyScheduleController::class)->parameters(['jadwal-survey' => 'id'])->except(['create', 'show', 'edit']);
        Route::put('jadwal-survey/{id}/status', [AdminSurveyScheduleController::class, 'updateStatus'])->name('jadwal-survey.status.update');
        Route::post('jadwal-survey/{id}/lock', [AdminSurveyScheduleController::class, 'lock'])->name('jadwal-survey.lock');
        Route::post('jadwal-survey/{id}/unlock', [AdminSurveyScheduleController::class, 'unlock'])->name('jadwal-survey.unlock');
        Route::get('spr', [AdminSprController::class, 'index'])->name('spr.index');
        Route::get('spr/create', [AdminSprController::class, 'create'])->name('spr.create');
        Route::get('spr/{id}', [AdminSprController::class, 'show'])->name('spr.show');
        Route::get('spr/{id}/preview', [AdminSprController::class, 'preview'])->name('spr.preview');
        Route::get('spr/{id}/print', [AdminSprController::class, 'print'])->name('spr.print');
        Route::get('spr/{id}/edit', [AdminSprController::class, 'edit'])->name('spr.edit');
        Route::post('spr', [AdminSprController::class, 'store'])->name('spr.store');
        Route::put('spr/{id}', [AdminSprController::class, 'update'])->name('spr.update');
        Route::post('spr/{id}/approve', [AdminSprController::class, 'approve'])->name('spr.approve');
        Route::post('spr/{id}/reject', [AdminSprController::class, 'reject'])->name('spr.reject');
        Route::post('spr/{id}/lock', [AdminSprController::class, 'lock'])->name('spr.lock');
        Route::post('spr/{id}/unlock', [AdminSprController::class, 'unlock'])->name('spr.unlock');
        Route::get('{slug}', [AdminMarketingController::class, 'show'])->name('show');
    });
});
