import {
    Activity,
    BarChart3,
    Boxes,
    Building2,
    Banknote,
    CalendarClock,
    ClipboardCheck,
    FileCheck2,
    FileBarChart,
    FileText,
    Home,
    KeyRound,
    Library,
    LayoutDashboard,
    MessageCircle,
    ReceiptText,
    RotateCcw,
    Scale,
    ShieldCheck,
    ShoppingCart,
    Target,
    Users,
    Warehouse,
    Wrench,
    UserPlus,
    WalletCards,
    TrendingDown,
    TrendingUp,
} from "lucide-react";

const adminSidebar = [
    {
        title: "Admin Panel",
        items: [
            {
                title: "Dashboard",
                icon: LayoutDashboard,
                link: "/admin/dashboard",
            },
            {
                title: "Approval",
                icon: ClipboardCheck,
                items: [
                    {
                        title: "Daftar Approval",
                        icon: ClipboardCheck,
                        link: "/admin/approval",
                        permission: "approval.view",
                    },
                    {
                        title: "Setting Approval",
                        icon: Target,
                        link: "/admin/approval/settings",
                        permission: "approval.settings",
                    },
                ],
            },
            {
                title: "Proyek",
                icon: Boxes,
                items: [
                    {
                        title: "Kapling / Unit",
                        icon: Home,
                        link: "/admin/unit-rumah",
                        permission: "detail-rumah.view",
                    },
                    {
                        title: "HPP Unit Rumah",
                        icon: FileText,
                        link: "/admin/hpp-unit-rumah",
                        permission: "rab-unit.view",
                    },
                    {
                        title: "Perumahan",
                        icon: Building2,
                        link: "/admin/management/perumahan",
                        permission: "perumahan.view",
                    },
                    {
                        title: "Progress Pembangunan",
                        icon: BarChart3,
                        link: "/admin/progress-pembangunan",
                        permission: "progress.view",
                    },
                    {
                        title: "Jadwal Lapangan",
                        icon: CalendarClock,
                        link: "/admin/jadwal-lapangan",
                        permission: "site-schedule.view",
                    },
                    {
                        title: "Laporan Lapangan",
                        icon: FileText,
                        link: "/admin/laporan-lapangan",
                        permission: "site-report.view",
                    },
                    {
                        title: "Kontrol Kualitas",
                        icon: ShieldCheck,
                        link: "/admin/kontrol-kualitas",
                        permission: "quality-inspection.view",
                    },
                    {
                        title: "Pengawasan Lapangan",
                        icon: FileText,
                        link: "/admin/pengawasan/defect",
                        permission: "field-supervision.view",
                    },
                    {
                        title: "SPK Kontraktor",
                        icon: FileText,
                        link: "/admin/spk-kontraktor",
                        permission: "spk-kontraktor.view",
                    },
                    {
                        title: "Template Pekerjaan SPK",
                        icon: FileText,
                        link: "/admin/spk-template",
                        permissionsAny: ["spk-template-perumahan.view", "spk-template-unit.view"],
                    },
                    {
                        title: "Pembayaran SPK",
                        icon: ReceiptText,
                        link: "/admin/keuangan/pembayaran-spk",
                        permission: "spk-payment.view",
                    },
                    {
                        title: "Inventaris Aset",
                        icon: Wrench,
                        link: "/admin/inventaris-aset",
                        permission: "asset-inventory.view",
                    },
                ],
            },
            {
                title: "Master Data",
                icon: Building2,
                items: [
                    {
                        title: "Users",
                        icon: Users,
                        link: "/admin/management/user",
                        permission: "users.view",
                    },
                    {
                        title: "Role Permission",
                        icon: ShieldCheck,
                        link: "/admin/management/role-permission",
                        permission: "roles.manage",
                    },
                    {
                        title: "Dokumen Pelanggan",
                        icon: FileText,
                        link: "/admin/management/master-dokumen-customer",
                        permission: "dokumen-customer.view",
                    },
                    {
                        title: "Dokumen Legalitas",
                        icon: FileText,
                        link: "/admin/management/dokumen-legalitas",
                        permission: "dokumen-legalitas.view",
                    },
                    {
                        title: "Master Bank",
                        icon: ReceiptText,
                        link: "/admin/management/master-bank",
                        permission: "master-bank.manage",
                    },
                    {
                        title: "Tipe Post",
                        icon: ReceiptText,
                        link: "/admin/management/tipe-post",
                        permission: "tipe-post.manage",
                    },
                    {
                        title: "Kelola Item Material",
                        icon: Boxes,
                        link: "/admin/master-material",
                        permission: "master-material.view",
                    },
                    {
                        title: "Daftar Tukang",
                        icon: Wrench,
                        link: "/admin/tukang",
                        permission: "tukang.view",
                    },
                ],
            },
            {
                title: "Pemasaran & Pelanggan",
                icon: Users,
                items: [
                    {
                        title: "Data Pelanggan",
                        icon: UserPlus,
                        link: "/admin/marketing/calon-konsumen",
                        permission: "customer.view",
                    },
                    {
                        title: "Tindak Lanjut Pelanggan",
                        icon: MessageCircle,
                        link: "/admin/marketing/jejak-follow-up",
                        permission: "customer.follow-up",
                    },
                    {
                        title: "Pengingat Tindak Lanjut",
                        icon: ClipboardCheck,
                        link: "/admin/marketing/operasional/reminder",
                        permission: "marketing.reminder.manage",
                    },
                    {
                        title: "SPR",
                        icon: FileText,
                        link: "/admin/marketing/spr",
                        permission: "booking.view",
                    },
                    {
                        title: "Pembayaran SPR",
                        icon: Banknote,
                        link: "/admin/marketing/pembayaran-spr",
                        permission: "spr-payment.view",
                    },
                    {
                        title: "Pengajuan KPR",
                        icon: ClipboardCheck,
                        link: "/admin/kpr",
                        permission: "kpr.view",
                    },
                    {
                        title: "Akad KPR",
                        icon: FileText,
                        link: "/admin/kpr/proses/akad",
                        permission: "kpr-akad.view",
                    },
                    {
                        title: "Serah Terima",
                        icon: KeyRound,
                        link: "/admin/kpr/proses/serah_terima",
                        permission: "handover-customer.view",
                    },
                    {
                        title: "Unit Tersedia",
                        icon: ClipboardCheck,
                        link: "/admin/marketing/tools/unit-stock",
                        permission: "unit-stock.view",
                    },
                    {
                        title: "Daftar Harga Aktif",
                        icon: ReceiptText,
                        link: "/admin/marketing/tools/pricelist",
                        permission: "pricelist.view",
                    },
                    {
                        title: "Simulasi Cicilan",
                        icon: Banknote,
                        link: "/admin/marketing/tools/simulasi-pembayaran",
                        permission: "payment-simulation.view",
                    },
                ],
            },
            {
                title: "Pemasaran & Analitik",
                icon: Target,
                items: [
                    {
                        title: "Sumber Lead",
                        icon: Users,
                        link: "/admin/marketing/sumber-lead",
                        permission: "marketing.lead-source.manage",
                    },
                    {
                        title: "Laporan Lead",
                        icon: BarChart3,
                        link: "/admin/marketing/laporan-lead",
                        permission: "marketing.lead-report.view",
                    },
                    {
                        title: "Pipeline Semua Marketing",
                        icon: BarChart3,
                        link: "/admin/marketing/operasional/pipeline",
                        permission: "marketing.pipeline-report.view",
                    },
                    {
                        title: "Campaign & Promosi",
                        icon: Target,
                        link: "/admin/marketing/operasional/campaign",
                        permission: "marketing.campaign.manage",
                    },
                    {
                        title: "Validasi Berkas",
                        icon: FileCheck2,
                        link: "/admin/marketing/operasional/dokumen",
                        permission: "marketing.document-review.manage",
                    },
                    {
                        title: "Distribusi Lead",
                        icon: ClipboardCheck,
                        link: "/admin/marketing/tools/distribusi-lead",
                        permission: "marketing.lead-distribution.manage",
                    },
                    {
                        title: "Monitoring Aktivitas",
                        icon: FileText,
                        link: "/admin/marketing/tools/monitoring-aktivitas",
                        permission: "marketing.activity.view",
                    },
                    {
                        title: "Target KPI & Komisi",
                        icon: Target,
                        link: "/admin/marketing/operasional/target-komisi",
                        permission: "marketing.target-commission.manage",
                    },
                    {
                        title: "Leaderboard Sales",
                        icon: BarChart3,
                        link: "/admin/marketing/tools/leaderboard-sales",
                        permission: "marketing.leaderboard.view",
                    },
                    {
                        title: "Tagihan & Kwitansi",
                        icon: WalletCards,
                        link: "/admin/marketing/operasional/piutang",
                        permission: "marketing.receivable.view",
                    },
                ],
            },
            {
                title: "Logistik",
                icon: Warehouse,
                items: [
                    {
                        title: "Data Gudang",
                        icon: Building2,
                        link: "/admin/gudang",
                        permission: "master-material.view",
                    },
                    {
                        title: "Kelola Item Material",
                        icon: Boxes,
                        link: "/admin/master-material",
                        permission: "master-material.view",
                    },
                    {
                        title: "Harga Material",
                        icon: Banknote,
                        link: "/admin/harga-material",
                        permission: "material-price.view",
                    },
                    {
                        title: "Saldo Awal Material",
                        icon: Boxes,
                        link: "/admin/saldo-awal-material",
                        permission: "material-opening-balance.view",
                    },
                    {
                        title: "Stok Material",
                        icon: Warehouse,
                        link: "/admin/stok-material",
                        permission: "site-material-stock.view",
                    },
                    {
                        title: "Permintaan Material",
                        icon: ClipboardCheck,
                        link: "/admin/permintaan-barang",
                        permission: "material-request.view",
                    },
                    {
                        title: "Pemakaian Material",
                        icon: Boxes,
                        link: "/admin/pemakaian-material",
                        permission: "material-usage.view",
                    },
                    {
                        title: "Pengembalian Material",
                        icon: RotateCcw,
                        link: "/admin/pengembalian-material",
                        permission: "material-return.view",
                    },
                    {
                        title: "Logistik",
                        icon: ShoppingCart,
                        link: "/admin/logistik",
                        permission: "material-purchase.view",
                    },
                ],
            },
            {
                title: "Keuangan",
                icon: Scale,
                items: [
                    {
                        title: "Dashboard Keuangan",
                        icon: BarChart3,
                        link: "/admin/keuangan/dashboard",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Daftar Akun / COA",
                        icon: Library,
                        link: "/admin/keuangan/daftar-akun",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Master Rekening Bank",
                        icon: Building2,
                        link: "/admin/management/master-bank",
                        permission: "master-bank.manage",
                    },
                    {
                        title: "Mutasi & Saldo Rekening",
                        icon: Banknote,
                        link: "/admin/rekening-bank",
                        permission: "bank-account-ledger.view",
                    },
                    {
                        title: "Transaksi Kas/Bank",
                        icon: ReceiptText,
                        link: "/admin/keuangan/transaksi-kas-bank",
                        permission: "keuangan.create",
                    },
                    {
                        title: "Jurnal Umum",
                        icon: Activity,
                        link: "/admin/keuangan/jurnal-umum",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Buku Besar",
                        icon: Library,
                        link: "/admin/keuangan/buku-besar",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Neraca Saldo",
                        icon: Scale,
                        link: "/admin/keuangan/neraca-saldo",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Laporan Keuangan",
                        icon: FileBarChart,
                        link: "/admin/keuangan/laba-rugi",
                        permission: "laporan.view",
                    },
                    {
                        title: "Piutang Pelanggan",
                        icon: TrendingUp,
                        link: "/admin/keuangan/piutang",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Hutang Supplier & Kontraktor",
                        icon: TrendingDown,
                        link: "/admin/keuangan/hutang",
                        permission: "keuangan.view",
                    },
                    {
                        title: "Refund SPR",
                        icon: RotateCcw,
                        link: "/admin/keuangan/refund-spr",
                        permission: "refund-spr.view",
                    },
                ],
            },
        ],
    },
];

export default adminSidebar;
