<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Invoice {{ $batch->batch_number }}</title><style>
@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172026;margin:0}.toolbar{position:fixed;right:18px;top:18px}.toolbar button{padding:10px 16px;border:0;border-radius:7px;background:#172026;color:#fff;font-weight:bold}.header{border-bottom:3px solid #b58a3a;padding-bottom:14px;margin-bottom:18px;display:flex;justify-content:space-between}.muted{color:#65727b;font-size:12px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:15px 0}.box{border:1px solid #d8dde1;border-radius:8px;padding:10px}.box strong{display:block;margin-top:5px}.slip{border:1px solid #aeb7bd;border-radius:10px;padding:16px;margin:0 0 16px;break-inside:avoid}.slip-head{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding-bottom:10px;margin-bottom:10px}.row{display:flex;justify-content:space-between;padding:5px 0}.total{border-top:2px solid #172026;margin-top:7px;padding-top:9px;font-size:17px;font-weight:bold}.watermark{position:fixed;inset:42% 0 auto;text-align:center;transform:rotate(-25deg);font-size:70px;font-weight:bold;color:rgba(190,30,30,.12);z-index:-1}.footer{font-size:11px;color:#65727b;margin-top:20px}@media print{.toolbar{display:none}}
</style></head><body>
@unless($isFinal)<div class="watermark">PREVIEW - BELUM FINAL</div>@endunless
<div class="toolbar"><button onclick="window.print()">Cetak Invoice</button></div>
<header class="header"><div><div class="muted">INVOICE PENGGAJIAN PEGAWAI</div><h1 style="margin:6px 0">{{ $batch->batch_number }}</h1><div class="muted">Dibuat oleh {{ $batch->creator?->name ?? '-' }}</div></div><div style="text-align:right"><strong>Periode {{ $batch->period }}</strong><div class="muted" style="margin-top:6px">Tanggal bayar {{ $batch->payment_date->format('d/m/Y') }}</div><div class="muted">Status: {{ $isFinal ? 'DISETUJUI' : strtoupper(str_replace('_',' ',$batch->status)) }}</div></div></header>
<section class="summary"><div class="box"><span class="muted">Jumlah Pegawai</span><strong>{{ $batch->items->count() }} orang</strong></div><div class="box"><span class="muted">Total Bruto</span><strong>Rp {{ number_format($batch->total_gross,0,',','.') }}</strong></div><div class="box"><span class="muted">Total Dibayarkan</span><strong>Rp {{ number_format($batch->total_net,0,',','.') }}</strong></div></section>
@if($batch->notes)<p class="muted"><strong>Catatan:</strong> {{ $batch->notes }}</p>@endif
@foreach($batch->items as $item)<section class="slip"><div class="slip-head"><div><strong>{{ $item->employee_name }}</strong><div class="muted">{{ $item->employee_number ?: '-' }} · {{ $item->job_position }}</div></div><strong>SLIP #{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</strong></div><div class="row"><span>Gaji Pokok</span><span>Rp {{ number_format($item->basic_salary,0,',','.') }}</span></div><div class="row"><span>Tunjangan Tetap</span><span>Rp {{ number_format($item->fixed_allowance,0,',','.') }}</span></div><div class="row"><span>Tunjangan Lain</span><span>Rp {{ number_format($item->other_allowance,0,',','.') }}</span></div><div class="row"><span>Potongan</span><span>(Rp {{ number_format($item->deductions,0,',','.') }})</span></div><div class="row total"><span>Gaji Bersih</span><span>Rp {{ number_format($item->net_salary,0,',','.') }}</span></div>@if($item->notes)<p class="muted">Catatan: {{ $item->notes }}</p>@endif</section>@endforeach
<div class="footer">Dokumen ini memuat seluruh slip dalam satu transaksi penggajian. Dicetak {{ now()->format('d/m/Y H:i') }}.</div></body></html>
