import { Head, Link, router, useForm } from "@inertiajs/react";
import { ArrowLeft, Ban, PackageOpen, Printer, Save } from "lucide-react";
import { Button, CurrencyInput, Input } from "../../../Components/UI";
import AdminLayout from "../../../Layouts/AdminLayout";

const money = (value) => `Rp ${Number(value || 0).toLocaleString("id-ID")}`;
const date = (value) => value ? new Date(value).toLocaleDateString("id-ID") : "-";

export default function Show({ title, row, summary, progressUrl, cancelUrl, indexUrl, canProgress, canCancel, addenda = [], addendumUrl, canAddendum, materialUsageUrl, materialRequestUrl, canMaterialRequest, canMaterialUsage, handover, handoverUrl, canHandover, defects = [], defectUrl, canDefect }) {
    const progress = useForm({ quality_upgrade_contract_item_id: String(row.items?.[0]?.id ?? ""), report_date: new Date().toISOString().slice(0, 10), progress_percent: "", work_status: "in_progress", material_cost: "0", labor_cost: "0", other_cost: "0", notes: "", inspection_notes: "" });
    const addendum = useForm({ addendum_date: new Date().toISOString().slice(0, 10), reason: "", value_change: "0", finish_date_change: "", billing_due_date: "" });
    const handoverForm = useForm({ handover_date: new Date().toISOString().slice(0, 10), notes: "", checklist: { work_complete: false, site_clean: false, documents_complete: false }, customer_evidence: null, supervisor_evidence: null });
    const defect = useForm({ quality_upgrade_contract_item_id: "", reported_date: new Date().toISOString().slice(0, 10), severity: "minor", description: "", target_date: "", evidence: null });
    const submitProgress = (event) => { event.preventDefault(); progress.post(progressUrl, { preserveScroll: true, onSuccess: () => progress.reset("progress_percent", "material_cost", "labor_cost", "other_cost", "notes", "inspection_notes") }); };
    const cancel = () => { const reason = window.prompt("Alasan pembatalan (minimal 10 karakter). Pembayaran harus sudah direversal/refund:"); if (reason) router.post(cancelUrl, { reason }); };

    return <><Head title={title}/><div className="grid gap-5">
        <header className="rounded-2xl border bg-white/90 p-5 dark:bg-white/5">
            <Button as={Link} href={indexUrl} size="sm" variant="outline"><ArrowLeft size={15}/> Kembali</Button>
            <div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-black">{row.contract_no}</h1><p className="text-sm text-ink-soft">{row.customer?.nama} · {row.unit?.perumahan?.nama_perusahaan} · {row.unit?.display_label}</p></div><div className="text-right"><p className="font-black">{row.company?.nama_cabang}</p><p className="text-sm">{row.business_status} · progres {Number(row.progress_percent || 0)}%</p>{canCancel && <Button type="button" className="mt-2" size="sm" variant="outline" onClick={cancel}><Ban size={14}/> Batalkan</Button>}</div></div>
        </header>
        <section className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{[
            ["Nilai Kontrak", row.contract_value], ["Ditagih", summary.billed], ["Dibayar", summary.paid], ["Piutang", summary.outstanding], ["Biaya Aktual", summary.actual_cost], ["Margin Aktual", summary.actual_margin],
        ].map(([label, value]) => <div key={label} className="rounded-xl border bg-white p-4 dark:bg-white/5"><p className="text-xs font-bold text-ink-soft">{label}</p><p className="mt-1 font-black">{money(value)}</p></div>)}</section>
        <section className="rounded-2xl border bg-white/90 p-5 dark:bg-white/5"><h2 className="text-lg font-black">Pekerjaan, progres, dan biaya</h2><div className="mt-4 overflow-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">Pekerjaan</th><th>Nilai</th><th>Progres</th><th>Material</th><th>Upah</th><th>Lainnya</th><th>Status</th></tr></thead><tbody>{row.items.map((item) => <tr key={item.id} className="border-b"><td className="p-2"><strong>{item.name}</strong><br/><span className="text-xs">{item.specification}</span></td><td>{money(item.total)}</td><td>{item.progress_percent}%</td><td>{money(item.material_cost)}</td><td>{money(item.labor_cost)}</td><td>{money(item.other_cost)}</td><td>{item.work_status}</td></tr>)}</tbody></table></div></section>
        {(canMaterialRequest || canMaterialUsage) && <div className="flex flex-wrap gap-2">{canMaterialRequest && <Button as={Link} href={materialRequestUrl} variant="outline"><PackageOpen size={15}/> Buat permintaan material</Button>}{canMaterialUsage && <Button as={Link} href={materialUsageUrl} variant="outline"><PackageOpen size={15}/> Catat pemakaian material kontrak</Button>}</div>}
        {canProgress && <form onSubmit={submitProgress} className="grid gap-3 rounded-2xl border bg-white/90 p-5 md:grid-cols-4 dark:bg-white/5"><h2 className="md:col-span-4 text-lg font-black">Laporan pengawasan</h2>
            <Field label="Item pekerjaan"><select className="w-full rounded-lg border p-3" value={progress.data.quality_upgrade_contract_item_id} onChange={(e) => progress.setData("quality_upgrade_contract_item_id", e.target.value)}>{row.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
            <Field label="Tanggal"><Input type="date" value={progress.data.report_date} onChange={(e) => progress.setData("report_date", e.target.value)}/></Field>
            <Field label="Progres kumulatif (%)"><Input type="number" min="0" max="100" value={progress.data.progress_percent} onChange={(e) => progress.setData("progress_percent", e.target.value)}/></Field>
            <Field label="Status"><select className="w-full rounded-lg border p-3" value={progress.data.work_status} onChange={(e) => progress.setData("work_status", e.target.value)}><option value="in_progress">Dikerjakan</option><option value="inspection">Pemeriksaan</option><option value="defect">Ada cacat/temuan</option><option value="completed">Selesai</option></select></Field>
            <Field label="Biaya material"><CurrencyInput value={progress.data.material_cost} onChange={(value) => progress.setData("material_cost", value)}/></Field><Field label="Upah buruh"><CurrencyInput value={progress.data.labor_cost} onChange={(value) => progress.setData("labor_cost", value)}/></Field><Field label="Biaya lainnya"><CurrencyInput value={progress.data.other_cost} onChange={(value) => progress.setData("other_cost", value)}/></Field>
            <Field label="Catatan pekerjaan"><Input value={progress.data.notes} onChange={(e) => progress.setData("notes", e.target.value)}/></Field><Field label="Hasil pemeriksaan" className="md:col-span-3"><Input value={progress.data.inspection_notes} onChange={(e) => progress.setData("inspection_notes", e.target.value)}/></Field>
            <Field label="Foto bukti" className="md:col-span-3"><Input type="file" accept="image/*" onChange={(e) => progress.setData("evidence", e.target.files?.[0] ?? null)}/></Field>
            <div className="self-end"><Button type="submit" disabled={progress.processing}><Save size={15}/> Simpan laporan</Button></div>
        </form>}
        <section className="rounded-2xl border bg-white/90 p-5 dark:bg-white/5"><h2 className="text-lg font-black">Riwayat pengawasan</h2><div className="mt-3 grid gap-2">{row.progresses?.length ? row.progresses.map((item) => <div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between"><strong>{item.item?.name}</strong><span>{date(item.report_date)} · {item.progress_percent}%</span></div><p className="text-sm">{item.notes || "Tanpa catatan"} {item.inspection_notes && `— Pemeriksaan: ${item.inspection_notes}`}</p><p className="mt-1 text-xs">Material {money(item.material_cost)} · Upah {money(item.labor_cost)} · Lainnya {money(item.other_cost)}</p>{item.evidence_url && <a className="text-sm font-bold text-emerald-700 underline" href={item.evidence_url} target="_blank">Lihat foto bukti</a>}</div>) : <p className="text-sm text-ink-soft">Belum ada laporan progres.</p>}</div></section>
        <section className="rounded-2xl border bg-white/90 p-5 dark:bg-white/5"><h2 className="text-lg font-black">Addendum kontrak · versi dokumen {row.document_version}</h2>
            {canAddendum && <form className="mt-3 grid gap-3 md:grid-cols-5" onSubmit={(e) => { e.preventDefault(); addendum.post(addendumUrl, { preserveScroll: true, onSuccess: () => addendum.reset("reason", "value_change", "finish_date_change", "billing_due_date") }); }}><Field label="Tanggal"><Input type="date" value={addendum.data.addendum_date} onChange={(e) => addendum.setData("addendum_date", e.target.value)}/></Field><Field label="Tambahan nilai"><CurrencyInput value={addendum.data.value_change} onChange={(value) => addendum.setData("value_change", value)}/></Field><Field label="Jatuh tempo"><Input type="date" value={addendum.data.billing_due_date} onChange={(e) => addendum.setData("billing_due_date", e.target.value)}/></Field><Field label="Perubahan selesai"><Input type="date" value={addendum.data.finish_date_change} onChange={(e) => addendum.setData("finish_date_change", e.target.value)}/></Field><Field label="Alasan"><Input value={addendum.data.reason} onChange={(e) => addendum.setData("reason", e.target.value)}/></Field><div><Button type="submit" disabled={addendum.processing}>Buat draft</Button></div></form>}
            <div className="mt-4 grid gap-2">{addenda.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><div><strong>{item.addendum_no}</strong><p className="text-sm">{item.reason} · {money(item.value_change)} · {item.approval_stage || item.status}</p></div><div className="flex gap-1">{item.can_lock && <Button size="sm" onClick={() => router.post(item.lock_url)}>Finalisasi</Button>}{item.can_unlock && <Button size="sm" variant="outline" onClick={() => router.post(item.unlock_url)}>Unlock</Button>}{item.can_review && <><Button size="sm" onClick={() => router.post(item.approve_url)}>Approve</Button><Button size="sm" variant="outline" onClick={() => { const note = prompt("Alasan penolakan"); if (note) router.post(item.reject_url, { note }); }}>Reject</Button></>}{item.status === "approved" && <Button as="a" href={item.print_url} target="_blank" size="sm" variant="outline"><Printer size={14}/></Button>}{item.can_delete && <Button size="sm" variant="outline" onClick={() => router.delete(item.delete_url)}>Hapus</Button>}</div></div>)}</div>
        </section>
        <section className="rounded-2xl border bg-white/90 p-5 dark:bg-white/5"><div className="flex justify-between"><div><h2 className="text-lg font-black">Serah terima dan garansi</h2><p className="text-sm text-ink-soft">Garansi berakhir: {row.warranty_end_date ? date(row.warranty_end_date) : "belum dimulai"}</p></div>{handover && <strong>{handover.status} · {handover.approval_stage}</strong>}</div>
            {canHandover && !handover && <form className="mt-3 grid gap-3 md:grid-cols-3" onSubmit={(e) => { e.preventDefault(); handoverForm.post(handoverUrl); }}><Field label="Tanggal serah terima"><Input type="date" value={handoverForm.data.handover_date} onChange={(e) => handoverForm.setData("handover_date", e.target.value)}/></Field><Field label="Catatan"><Input value={handoverForm.data.notes} onChange={(e) => handoverForm.setData("notes", e.target.value)}/></Field><div className="grid gap-1 text-sm">{[["work_complete","Pekerjaan 100%"],["site_clean","Lokasi bersih"],["documents_complete","Dokumen lengkap"]].map(([key,label]) => <label key={key}><input type="checkbox" checked={handoverForm.data.checklist[key]} onChange={(e) => handoverForm.setData("checklist", {...handoverForm.data.checklist,[key]:e.target.checked})}/> {label}</label>)}</div><Field label="Bukti customer"><Input type="file" accept="image/*" onChange={(e) => handoverForm.setData("customer_evidence", e.target.files?.[0] ?? null)}/></Field><Field label="Bukti pengawas"><Input type="file" accept="image/*" onChange={(e) => handoverForm.setData("supervisor_evidence", e.target.files?.[0] ?? null)}/></Field><div className="self-end"><Button type="submit">Simpan draft</Button></div></form>}
            {handover && <div className="mt-3 flex gap-2">{handover.can_lock && <Button onClick={() => router.post(handover.lock_url)}>Finalisasi serah terima</Button>}{handover.can_unlock && <Button variant="outline" onClick={() => router.post(handover.unlock_url)}>Unlock</Button>}{handover.can_review && <><Button onClick={() => router.post(handover.approve_url)}>Approve</Button><Button variant="outline" onClick={() => { const note=prompt("Alasan penolakan"); if(note) router.post(handover.reject_url,{note}); }}>Reject</Button></>}</div>}
        </section>
        <section className="rounded-2xl border bg-white/90 p-5 dark:bg-white/5"><h2 className="text-lg font-black">Defect dan perbaikan</h2>
            {canDefect && <form className="mt-3 grid gap-3 md:grid-cols-5" onSubmit={(e) => { e.preventDefault(); defect.post(defectUrl, { preserveScroll:true, onSuccess:()=>defect.reset("description","target_date","evidence") }); }}><Field label="Item"><select className="rounded-lg border p-3" value={defect.data.quality_upgrade_contract_item_id} onChange={(e)=>defect.setData("quality_upgrade_contract_item_id",e.target.value)}><option value="">Umum</option>{row.items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Tanggal"><Input type="date" value={defect.data.reported_date} onChange={(e)=>defect.setData("reported_date",e.target.value)}/></Field><Field label="Tingkat"><select className="rounded-lg border p-3" value={defect.data.severity} onChange={(e)=>defect.setData("severity",e.target.value)}><option value="minor">Minor</option><option value="major">Major</option><option value="critical">Kritis</option></select></Field><Field label="Target"><Input type="date" value={defect.data.target_date} onChange={(e)=>defect.setData("target_date",e.target.value)}/></Field><Field label="Temuan"><Input value={defect.data.description} onChange={(e)=>defect.setData("description",e.target.value)}/></Field><Field label="Foto"><Input type="file" accept="image/*" onChange={(e)=>defect.setData("evidence",e.target.files?.[0]??null)}/></Field><div><Button type="submit">Catat temuan</Button></div></form>}
            <div className="mt-4 grid gap-2">{defects.map(item=><div key={item.id} className="flex flex-wrap justify-between rounded-xl border p-3"><div><strong>{item.defect_no} · {item.severity}</strong><p className="text-sm">{item.description} · {item.status}</p>{item.evidence_url&&<a href={item.evidence_url} target="_blank" className="text-sm underline">Foto temuan</a>}</div><div className="flex gap-1">{item.can_resolve&&<Button size="sm" onClick={()=>{const resolution_notes=prompt("Catatan penyelesaian");if(resolution_notes)router.post(item.resolve_url,{resolution_notes});}}>Selesaikan</Button>}{item.can_delete&&<Button size="sm" variant="outline" onClick={()=>router.delete(item.delete_url)}>Hapus</Button>}</div></div>)}</div>
        </section>
    </div></>;
}
function Field({ label, children, className = "" }) { return <label className={`grid gap-1 text-sm font-bold ${className}`}><span>{label}</span>{children}</label>; }
Show.layout = (page) => <AdminLayout title={page.props.title}>{page}</AdminLayout>;
