<!doctype html><html lang="id"><head><meta charset="utf-8"><style>
@page{margin:{{ $printConfig['margin_top_mm'] }}mm {{ $printConfig['margin_right_mm'] }}mm {{ $printConfig['margin_bottom_mm'] }}mm {{ $printConfig['margin_left_mm'] }}mm}
body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:11px}.head{text-align:center;border-bottom:3px solid #172033;padding-bottom:12px}.head h1{font-size:18px;margin:0}.meta{margin-top:14px;width:100%;border-collapse:collapse}.meta td{padding:4px}.data{width:100%;border-collapse:collapse;margin-top:18px}.data th,.data td{border:1px solid #94a3b8;padding:7px;text-align:left}.data th{width:34%;background:#e2e8f0}.watermark{position:fixed;top:42%;left:12%;font-size:72px;color:rgba(148,163,184,.18);transform:rotate(-28deg);z-index:-1}.signatures{width:100%;margin-top:55px;border-collapse:collapse;page-break-inside:avoid}.signatures td{width:33.33%;text-align:center;vertical-align:top;padding:0 12px}.space{height:75px}.line{border-top:1px solid #172033;padding-top:5px;font-weight:bold}.foot{position:fixed;bottom:0;color:#64748b;font-size:9px}
</style></head><body>
@php($sectionLabels=['loans'=>'PEMINJAMAN','returns'=>'PENGEMBALIAN','transfers'=>'MUTASI','damages'=>'KERUSAKAN','losses'=>'KEHILANGAN','stock-opname'=>'STOCK OPNAME','replacements'=>'PENGGANTIAN KOMPONEN','usage'=>'PENGGUNAAN','maintenance'=>'PERAWATAN','fuel'=>'PENGISIAN BBM'])
@php($statusLabels=['draft'=>'DRAF','submitted'=>'DIAJUKAN','pending'=>'MENUNGGU PERSETUJUAN','approved'=>'DISETUJUI','rejected'=>'DITOLAK'])
<div class="watermark">{{ $official ? 'RESMI' : 'DRAF' }}</div><div class="head"><h1>BUKTI TRANSAKSI {{ $sectionLabels[$section] ?? strtoupper(str_replace('-', ' ', $section)) }}</h1><div>{{ $module === 'inventory' ? 'ASET PERUSAHAAN' : 'ALAT BERAT' }}</div></div>
<table class="meta"><tr><td><b>Nomor Dokumen</b></td><td>: {{ $archive->document_no }}</td><td><b>Status</b></td><td>: {{ $statusLabels[$archive->status] ?? strtoupper($archive->status) }}</td></tr><tr><td><b>Dicetak</b></td><td>: {{ $printedAt }}</td><td><b>Cetakan ke</b></td><td>: {{ $archive->print_count + ($official ? 0 : 1) }}</td></tr></table>
<table class="data">@foreach($rows as $item)<tr><th>{{ $item['label'] }}</th><td>{{ $item['value'] }}</td></tr>@endforeach</table>
@if($archive->approval_notes)<p><b>Catatan Persetujuan:</b> {{ $archive->approval_notes }}</p>@endif
<table class="signatures"><tr><td>Penanggung Jawab<div class="space"></div><div class="line">{{ $responsible }}</div></td><td>Pemberi Persetujuan<div class="space"></div><div class="line">{{ $approver }}</div></td><td>Petugas Cetak<div class="space"></div><div class="line">{{ $printer }}</div></td></tr></table>
<div class="foot">Dokumen dibuat oleh sistem. Petugas dan waktu pencetakan tercatat otomatis. {{ $official ? 'Dokumen resmi setelah disetujui.' : 'Pratinjau draf — belum menjadi arsip resmi.' }}</div></body></html>
