import { Head, Link, useForm } from "@inertiajs/react";
import { ArrowLeft, CheckCircle2, RotateCcw, Save, XCircle } from "lucide-react";
import { Button, CurrencyInput, Dropdown, Input, Textarea } from "../../../../Components/UI";
import AdminLayout from "../../../../Layouts/AdminLayout";

const money = (value) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Number(value || 0));

export default function RefundFormPage({ title, mode, action, baseUrl, actionUrl, row, bankOptions }) {
    const form = useForm(mode === "request" ? { alasan_batal: row.alasan_batal ?? "Customer batal", refund_amount: String(row.refundable_paid || ""), refund_master_bank_id: "", refund_at: new Date().toISOString().slice(0, 10), catatan: "" } : { note: "" });
    const submit = (event) => { event.preventDefault(); form.post(actionUrl); };
    return <><Head title={title} /><div className="mx-auto grid max-w-4xl gap-5 pb-8">
        <section className="rounded-2xl bg-gradient-to-br from-ink via-graphite to-[#27323b] px-6 py-5 text-white shadow-lg"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.16em] text-champagne"><RotateCcw size={16} /> Refund SPR</p><h1 className="mt-2 text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-white/65">{row.customer} · {row.unit} · {row.perumahan}</p></div><Button as={Link} href={baseUrl} variant="outline" className="border-white/20 bg-white/10 text-white"><ArrowLeft size={17} /> Kembali</Button></div></section>
        <form className="grid gap-4" onSubmit={submit}><section className="rounded-2xl border border-silver-deep/60 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/[0.04]"><div className="mb-5 grid gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800"><span>SPR: {row.kode_spr}</span><span>Dana dapat direfund: {money(row.refundable_paid)}</span>{row.refund_amount > 0 && <span>Nilai diajukan: {money(row.refund_amount)}</span>}</div>
        {mode === "request" ? <div className="grid gap-5 md:grid-cols-2"><Input className="md:col-span-2" label="Alasan Batal" required value={form.data.alasan_batal} error={form.errors.alasan_batal} onChange={(event) => form.setData("alasan_batal", event.target.value)} /><CurrencyInput label="Jumlah Refund" required value={form.data.refund_amount} error={form.errors.refund_amount} onChange={(value) => form.setData("refund_amount", value)} /><div className="grid gap-2"><span className="text-sm font-extrabold">Bank/Kas Pengembalian *</span><Dropdown value={form.data.refund_master_bank_id} options={bankOptions} onChange={(value) => form.setData("refund_master_bank_id", value)} />{form.errors.refund_master_bank_id && <span className="text-xs font-bold text-red-600">{form.errors.refund_master_bank_id}</span>}</div><Input label="Tanggal Pengembalian" type="date" value={form.data.refund_at} error={form.errors.refund_at} onChange={(event) => form.setData("refund_at", event.target.value)} /><div className="md:col-span-2"><Textarea label="Catatan" value={form.data.catatan} error={form.errors.catatan} onChange={(event) => form.setData("catatan", event.target.value)} /></div></div> : <Textarea label={action === "reject" ? "Alasan Penolakan" : "Catatan Approval"} required={action === "reject"} value={form.data.note} error={form.errors.note} onChange={(event) => form.setData("note", event.target.value)} />}
        </section><div className="flex justify-end gap-3 rounded-xl border bg-white p-4 dark:border-white/10 dark:bg-graphite"><Button as={Link} href={baseUrl} variant="outline">Batal</Button><Button disabled={form.processing} variant={action === "reject" ? "outline" : "dark"}>{action === "reject" ? <XCircle size={17} /> : mode === "review" ? <CheckCircle2 size={17} /> : <Save size={17} />} {action === "reject" ? "Tolak Refund" : mode === "review" ? "Setujui Refund" : "Ajukan Refund"}</Button></div></form>
    </div></>;
}
RefundFormPage.layout = (page) => <AdminLayout title={page?.props?.title ?? "Form Refund SPR"}>{page}</AdminLayout>;
