import { Head, router } from '@inertiajs/react';
import { ArrowLeft, Gauge, Settings, TriangleAlert, Wrench } from 'lucide-react';
import { Button } from '../../../Components/UI';
import AdminLayout from '../../../Layouts/AdminLayout';

const text=(v)=>String(v??'-').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
function Table({title,rows=[]}){const cols=rows.length?Object.keys(rows[0]).filter(k=>!['deleted_at','created_by','updated_by'].includes(k)).slice(0,7):[];return <section className="overflow-hidden rounded-lg border border-white/80 bg-white/78 shadow-soft dark:border-white/10 dark:bg-white/8"><div className="border-b border-silver-deep/60 px-5 py-4"><h3 className="font-extrabold">{title}</h3></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-silver-soft/70 text-left text-xs uppercase text-ink-soft"><tr>{cols.map(c=><th className="px-4 py-3" key={c}>{text(c)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t border-silver-deep/50" key={r.id??i}>{cols.map(c=><td className="px-4 py-3" key={c}>{text(r[c])}</td>)}</tr>)}{!rows.length&&<tr><td className="px-5 py-8 text-center text-ink-soft">Belum ada riwayat.</td></tr>}</tbody></table></div></section>}
export default function Show({title,equipment,components=[],usages=[],maintenances=[],damages=[],replacements=[],indexUrl}){return <><Head title={`${title} - ${equipment.name}`}/><div className="grid gap-6"><section className="rounded-lg border border-white/80 bg-white/78 p-6 shadow-soft dark:border-white/10 dark:bg-white/8"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-ink-soft">{equipment.code} • {equipment.type_name}</p><h2 className="mt-2 text-3xl font-extrabold">{equipment.name}</h2><p className="mt-2 text-ink-soft">{equipment.brand||'-'} {equipment.model||''} • {equipment.year||'-'} • {text(equipment.status)}</p></div><Button variant="outline" onClick={()=>router.get(indexUrl)}><ArrowLeft size={16}/> Kembali</Button></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Gauge,'Hour Meter',Number(equipment.current_hour_meter).toLocaleString('id-ID')],[Settings,'Komponen Terpasang',components.length],[Wrench,'Total Maintenance',maintenances.length],[TriangleAlert,'Riwayat Kerusakan',damages.length]].map(([Icon,l,v])=><div className="rounded-lg border border-white/80 bg-white/78 p-5 shadow-soft" key={l}><Icon size={20}/><p className="mt-3 text-xs font-extrabold uppercase text-ink-soft">{l}</p><p className="mt-2 text-2xl font-extrabold">{v}</p></div>)}</section><section className="grid gap-4 rounded-lg border border-white/80 bg-white/78 p-6 shadow-soft md:grid-cols-3">{[['Nomor Seri',equipment.serial_no],['Nomor Polisi',equipment.license_plate],['Kepemilikan',text(equipment.ownership)],['Merk / Model',`${equipment.brand||'-'} / ${equipment.model||'-'}`],['Tahun',equipment.year],['Status',text(equipment.status)]].map(([l,v])=><div key={l}><p className="text-xs font-extrabold uppercase text-ink-soft">{l}</p><p className="mt-1 font-bold">{v||'-'}</p></div>)}</section><Table title="Komponen Sedang Terpasang" rows={components}/><Table title="Riwayat Penggunaan" rows={usages}/><Table title="Riwayat Maintenance" rows={maintenances}/><Table title="Riwayat Kerusakan" rows={damages}/><Table title="Riwayat Penggantian Komponen" rows={replacements}/></div></>}
Show.layout=(page)=><AdminLayout title={page?.props?.title??'Detail Alat Berat'}>{page}</AdminLayout>;
