import { Head, router } from '@inertiajs/react';
import { ArrowLeft, Fuel, Gauge, MapPin, Settings, TriangleAlert, UserRound, Wrench } from 'lucide-react';
import { Button } from '../../../Components/UI';
import AdminLayout from '../../../Layouts/AdminLayout';

const text = (value) => value === null || value === undefined || value === '' ? '-' : String(value).replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

function Table({ title, columns, rows = [] }) {
    return <section className="overflow-hidden rounded-xl border border-white/80 bg-white/80 shadow-soft dark:border-white/10 dark:bg-white/8"><div className="border-b border-silver-deep/60 px-5 py-4"><h3 className="font-extrabold">{title}</h3></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-silver-soft/70 text-left text-xs uppercase text-ink-soft"><tr>{columns.map((column) => <th className="whitespace-nowrap px-4 py-3" key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-silver-deep/50" key={row.id ?? index}>{columns.map((column) => <td className="px-4 py-3" key={column.key}>{column.render ? column.render(row) : text(row[column.key])}</td>)}</tr>)}{!rows.length && <tr><td className="px-5 py-8 text-center text-ink-soft" colSpan={columns.length}>Belum ada riwayat.</td></tr>}</tbody></table></div></section>;
}

export default function Show({ title, equipment, components = [], usages = [], maintenances = [], damages = [], replacements = [], fuelings = [], currentUsage = null, indexUrl }) {
    const totalFuel = fuelings.reduce((total, fueling) => total + Number(fueling.liters || 0), 0);
    return <><Head title={`${title} - ${equipment.name}`} /><div className="grid gap-6">
        <section className="rounded-xl border border-white/80 bg-white/80 p-6 shadow-soft dark:border-white/10 dark:bg-white/8"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-ink-soft">{equipment.type_name} · {equipment.code}</p><h1 className="mt-2 text-3xl font-extrabold">{equipment.name}</h1><p className="mt-2 text-ink-soft">{equipment.brand || '-'} {equipment.model || ''} · {equipment.year || '-'} · {text(equipment.status)}</p></div><Button variant="outline" onClick={() => router.get(indexUrl)}><ArrowLeft size={16} /> Kembali</Button></div></section>

        {currentUsage && <section className="rounded-xl border border-blue-200 bg-blue-50 p-5 text-blue-950"><div className="flex items-start gap-3"><MapPin className="mt-1" size={20} /><div><p className="text-xs font-black uppercase tracking-wider">Sedang Digunakan</p><h2 className="mt-1 text-xl font-black">{currentUsage.project_name || currentUsage.work_location || 'Lokasi belum dicatat'}{currentUsage.house_number ? ` · Unit ${currentUsage.house_number}` : ''}</h2><p className="mt-1 text-sm font-semibold">Operator {currentUsage.operator_name} · Mulai HM {currentUsage.hour_meter_start} · Transaksi {currentUsage.transaction_no}</p></div></div></section>}

        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[[Gauge, 'Hour Meter', Number(equipment.current_hour_meter).toLocaleString('id-ID')], [Settings, 'Komponen Terpasang', components.length], [UserRound, 'Riwayat Penggunaan', usages.length], [Wrench, 'Maintenance', maintenances.length], [TriangleAlert, 'Kerusakan', damages.length], [Fuel, 'Total BBM', `${totalFuel.toLocaleString('id-ID')} L`]].map(([Icon, label, value]) => <div className="rounded-xl border border-white/80 bg-white/80 p-4 shadow-soft" key={label}><Icon size={20} /><p className="mt-3 text-xs font-extrabold uppercase text-ink-soft">{label}</p><p className="mt-2 text-xl font-extrabold">{value}</p></div>)}</section>

        <section className="grid gap-4 rounded-xl border border-white/80 bg-white/80 p-6 shadow-soft md:grid-cols-3">{[['Nama Alat', equipment.name], ['Jenis', equipment.type_name], ['Nomor Seri', equipment.serial_no], ['Nomor Polisi', equipment.license_plate], ['Kepemilikan', text(equipment.ownership)], ['Merk / Model', `${equipment.brand || '-'} / ${equipment.model || '-'}`], ['Tahun', equipment.year], ['Status', text(equipment.status)]].map(([label, value]) => <div key={label}><p className="text-xs font-extrabold uppercase text-ink-soft">{label}</p><p className="mt-1 font-bold">{value || '-'}</p></div>)}</section>

        <Table title="Komponen Sedang Terpasang" rows={components} columns={[{ key: 'name', label: 'Nama Komponen' }, { key: 'code', label: 'Kode' }, { key: 'component_type', label: 'Tipe' }, { key: 'serial_no', label: 'Nomor Seri' }, { key: 'condition', label: 'Kondisi' }, { key: 'status', label: 'Status' }]} />
        <Table title="Riwayat Penggunaan" rows={usages} columns={[{ key: 'transaction_no', label: 'Nomor' }, { key: 'date', label: 'Tanggal' }, { key: 'operator_name', label: 'Operator' }, { key: 'project_name', label: 'Perumahan' }, { key: 'house_number', label: 'Unit Rumah', render: (row) => row.house_number ? `Unit ${row.house_number}` : '-' }, { key: 'work_location', label: 'Lokasi Tambahan' }, { key: 'hour_meter_start', label: 'HM Awal' }, { key: 'hour_meter_end', label: 'HM Akhir' }, { key: 'duration_hours', label: 'Durasi' }, { key: 'status', label: 'Status' }]} />
        <Table title="Riwayat Maintenance" rows={maintenances} columns={[{ key: 'maintenance_no', label: 'Nomor' }, { key: 'date', label: 'Tanggal' }, { key: 'maintenance_type', label: 'Jenis' }, { key: 'workshop', label: 'Bengkel' }, { key: 'cost', label: 'Biaya', render: (row) => `Rp ${Number(row.cost || 0).toLocaleString('id-ID')}` }, { key: 'next_schedule', label: 'Jadwal Berikut' }, { key: 'status', label: 'Status' }]} />
        <Table title="Riwayat Kerusakan" rows={damages} columns={[{ key: 'date', label: 'Tanggal' }, { key: 'description', label: 'Kerusakan' }, { key: 'severity', label: 'Tingkat' }, { key: 'repair_status', label: 'Status Perbaikan' }, { key: 'completed_date', label: 'Selesai' }, { key: 'notes', label: 'Catatan' }]} />
        <Table title="Riwayat Penggantian Komponen" rows={replacements} columns={[{ key: 'transaction_no', label: 'Nomor' }, { key: 'date', label: 'Tanggal' }, { key: 'old_component_name', label: 'Komponen Lama' }, { key: 'new_component_name', label: 'Komponen Baru' }, { key: 'hour_meter', label: 'Hour Meter' }, { key: 'reason', label: 'Alasan' }, { key: 'operator_name', label: 'Operator' }, { key: 'technician', label: 'Teknisi' }]} />
        <Table title="Riwayat Pengisian BBM" rows={fuelings} columns={[{ key: 'date', label: 'Tanggal' }, { key: 'fuel_type', label: 'Jenis BBM' }, { key: 'liters', label: 'Liter' }, { key: 'price_per_liter', label: 'Harga/Liter', render: (row) => `Rp ${Number(row.price_per_liter || 0).toLocaleString('id-ID')}` }, { key: 'total_cost', label: 'Total', render: (row) => `Rp ${Number(row.total_cost || 0).toLocaleString('id-ID')}` }, { key: 'hour_meter', label: 'Hour Meter' }, { key: 'notes', label: 'Catatan' }]} />
    </div></>;
}

Show.layout = (page) => <AdminLayout title={page?.props?.title ?? 'Detail Alat Berat'}>{page}</AdminLayout>;
