<?php

namespace App\Support;

class SalesProcessDefinitions
{
    public static function dependencies(string $code, string $method): array
    {
        return match ($code) {
            'contract_signing' => $method === 'kpr_bank' ? ['contract_preparation'] : ($method === 'kpr_developer' ? ['internal_approval'] : ['contract_review']),
            'installment_monitoring' => ['contract_signing'],'bank_disbursement' => ['contract_signing'],
            'construction_preparation' => ['contract_signing'],'construction' => ['construction_preparation'],
            'quality_inspection' => ['construction'],'internal_handover' => ['quality_inspection'],
            'customer_handover' => ['internal_handover'],'move_in' => ['customer_handover'],'warranty' => ['move_in'],'completed' => ['warranty'],
            'document_validation' => $method === 'kpr_developer' ? ['affordability_analysis'] : [],
            'slik' => ['document_collection'],'appraisal' => ['slik'],'bank_decision' => ['appraisal'],'sp3k' => ['bank_decision'],'contract_preparation' => ['sp3k'],
            'internal_approval' => ['document_validation'],default => [],
        };
    }

    private static function f(string $name, string $label, string $type = 'text', bool $required = true, array $options = []): array
    {
        return compact('name', 'label', 'type', 'required', 'options');
    }

    private static function c(string $key, string $label, bool $required = true): array
    {
        return compact('key', 'label', 'required');
    }

    private static function d(string $type, string $label, bool $required = true): array
    {
        return compact('type', 'label', 'required');
    }

    public static function get(string $code): array
    {
        $f = fn (...$a) => self::f(...$a);
        $c = fn (...$a) => self::c(...$a);
        $d = fn (...$a) => self::d(...$a);
        $definitions = [
            'contract_review' => ['fields' => [$f('contract_number', 'Nomor Kontrak'), $f('contract_version', 'Versi Kontrak'), $f('final_price', 'Harga Final', 'currency'), $f('booking_fee', 'Booking Fee', 'currency'), $f('down_payment', 'Uang Muka', 'currency'), $f('financed_amount', 'Nilai Dicicil', 'currency'), $f('installment_count', 'Jumlah Termin', 'number'), $f('first_due_date', 'Jatuh Tempo Pertama', 'date'), $f('grace_days', 'Masa Tenggang', 'number'), $f('penalty_terms', 'Ketentuan Denda', 'textarea'), $f('early_settlement_terms', 'Pelunasan Dipercepat', 'textarea'), $f('cancellation_terms', 'Ketentuan Pembatalan', 'textarea')], 'checklist' => [$c('price_match', 'Harga sesuai SPR approved'), $c('scheme_match', 'Skema dan tenor sesuai master'), $c('customer_identity', 'Identitas para pihak benar'), $c('unit_identity', 'Data unit dan spesifikasi benar'), $c('handover_clause', 'Syarat serah terima tercantum')], 'documents' => [$d('contract_draft', 'Draf Kontrak')]],
            'affordability_analysis' => ['fields' => [$f('customer_income', 'Penghasilan Customer', 'currency'), $f('spouse_income', 'Penghasilan Pasangan', 'currency', false), $f('other_income', 'Penghasilan Tambahan', 'currency', false), $f('monthly_expense', 'Pengeluaran Bulanan', 'currency'), $f('existing_installment', 'Cicilan Berjalan', 'currency'), $f('net_disposable_income', 'Sisa Penghasilan', 'currency'), $f('dsr_percent', 'Debt Service Ratio', 'number'), $f('requested_financing', 'Nilai Pembiayaan', 'currency'), $f('recommended_tenor', 'Tenor Rekomendasi', 'number'), $f('recommended_installment', 'Angsuran Rekomendasi', 'currency'), $f('risk_grade', 'Grade Risiko', 'select', true, ['low' => 'Rendah', 'medium' => 'Sedang', 'high' => 'Tinggi'])], 'checklist' => [$c('income_verified', 'Penghasilan telah diverifikasi'), $c('expense_verified', 'Pengeluaran dan cicilan diperiksa'), $c('age_eligible', 'Usia memenuhi ketentuan produk'), $c('dsr_eligible', 'DSR memenuhi kebijakan')], 'documents' => [$d('income_evidence', 'Bukti Penghasilan'), $d('bank_statement', 'Rekening Koran')]],
            'document_validation' => self::documentValidation($f, $c, $d),
            'document_collection' => self::documentValidation($f, $c, $d),
            'internal_approval' => ['fields' => [$f('decision', 'Keputusan', 'select', true, ['approved' => 'Disetujui', 'conditional' => 'Disetujui Bersyarat', 'revision' => 'Revisi', 'rejected' => 'Ditolak']), $f('approved_limit', 'Limit Disetujui', 'currency'), $f('approved_tenor', 'Tenor Disetujui', 'number'), $f('required_dp', 'DP Wajib', 'currency'), $f('conditions', 'Syarat Keputusan', 'textarea', false), $f('decision_reason', 'Dasar Keputusan', 'textarea')], 'checklist' => [$c('analysis_complete', 'Analisis kemampuan bayar lengkap'), $c('documents_valid', 'Dokumen wajib valid'), $c('risk_reviewed', 'Risiko telah ditinjau')], 'documents' => [$d('approval_memo', 'Memo Persetujuan Internal')]],
            'slik' => ['fields' => [$f('request_date', 'Tanggal Permintaan', 'date'), $f('result_date', 'Tanggal Hasil', 'date'), $f('reference_number', 'Nomor Referensi'), $f('collectibility', 'Kolektibilitas', 'select', true, ['1' => 'Lancar/1', '2' => 'DPK/2', '3' => 'Kurang Lancar/3', '4' => 'Diragukan/4', '5' => 'Macet/5']), $f('total_obligation', 'Total Kewajiban', 'currency'), $f('arrears_amount', 'Total Tunggakan', 'currency'), $f('result', 'Hasil SLIK', 'select', true, ['passed' => 'Lolos', 'conditional' => 'Bersyarat', 'failed' => 'Tidak Lolos']), $f('analyst_notes', 'Catatan Analis', 'textarea')], 'checklist' => [$c('identity_match', 'Identitas cocok dengan hasil SLIK'), $c('facilities_reviewed', 'Seluruh fasilitas kredit diperiksa'), $c('arrears_reviewed', 'Tunggakan dan kolektibilitas diperiksa')], 'documents' => [$d('slik_result', 'Dokumen Hasil SLIK')]],
            'appraisal' => ['fields' => [$f('vendor', 'Vendor/Appraiser'), $f('officer', 'Petugas Survei'), $f('schedule_date', 'Jadwal Survei', 'datetime'), $f('survey_date', 'Realisasi Survei', 'datetime'), $f('market_value', 'Nilai Pasar', 'currency'), $f('liquidation_value', 'Nilai Likuidasi', 'currency'), $f('land_value', 'Nilai Tanah', 'currency'), $f('building_value', 'Nilai Bangunan', 'currency'), $f('residence_result', 'Hasil Survei Tempat Tinggal', 'textarea'), $f('employment_result', 'Hasil Survei Pekerjaan/Usaha', 'textarea'), $f('result', 'Kesimpulan', 'select', true, ['eligible' => 'Layak', 'conditional' => 'Layak Bersyarat', 'not_eligible' => 'Tidak Layak'])], 'checklist' => [$c('unit_visited', 'Unit telah disurvei'), $c('residence_verified', 'Tempat tinggal diverifikasi'), $c('employment_verified', 'Pekerjaan/usaha diverifikasi'), $c('value_sufficient', 'Nilai agunan mencukupi')], 'documents' => [$d('appraisal_report', 'Laporan Appraisal'), $d('survey_photos', 'Foto Survei')]],
            'bank_decision' => ['fields' => [...[$f('decision_date', 'Tanggal Keputusan', 'date'), $f('decision', 'Keputusan Bank', 'select', true, ['approved' => 'Disetujui', 'conditional' => 'Disetujui Bersyarat', 'revision' => 'Revisi', 'rejected' => 'Ditolak']), $f('approved_limit', 'Plafon Disetujui', 'currency'), $f('approved_tenor', 'Tenor Disetujui', 'number'), $f('interest_rate', 'Bunga/Margin', 'number'), $f('installment', 'Angsuran', 'currency'), $f('required_dp', 'DP', 'currency'), $f('shortfall', 'Kekurangan Plafon', 'currency'), $f('conditions', 'Syarat Tambahan', 'textarea', false), $f('rejection_reason', 'Alasan Penolakan', 'textarea', false)], ...self::feeFields($f)], 'checklist' => [$c('slik_passed', 'SLIK memenuhi syarat'), $c('appraisal_passed', 'Appraisal memenuhi syarat'), $c('credit_committee', 'Keputusan komite kredit tersedia')], 'documents' => [$d('bank_decision_letter', 'Surat Keputusan Bank')]],
            'sp3k' => ['fields' => [$f('sp3k_number', 'Nomor SP3K'), $f('issue_date', 'Tanggal Terbit', 'date'), $f('expires_at', 'Berlaku Sampai', 'date'), $f('approved_limit', 'Plafon', 'currency'), $f('tenor_months', 'Tenor', 'number'), $f('interest_rate', 'Bunga/Margin', 'number'), $f('installment', 'Angsuran', 'currency'), $f('pre_contract_conditions', 'Syarat Sebelum Akad', 'textarea'), $f('customer_response', 'Respons Customer', 'select', true, ['accepted' => 'Diterima', 'revision' => 'Minta Revisi', 'rejected' => 'Ditolak'])], 'checklist' => [$c('decision_consistent', 'Nilai sesuai keputusan bank'), $c('validity_checked', 'Masa berlaku diperiksa'), $c('customer_received', 'SP3K telah diterima customer')], 'documents' => [$d('sp3k', 'Dokumen SP3K')]],
            'contract_preparation' => ['fields' => [$f('notary_name', 'Nama Notaris'), $f('bank_pic', 'PIC Bank'), $f('contract_date', 'Rencana Tanggal Akad', 'datetime'), $f('contract_location', 'Lokasi Akad'), $f('dp_paid', 'DP Dibayar', 'currency'), $f('shortfall_paid', 'Kekurangan Plafon Dibayar', 'currency'), $f('contract_fees_paid', 'Biaya Akad Dibayar', 'currency')], 'checklist' => [$c('sp3k_valid', 'SP3K masih berlaku'), $c('customer_documents', 'Dokumen customer lengkap'), $c('unit_legal_documents', 'Dokumen legal unit lengkap'), $c('dp_settled', 'DP dan kekurangan plafon terpenuhi'), $c('fees_settled', 'Biaya akad terpenuhi'), $c('notary_ready', 'Notaris dan bank siap'), $c('unit_bank_eligible', 'Unit memenuhi syarat bank')], 'documents' => [$d('contract_invitation', 'Undangan/Jadwal Akad'), $d('legal_document_pack', 'Paket Dokumen Legal Unit')]],
            'contract_signing' => ['fields' => [$f('contract_number', 'Nomor Akad/Kontrak'), $f('contract_datetime', 'Tanggal dan Jam', 'datetime'), $f('location', 'Lokasi'), $f('developer_representative', 'Pihak Developer'), $f('customer_name', 'Customer'), $f('spouse_name', 'Pasangan', 'text', false), $f('witnesses', 'Saksi', 'textarea', false), $f('notary_name', 'Notaris', 'text', false), $f('bank_representative', 'Pihak Bank', 'text', false), $f('final_contract_value', 'Nilai Akad/Kontrak', 'currency')], 'checklist' => [$c('customer_signed', 'Customer menandatangani'), $c('spouse_signed', 'Pasangan/penjamin menandatangani', false), $c('developer_signed', 'Developer menandatangani'), $c('bank_signed', 'Bank menandatangani', false), $c('notary_signed', 'Notaris mengesahkan', false), $c('copies_distributed', 'Salinan dokumen diserahkan')], 'documents' => [$d('signed_contract', 'Kontrak/Akad Bertanda Tangan'), $d('signing_minutes', 'Berita Acara Penandatanganan'), $d('signing_photos', 'Foto Penandatanganan')]],
            'installment_monitoring' => ['fields' => [$f('total_bill', 'Total Tagihan', 'currency'), $f('total_paid', 'Total Dibayar', 'currency'), $f('outstanding', 'Sisa Piutang', 'currency'), $f('overdue_amount', 'Tunggakan', 'currency'), $f('penalty_amount', 'Denda', 'currency'), $f('payment_condition', 'Kondisi Pembayaran', 'select', true, ['current' => 'Lancar', 'partial' => 'Sebagian', 'overdue' => 'Menunggak', 'paid_off' => 'Lunas', 'restructured' => 'Restrukturisasi'])], 'checklist' => [$c('schedule_generated', 'Jadwal resmi sudah terbentuk'), $c('receipts_approved', 'Seluruh pembayaran sudah melalui approval'), $c('arrears_resolved', 'Tunggakan wajib telah diselesaikan')], 'documents' => [$d('settlement_statement', 'Surat/Keterangan Pelunasan', false)]],
            'bank_disbursement' => ['fields' => [$f('disbursement_stage', 'Tahap Pencairan', 'number'), $f('disbursement_date', 'Tanggal Pencairan', 'date'), $f('gross_amount', 'Nominal Bruto', 'currency'), $f('deduction_amount', 'Potongan Bank', 'currency'), $f('net_amount', 'Nominal Netto', 'currency'), $f('recipient_account', 'Rekening Penerima'), $f('bank_reference', 'Referensi Bank'), $f('remaining_limit', 'Sisa Plafon', 'currency')], 'checklist' => [$c('contract_completed', 'Akad telah selesai'), $c('bank_conditions_completed', 'Syarat pencairan bank terpenuhi'), $c('fund_received', 'Dana masuk rekening penerima'), $c('accounting_posted', 'Pencairan sudah diposting ke akuntansi')], 'documents' => [$d('disbursement_proof', 'Bukti Pencairan'), $d('bank_transfer_advice', 'Transfer Advice Bank', false)]],
            'construction_preparation' => ['fields' => [$f('planned_start', 'Rencana Mulai', 'date'), $f('planned_finish', 'Rencana Selesai', 'date'), $f('site_manager', 'Penanggung Jawab Lapangan'), $f('work_schedule_number', 'Nomor Jadwal/Rencana Kerja')], 'checklist' => [$c('drawing_ready', 'Gambar kerja tersedia'), $c('rab_ready', 'RAB/HPP unit tersedia'), $c('work_schedule_ready', 'Jadwal pekerjaan tersedia'), $c('contractor_ready', 'SPK/tenaga kerja siap'), $c('material_plan_ready', 'Rencana material siap')], 'documents' => [$d('work_schedule', 'Jadwal Pembangunan'), $d('approved_drawing', 'Gambar Kerja')]],
            'construction' => ['fields' => [$f('start_date', 'Tanggal Mulai', 'date'), $f('finish_date', 'Tanggal Selesai', 'date'), $f('progress_percent', 'Progress Akhir', 'number'), $f('site_supervisor', 'Pengawas'), $f('delay_days', 'Keterlambatan Hari', 'number', false), $f('delay_reason', 'Alasan Keterlambatan', 'textarea', false)], 'checklist' => [$c('progress_100', 'Progress pembangunan mencapai 100%'), $c('site_reports_complete', 'Laporan dan foto progress lengkap'), $c('spk_work_complete', 'Seluruh pekerjaan SPK selesai'), $c('material_reconciled', 'Pemakaian material direkonsiliasi')], 'documents' => [$d('completion_report', 'Laporan Penyelesaian Pembangunan'), $d('completion_photos', 'Foto Unit Selesai')]],
            'quality_inspection' => ['fields' => [$f('inspection_number', 'Nomor Inspeksi'), $f('inspection_date', 'Tanggal Inspeksi', 'date'), $f('inspector', 'Inspektor'), $f('score', 'Nilai QC', 'number'), $f('critical_defects', 'Defect Kritis', 'number'), $f('major_defects', 'Defect Mayor', 'number'), $f('minor_defects', 'Defect Minor', 'number'), $f('result', 'Hasil QC', 'select', true, ['passed' => 'Lulus', 'conditional' => 'Lulus dengan Perbaikan', 'failed' => 'Tidak Lulus'])], 'checklist' => [$c('structure_checked', 'Struktur diperiksa'), $c('architecture_checked', 'Arsitektur diperiksa'), $c('mep_checked', 'MEP/utilitas diperiksa'), $c('finishing_checked', 'Finishing diperiksa'), $c('critical_defects_closed', 'Seluruh defect kritis ditutup')], 'documents' => [$d('qc_report', 'Laporan QC'), $d('defect_list', 'Daftar Defect'), $d('qc_photos', 'Foto Pemeriksaan')]],
            'internal_handover' => ['fields' => self::handoverFields($f, false), 'checklist' => self::handoverChecklist($c, false), 'documents' => [$d('internal_handover_minutes', 'Berita Acara Serah Terima Internal'), $d('unit_condition_photos', 'Foto Kondisi Unit')]],
            'customer_handover' => ['fields' => self::handoverFields($f, true), 'checklist' => self::handoverChecklist($c, true), 'documents' => [$d('bast', 'BAST Customer'), $d('key_handover', 'Berita Acara Penyerahan Kunci'), $d('handover_photos', 'Foto Serah Terima')]],
            'move_in' => ['fields' => [$f('occupancy_date', 'Tanggal Mulai Dihuni', 'date'), $f('occupant_name', 'Nama Penghuni'), $f('occupant_phone', 'Kontak Penghuni'), $f('occupant_relation', 'Hubungan dengan Pemilik'), $f('electricity_active', 'Listrik Aktif', 'boolean'), $f('water_active', 'Air Aktif', 'boolean'), $f('warranty_start', 'Mulai Garansi', 'date'), $f('warranty_end', 'Akhir Garansi', 'date')], 'checklist' => [$c('bast_completed', 'BAST telah selesai'), $c('keys_received', 'Kunci telah diterima'), $c('utilities_active', 'Utilitas utama aktif'), $c('occupant_confirmed', 'Penghuni terkonfirmasi')], 'documents' => [$d('occupancy_confirmation', 'Konfirmasi Mulai Huni')]],
            'warranty' => ['fields' => [$f('warranty_start', 'Mulai Masa Pemeliharaan', 'date'), $f('warranty_end', 'Akhir Masa Pemeliharaan', 'date'), $f('complaint_count', 'Jumlah Keluhan', 'number'), $f('resolved_count', 'Keluhan Selesai', 'number'), $f('open_count', 'Keluhan Terbuka', 'number'), $f('customer_rating', 'Nilai Kepuasan', 'number'), $f('closure_notes', 'Catatan Penutupan', 'textarea')], 'checklist' => [$c('all_complaints_resolved', 'Semua keluhan wajib selesai'), $c('final_visit', 'Kunjungan akhir dilakukan'), $c('customer_confirmation', 'Customer mengonfirmasi penyelesaian')], 'documents' => [$d('warranty_closure', 'Berita Acara Penutupan Garansi')]],
            'completed' => ['fields' => [$f('completion_date', 'Tanggal Penutupan', 'date'), $f('financial_status', 'Status Keuangan', 'select', true, ['paid_off' => 'Lunas', 'bank_receivable' => 'Piutang Bank Selesai', 'approved_exception' => 'Pengecualian Disetujui']), $f('document_status', 'Status Dokumen', 'select', true, ['complete' => 'Lengkap', 'approved_exception' => 'Pengecualian Disetujui']), $f('closing_summary', 'Ringkasan Penutupan', 'textarea')], 'checklist' => [$c('finance_closed', 'Kewajiban keuangan selesai'), $c('documents_archived', 'Dokumen final diarsipkan'), $c('ownership_active', 'Kepemilikan unit aktif'), $c('warranty_closed', 'Masa pemeliharaan selesai')], 'documents' => [$d('transaction_closure', 'Berita Acara Penutupan Transaksi')]],
        ];

        return $definitions[$code] ?? ['fields' => [$f('result', 'Hasil Proses', 'textarea')], 'checklist' => [$c('data_verified', 'Data proses telah diverifikasi')], 'documents' => [$d('supporting_document', 'Dokumen Pendukung', false)]];
    }

    private static function documentValidation($f, $c, $d): array
    {
        return ['fields' => [$f('received_date', 'Tanggal Dokumen Diterima', 'date'), $f('validator', 'Nama Verifikator'), $f('validation_result', 'Hasil Validasi', 'select', true, ['valid' => 'Valid', 'revision' => 'Perlu Revisi', 'expired' => 'Kedaluwarsa', 'invalid' => 'Tidak Valid']), $f('revision_deadline', 'Batas Revisi', 'date', false), $f('validation_notes', 'Catatan Verifikasi', 'textarea')], 'checklist' => [$c('identity', 'KTP/identitas tersedia dan valid'), $c('family_card', 'Kartu Keluarga tersedia dan valid'), $c('marriage_document', 'Dokumen perkawinan tersedia', false), $c('tax_number', 'NPWP tersedia', false), $c('income_document', 'Dokumen penghasilan tersedia'), $c('bank_statement', 'Rekening koran tersedia'), $c('spouse_document', 'Dokumen pasangan tersedia', false), $c('product_requirements', 'Syarat khusus produk terpenuhi')], 'documents' => [$d('verification_sheet', 'Lembar Hasil Verifikasi', false), $d('verification_support', 'Bukti Pendukung Verifikasi', false)]];
    }

    private static function feeFields($f): array
    {
        return [$f('provision_fee', 'Biaya Provisi', 'currency', false), $f('administration_fee', 'Biaya Administrasi', 'currency', false), $f('appraisal_fee', 'Biaya Appraisal', 'currency', false), $f('insurance_fee', 'Biaya Asuransi', 'currency', false), $f('notary_fee', 'Biaya Notaris', 'currency', false)];
    }

    private static function handoverFields($f, bool $customer): array
    {
        return [$f('handover_number', $customer ? 'Nomor BAST' : 'Nomor Serah Terima Internal'), $f('handover_datetime', 'Tanggal dan Jam', 'datetime'), $f('developer_officer', 'Petugas Developer'), $f('recipient_name', $customer ? 'Customer/Penerima' : 'Penerima Internal'), $f('representative_document', 'Dokumen Kuasa', 'text', false), $f('electricity_meter', 'Meter Listrik'), $f('water_meter', 'Meter Air'), $f('key_numbers', 'Nomor Kunci'), $f('key_count', 'Jumlah Kunci', 'number'), $f('facility_list', 'Fasilitas/Inventaris Diserahkan', 'textarea'), $f('customer_objection', 'Keberatan/Catatan Penerima', 'textarea', false)];
    }

    private static function handoverChecklist($c, bool $customer): array
    {
        return [$c('construction_complete', 'Pembangunan selesai 100%'), $c('qc_passed', 'QC lulus'), $c('critical_defects_closed', 'Defect kritis selesai'), $c('unit_clean', 'Unit bersih dan siap'), $c('utilities_checked', 'Listrik dan air diperiksa'), $c('keys_complete','Kunci lengkap'), ...($customer ? [$c('payment_requirement','Syarat pembayaran serah terima terpenuhi'), $c('legal_documents_ready','Dokumen legal yang disyaratkan siap'), $c('customer_inspected','Customer telah memeriksa unit'), $c('bast_signed','BAST ditandatangani')] : [])];
    }
}
