import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, Save } from 'lucide-react';
import { Button, Dropdown, Input, Textarea } from '../../../../Components/UI';
import AdminLayout from '../../../../Layouts/AdminLayout';

const FieldTitle=({children,required=false})=><span className="text-sm font-extrabold">{children}{required&&<span className="ml-1 text-red-600">*</span>}</span>;

export default function Form({title,indexUrl,actionUrl,method,bank}) {
    const form=useForm({kode_bank:bank?.kode_bank??'',nama_bank:bank?.nama_bank??'',jenis_bank:bank?.jenis_bank??'konvensional',alamat_pusat:bank?.alamat_pusat??'',website:bank?.website??'',logo:null,nomor_telepon:bank?.nomor_telepon??'',email:bank?.email??'',catatan:bank?.catatan??'',status:bank?.status??'aktif'});
    const submit=(event)=>{event.preventDefault();form.transform(data=>method==='put'?{...data,_method:'put'}:data);form.post(actionUrl,{forceFormData:true,onFinish:()=>form.transform(data=>data)});};
    return <><Head title={title}/><div className="mx-auto grid max-w-5xl gap-6"><section className="flex items-center justify-between rounded-xl border bg-white/80 p-6 dark:border-white/10 dark:bg-white/8"><div><p className="text-xs font-black uppercase tracking-wider text-ink-soft">Master Kredit Bank</p><h1 className="mt-1 text-2xl font-black">{title}</h1><p className="mt-1 text-sm text-ink-soft"><span className="text-red-600">*</span> wajib diisi.</p></div><Button as={Link} href={indexUrl} variant="outline"><ArrowLeft size={16}/>Kembali</Button></section><form className="grid gap-6" onSubmit={submit}><section className="grid gap-5 rounded-xl border bg-white/80 p-6 dark:border-white/10 dark:bg-white/8 md:grid-cols-2">
        <Input label="Kode Bank" value={form.data.kode_bank} error={form.errors.kode_bank} placeholder="Dibuat otomatis jika dikosongkan" onChange={e=>form.setData('kode_bank',e.target.value)}/>
        <Input label="Nama Bank *" required value={form.data.nama_bank} error={form.errors.nama_bank} onChange={e=>form.setData('nama_bank',e.target.value)}/>
        <label className="grid gap-2"><FieldTitle required>Jenis Bank</FieldTitle><Dropdown searchable={false} value={form.data.jenis_bank} options={[{value:'konvensional',label:'Konvensional'},{value:'syariah',label:'Syariah'}]} onChange={value=>form.setData('jenis_bank',value)}/>{form.errors.jenis_bank&&<span className="text-xs font-bold text-red-600">{form.errors.jenis_bank}</span>}</label>
        <label className="grid gap-2"><FieldTitle required>Status</FieldTitle><Dropdown searchable={false} value={form.data.status} options={[{value:'aktif',label:'Aktif'},{value:'nonaktif',label:'Nonaktif'}]} onChange={value=>form.setData('status',value)}/>{form.errors.status&&<span className="text-xs font-bold text-red-600">{form.errors.status}</span>}</label>
        <Input label="Website" value={form.data.website} error={form.errors.website} onChange={e=>form.setData('website',e.target.value)}/><Input label="Nomor Telepon" value={form.data.nomor_telepon} error={form.errors.nomor_telepon} onChange={e=>form.setData('nomor_telepon',e.target.value)}/><Input label="Email" type="email" value={form.data.email} error={form.errors.email} onChange={e=>form.setData('email',e.target.value)}/><Input label="Logo" type="file" accept="image/*" error={form.errors.logo} onChange={e=>form.setData('logo',e.target.files[0])}/><Textarea label="Alamat Pusat" value={form.data.alamat_pusat} error={form.errors.alamat_pusat} onChange={e=>form.setData('alamat_pusat',e.target.value)}/><Textarea label="Catatan" value={form.data.catatan} error={form.errors.catatan} onChange={e=>form.setData('catatan',e.target.value)}/>
    </section><section className="flex justify-end gap-3 rounded-xl border bg-white/80 p-4 dark:border-white/10 dark:bg-white/8"><Button as={Link} href={indexUrl} variant="outline">Batal</Button><Button type="submit" disabled={form.processing}><Save size={16}/>{form.processing?'Menyimpan...':'Simpan Data'}</Button></section></form></div></>;
}
Form.layout=page=><AdminLayout title={page?.props?.title??'Master Bank Kredit'}>{page}</AdminLayout>;
