<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Inertia\Inertia;

class HeavyEquipmentController extends Controller
{
    public function show(string $id)
    {
        $this->authorizeModule('view');
        $equipment=DB::table('heavy_equipments as e')->join('heavy_equipment_types as t','t.id','=','e.heavy_equipment_type_id')->whereNull('e.deleted_at')->where('e.id',$id)->select('e.*','t.name as type_name')->first();abort_if(!$equipment,404);
        return Inertia::render('Admin/HeavyEquipment/Show',['title'=>'Detail Alat Berat','equipment'=>(array)$equipment,'components'=>DB::table('heavy_equipment_components')->whereNull('deleted_at')->where('heavy_equipment_id',$id)->get(),'usages'=>DB::table('heavy_equipment_usages')->whereNull('deleted_at')->where('heavy_equipment_id',$id)->latest('date')->get(),'maintenances'=>DB::table('heavy_equipment_maintenances')->whereNull('deleted_at')->where('heavy_equipment_id',$id)->latest('date')->get(),'damages'=>DB::table('heavy_equipment_damages')->whereNull('deleted_at')->where('heavy_equipment_id',$id)->latest('date')->get(),'replacements'=>DB::table('heavy_component_replacements')->whereNull('deleted_at')->where('heavy_equipment_id',$id)->latest('date')->get(),'indexUrl'=>'/admin/alat-berat/equipment']);
    }
    public function index(Request $request, string $section = 'dashboard')
    {
        $this->authorizeModule('view'); $config=$this->config($section); $search=trim((string)$request->query('search')); $sortable=array_merge(['id'],array_column($config['fields'],'name'));$sort=in_array($request->query('sort'),$sortable,true)?$request->query('sort'):'id';$direction=$request->query('direction')==='asc'?'asc':'desc';$query=$config['table']?DB::table($config['table'])->whereNull('deleted_at'):null;
        if($query&&$search!=='')$query->where(fn(Builder $q)=>collect($config['search'])->each(fn($c,$i)=>$i?$q->orWhere($c,'like',"%{$search}%"):$q->where($c,'like',"%{$search}%")));
        return Inertia::render('Admin/OperationsModule/Index',['title'=>'Alat Berat','module'=>'heavy','section'=>$section,'sectionTitle'=>$config['title'],'baseUrl'=>'/admin/alat-berat','menu'=>$this->menu(),'fields'=>$config['fields'],'filters'=>['search'=>$search,'sort'=>$sort,'direction'=>$direction],'rows'=>$query?$query->orderBy($sort,$direction)->paginate(15)->withQueryString()->through(fn($r)=>(array)$r):['data'=>[],'links'=>[]],'summary'=>$this->summary(),'options'=>$this->options(),'permissions'=>['create'=>$this->can('create'),'update'=>$this->can('update'),'delete'=>$this->can('delete'),'export'=>$this->can('export')]]);
    }
    public function store(Request $r,string $section){$this->authorizeModule('create');$c=$this->config($section);$d=$r->validate($c['rules']);DB::transaction(fn()=> $this->save($section,$c['table'],[...$d,'created_by'=>auth()->id(),'updated_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]));return back()->with('success',$c['title'].' berhasil disimpan.');}
    public function update(Request $r,string $section,string $id){$this->authorizeModule('update');$c=$this->config($section);$d=$r->validate($c['rules']);DB::table($c['table'])->where('id',$id)->whereNull('deleted_at')->update([...$d,'updated_by'=>auth()->id(),'updated_at'=>now()]);return back()->with('success','Data berhasil diperbarui.');}
    public function destroy(string $section,string $id){$this->authorizeModule('delete');$c=$this->config($section);DB::table($c['table'])->where('id',$id)->update(['deleted_at'=>now(),'updated_by'=>auth()->id(),'updated_at'=>now()]);return back()->with('success','Data diarsipkan; histori tidak dihapus permanen.');}
    public function export(string $section,string $format){$this->authorizeModule('export');$c=$this->config($section);$rows=DB::table($c['table'])->whereNull('deleted_at')->get();if($format==='pdf')return Pdf::loadView('reports.module-table',['title'=>$c['title'],'rows'=>$rows,'printedAt'=>now()->format('d/m/Y H:i')])->setPaper('a4','landscape')->download('alat-berat-'.$section.'.pdf');$view=view('reports.module-table',['title'=>$c['title'],'rows'=>$rows,'printedAt'=>now()->format('d/m/Y H:i')]);return response($view)->header('Content-Type','application/vnd.ms-excel')->header('Content-Disposition','attachment; filename="alat-berat-'.$section.'.xls"');}
    private function save(string $s,string $table,array $d):void
    {
        if($s==='replacements'){$new=DB::table('heavy_equipment_components')->lockForUpdate()->find($d['new_component_id']);abort_if(!$new||in_array($new->status,['installed','damaged','service']),422,'Komponen baru tidak tersedia untuk dipasang.');if($d['old_component_id']??null)DB::table('heavy_equipment_components')->where('id',$d['old_component_id'])->update(['heavy_equipment_id'=>null,'status'=>$d['old_component_status'],'condition'=>$d['old_component_condition']??'used','updated_at'=>now()]);DB::table('heavy_equipment_components')->where('id',$d['new_component_id'])->update(['heavy_equipment_id'=>$d['heavy_equipment_id'],'status'=>'installed','updated_at'=>now()]);}
        if($s==='usage'){$equipment=DB::table('heavy_equipments')->lockForUpdate()->find($d['heavy_equipment_id']);abort_if(!$equipment||in_array($equipment->status,['service','damaged']),422,'Alat tidak dapat digunakan.');abort_if(($d['hour_meter_end']??$d['hour_meter_start'])<$d['hour_meter_start'],422,'Hour meter akhir tidak boleh lebih kecil.');$d['duration_hours']=max(0,(float)($d['hour_meter_end']??0)-(float)$d['hour_meter_start']);$d['status']=filled($d['hour_meter_end']??null)?'completed':'in_use';DB::table('heavy_equipments')->where('id',$equipment->id)->update(['current_hour_meter'=>max($equipment->current_hour_meter,$d['hour_meter_end']??$d['hour_meter_start']),'status'=>$d['status']==='completed'?'active':'in_use','updated_at'=>now()]);}
        if($s==='maintenance')DB::table('heavy_equipments')->where('id',$d['heavy_equipment_id'])->update(['status'=>$d['status']==='completed'?'active':'service','updated_at'=>now()]);
        if($s==='damages')DB::table('heavy_equipments')->where('id',$d['heavy_equipment_id'])->update(['status'=>$d['repair_status']==='completed'?'active':'damaged','updated_at'=>now()]);
        if($s==='fuel')$d['total_cost']=(float)$d['liters']*(float)$d['price_per_liter'];
        DB::table($table)->insert($d);
    }
    private function summary():array{return [['label'=>'Total Alat Berat','value'=>DB::table('heavy_equipments')->whereNull('deleted_at')->count()],['label'=>'Sedang Digunakan','value'=>DB::table('heavy_equipments')->whereNull('deleted_at')->where('status','in_use')->count()],['label'=>'Sedang Servis','value'=>DB::table('heavy_equipments')->whereNull('deleted_at')->where('status','service')->count()],['label'=>'Alat Rusak','value'=>DB::table('heavy_equipments')->whereNull('deleted_at')->where('status','damaged')->count()],['label'=>'Total Komponen','value'=>DB::table('heavy_equipment_components')->whereNull('deleted_at')->count()],['label'=>'Komponen Rusak','value'=>DB::table('heavy_equipment_components')->whereNull('deleted_at')->where('status','damaged')->count()],['label'=>'Maintenance Terdekat','value'=>DB::table('heavy_equipment_maintenances')->whereNull('deleted_at')->whereDate('next_schedule','>=',now())->min('next_schedule')??'-'],['label'=>'Penggunaan Hari Ini','value'=>DB::table('heavy_equipment_usages')->whereNull('deleted_at')->whereDate('date',today())->count()]];}
    private function menu():array{return collect([['dashboard','Dashboard'],['equipment','Data Alat Berat'],['types','Jenis Alat'],['components','Komponen Alat Berat'],['replacements','Riwayat Penggantian Komponen'],['usage','Penggunaan Alat'],['operators','Operator'],['maintenance','Maintenance'],['damages','Kerusakan'],['fuel','Pengisian BBM'],['reports','Laporan']])->map(fn($x)=>['key'=>$x[0],'label'=>$x[1]])->all();}
    private function options():array{return ['types'=>DB::table('heavy_equipment_types')->whereNull('deleted_at')->pluck('name','id'),'equipment'=>DB::table('heavy_equipments')->whereNull('deleted_at')->pluck('name','id'),'components'=>DB::table('heavy_equipment_components')->whereNull('deleted_at')->pluck('name','id'),'operators'=>DB::table('heavy_equipment_operators')->whereNull('deleted_at')->pluck('name','id')];}
    private function config(string $s):array
    {
        $t=fn($n,$l,$r=true)=>['name'=>$n,'label'=>$l,'type'=>'text','required'=>$r];$n=fn($n,$l,$r=true)=>['name'=>$n,'label'=>$l,'type'=>'number','required'=>$r];$d=fn($n,$l)=>['name'=>$n,'label'=>$l,'type'=>'date','required'=>true];$o=fn($n,$l,$k)=>['name'=>$n,'label'=>$l,'type'=>'select','optionsKey'=>$k,'required'=>true];
        return match($s){
            'dashboard','reports'=>['title'=>$s==='dashboard'?'Dashboard':'Laporan Alat Berat','table'=>null,'fields'=>[],'rules'=>[],'search'=>[]],
            'types'=>['title'=>'Jenis Alat','table'=>'heavy_equipment_types','fields'=>[$t('name','Nama Jenis'),$t('description','Keterangan',false)],'rules'=>['name'=>'required|string|max:255','description'=>'nullable|string'],'search'=>['name','description']],
            'operators'=>['title'=>'Operator','table'=>'heavy_equipment_operators','fields'=>[$t('name','Nama'),$t('phone','Nomor HP',false),$t('identity_no','Nomor Identitas',false),$t('certification','Sertifikasi',false)],'rules'=>['name'=>'required|string','phone'=>'nullable|string','identity_no'=>'nullable|string','certification'=>'nullable|string'],'search'=>['name','phone','identity_no','certification']],
            'equipment'=>['title'=>'Data Alat Berat','table'=>'heavy_equipments','fields'=>[$t('code','Kode Alat'),$t('name','Nama Alat'),$o('heavy_equipment_type_id','Jenis Alat','types'),$t('brand','Merk',false),$t('model','Model',false),$n('year','Tahun',false),$t('serial_no','Nomor Seri'),$t('license_plate','Nomor Polisi',false),$n('current_hour_meter','Hour Meter'),['name'=>'ownership','label'=>'Kepemilikan','type'=>'select','options'=>['company'=>'Milik Perusahaan','rental'=>'Sewa'],'required'=>true],['name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Aktif','in_use'=>'Digunakan','service'=>'Servis','damaged'=>'Rusak'],'required'=>true],$t('notes','Catatan',false)],'rules'=>['code'=>'required|string','name'=>'required|string','heavy_equipment_type_id'=>'required|exists:heavy_equipment_types,id','brand'=>'nullable|string','model'=>'nullable|string','year'=>'nullable|integer|min:1900','serial_no'=>'required|string','license_plate'=>'nullable|string','current_hour_meter'=>'required|numeric|min:0','ownership'=>['required',Rule::in(['company','rental'])],'status'=>['required',Rule::in(['active','in_use','service','damaged'])],'notes'=>'nullable|string'],'search'=>['code','name','brand','model','serial_no','license_plate','status']],
            'components'=>['title'=>'Komponen Alat Berat','table'=>'heavy_equipment_components','fields'=>[$t('code','Kode Komponen'),$t('name','Nama Komponen'),$o('heavy_equipment_type_id','Jenis Alat','types'),['name'=>'heavy_equipment_id','label'=>'Alat Terpasang','type'=>'select','optionsKey'=>'equipment','required'=>false],$t('component_type','Tipe Komponen'),$t('serial_no','Nomor Seri',false),$t('condition','Kondisi'),['name'=>'status','label'=>'Status','type'=>'select','options'=>['installed'=>'Terpasang','available'=>'Tersedia','service'=>'Servis','damaged'=>'Rusak'],'required'=>true],$t('storage_location','Lokasi Penyimpanan',false)],'rules'=>['code'=>'required|string','name'=>'required|string','heavy_equipment_type_id'=>'required|exists:heavy_equipment_types,id','heavy_equipment_id'=>'nullable|required_if:status,installed|exists:heavy_equipments,id','component_type'=>'required|string','serial_no'=>'nullable|string','condition'=>'required|string','status'=>['required',Rule::in(['installed','available','service','damaged'])],'storage_location'=>'nullable|string'],'search'=>['code','name','component_type','serial_no','status']],
            'replacements'=>['title'=>'Penggantian Komponen','table'=>'heavy_component_replacements','fields'=>[$t('transaction_no','Nomor Transaksi'),$d('date','Tanggal'),$o('heavy_equipment_id','Alat Berat','equipment'),$o('old_component_id','Komponen Lama','components'),$o('new_component_id','Komponen Baru','components'),$n('hour_meter','Hour Meter'),$t('reason','Alasan'),$o('operator_id','Operator','operators'),$t('technician','Teknisi',false),$t('old_component_condition','Kondisi Komponen Lama'),['name'=>'old_component_status','label'=>'Status Komponen Lama','type'=>'select','options'=>['available'=>'Tersedia','service'=>'Servis','damaged'=>'Rusak'],'required'=>true]],'rules'=>['transaction_no'=>'required|string','date'=>'required|date','heavy_equipment_id'=>'required|exists:heavy_equipments,id','old_component_id'=>'nullable|different:new_component_id|exists:heavy_equipment_components,id','new_component_id'=>'required|exists:heavy_equipment_components,id','hour_meter'=>'required|numeric|min:0','reason'=>'required|string','operator_id'=>'nullable|exists:heavy_equipment_operators,id','technician'=>'nullable|string','old_component_condition'=>'nullable|string','old_component_status'=>['required',Rule::in(['available','service','damaged'])]],'search'=>['transaction_no','reason','technician']],
            'usage'=>['title'=>'Penggunaan Alat','table'=>'heavy_equipment_usages','fields'=>[$t('transaction_no','Nomor Transaksi'),$d('date','Tanggal'),$o('heavy_equipment_id','Alat Berat','equipment'),$o('operator_id','Operator','operators'),$t('project','Proyek',false),$n('hour_meter_start','Hour Meter Awal'),$n('hour_meter_end','Hour Meter Akhir',false),$t('description','Keterangan',false)],'rules'=>['transaction_no'=>'required|string','date'=>'required|date','heavy_equipment_id'=>'required|exists:heavy_equipments,id','operator_id'=>'required|exists:heavy_equipment_operators,id','project'=>'nullable|string','hour_meter_start'=>'required|numeric|min:0','hour_meter_end'=>'nullable|numeric|min:0','description'=>'nullable|string'],'search'=>['transaction_no','project','status']],
            'maintenance'=>['title'=>'Maintenance','table'=>'heavy_equipment_maintenances','fields'=>[$t('maintenance_no','Nomor Maintenance'),$d('date','Tanggal'),$o('heavy_equipment_id','Alat Berat','equipment'),$t('maintenance_type','Jenis Maintenance'),$t('workshop','Bengkel',false),$n('cost','Biaya'),['name'=>'next_schedule','label'=>'Jadwal Berikutnya','type'=>'date','required'=>false],$t('notes','Catatan',false),['name'=>'status','label'=>'Status','type'=>'select','options'=>['scheduled'=>'Dijadwalkan','in_progress'=>'Dikerjakan','completed'=>'Selesai'],'required'=>true]],'rules'=>['maintenance_no'=>'required|string','date'=>'required|date','heavy_equipment_id'=>'required|exists:heavy_equipments,id','maintenance_type'=>'required|string','workshop'=>'nullable|string','cost'=>'required|numeric|min:0','next_schedule'=>'nullable|date','notes'=>'nullable|string','status'=>'required|string'],'search'=>['maintenance_no','maintenance_type','workshop','status']],
            'damages'=>['title'=>'Kerusakan','table'=>'heavy_equipment_damages','fields'=>[$d('date','Tanggal'),$o('heavy_equipment_id','Alat Berat','equipment'),$t('description','Deskripsi Kerusakan'),$t('severity','Tingkat Kerusakan'),$t('repair_status','Status Perbaikan'),['name'=>'completed_date','label'=>'Tanggal Selesai','type'=>'date','required'=>false],$t('notes','Catatan',false)],'rules'=>['date'=>'required|date','heavy_equipment_id'=>'required|exists:heavy_equipments,id','description'=>'required|string','severity'=>'required|string','repair_status'=>'required|string','completed_date'=>'nullable|date','notes'=>'nullable|string'],'search'=>['description','severity','repair_status']],
            'fuel'=>['title'=>'Pengisian BBM','table'=>'heavy_equipment_fuelings','fields'=>[$d('date','Tanggal'),$o('heavy_equipment_id','Alat Berat','equipment'),$t('fuel_type','Jenis BBM'),$n('liters','Liter'),$n('price_per_liter','Harga per Liter'),$n('hour_meter','Hour Meter'),$t('notes','Catatan',false)],'rules'=>['date'=>'required|date','heavy_equipment_id'=>'required|exists:heavy_equipments,id','fuel_type'=>'required|string','liters'=>'required|numeric|min:0.01','price_per_liter'=>'required|numeric|min:0','hour_meter'=>'required|numeric|min:0','notes'=>'nullable|string'],'search'=>['fuel_type','notes']],default=>abort(404)};
    }
    private function can(string $a):bool{return auth()->user()?->can("heavy-equipment.{$a}")||auth()->user()?->hasAnyRole(['super_admin','manajer_pimpro','user_area_gudang']);}private function authorizeModule(string $a):void{abort_unless($this->can($a),403);}
}
