import { Head, router, useForm } from '@inertiajs/react';
import { ArrowLeft, Save } from 'lucide-react';
import { Button, Dropdown, Form, Input, Textarea } from '../../../../Components/UI';
import AdminLayout from '../../../../Layouts/AdminLayout';

export default function FormPage({ title, baseUrl, actionUrl, method = 'post', customers = [], options = {}, row = {} }) {
    const form = useForm({
        marketing_lead_id: row?.marketing_lead_id ?? '',
        tanggal_follow_up: row?.tanggal_follow_up ?? new Date().toISOString().slice(0, 10),
        metode_follow_up: row?.metode_follow_up ?? 'whatsapp', status_serius: row?.status_serius ?? '0',
        progress_kemampuan: row?.progress_kemampuan ?? 'low', result_code: row?.result_code ?? '',
        interest_level: row?.interest_level ?? 'cold', status: row?.status ?? 'selesai', catatan: row?.catatan ?? '',
        obstacle: row?.obstacle ?? '', next_action: row?.next_action ?? '', rencana_follow_up_at: row?.rencana_follow_up_at ?? '', attachment: null,
    });
    const leadOptions = customers.map((item) => ({ value: String(item.id), label: `${item.kode_costumer} — ${item.nama} — ${item.telepon || '-'}` }));
    const select = (name, label, items) => <div className="grid gap-2"><span className="text-sm font-extrabold">{label}</span><Dropdown value={form.data[name]} options={items ?? []} onChange={(value) => form.setData(name, value)} />{form.errors[name] && <span className="text-xs font-bold text-red-600">{form.errors[name]}</span>}</div>;
    const submit = (event) => { event.preventDefault(); form[method](actionUrl, { forceFormData: true, onSuccess: () => router.visit(baseUrl) }); };

    return <><Head title={title} /><div className="grid gap-6"><section className="rounded-lg border bg-white/80 p-6 shadow-soft dark:border-white/10 dark:bg-white/8"><p className="text-xs font-extrabold uppercase tracking-widest text-ink-soft">Marketing / Tindak Lanjut</p><h1 className="mt-2 text-3xl font-extrabold">{title}</h1><p className="mt-2 text-sm text-ink-soft">Follow-up dicatat pada Lead dan tetap menjadi riwayat ketika Lead dikonversi menjadi Customer.</p></section><Form title="Data Tindak Lanjut" description="Hasil follow-up memperbarui tahap dan jadwal tindakan Lead secara otomatis." onSubmit={submit} actions={<><Button type="button" variant="outline" onClick={() => router.visit(baseUrl)}><ArrowLeft size={17} /> Kembali</Button><Button type="submit" disabled={form.processing}><Save size={17} /> Simpan</Button></>}><div className="grid gap-4 md:grid-cols-2">{select('marketing_lead_id', 'Lead / Prospek *', leadOptions)}<Input type="date" label="Tanggal Tindak Lanjut *" value={form.data.tanggal_follow_up} error={form.errors.tanggal_follow_up} onChange={(e) => form.setData('tanggal_follow_up', e.target.value)} />{select('metode_follow_up', 'Metode *', options.methodOptions)}{select('result_code', 'Hasil Follow-up *', options.resultOptions)}{select('interest_level', 'Tingkat Minat *', options.interestOptions)}{select('status_serius', 'Keseriusan', options.seriousOptions)}{select('progress_kemampuan', 'Kemajuan Kemampuan', options.progressOptions)}{select('status', 'Status Tindak Lanjut', options.statusOptions)}<div className="md:col-span-2"><Textarea label="Catatan hasil *" value={form.data.catatan} error={form.errors.catatan} onChange={(e) => form.setData('catatan', e.target.value)} /></div><div className="md:col-span-2"><Textarea label="Kendala / keberatan Lead" value={form.data.obstacle} error={form.errors.obstacle} onChange={(e) => form.setData('obstacle', e.target.value)} /></div><div className="md:col-span-2"><Textarea label="Tindakan berikutnya" value={form.data.next_action} error={form.errors.next_action} onChange={(e) => form.setData('next_action', e.target.value)} /></div><Input type="date" label="Jadwal tindak lanjut berikutnya" value={form.data.rencana_follow_up_at} error={form.errors.rencana_follow_up_at} onChange={(e) => form.setData('rencana_follow_up_at', e.target.value)} /><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" label="Bukti komunikasi (opsional)" error={form.errors.attachment} onChange={(e) => form.setData('attachment', e.target.files?.[0] || null)} /></div></Form></div></>;
}
FormPage.layout = (page) => <AdminLayout title={page?.props?.title ?? 'Tindak Lanjut'}>{page}</AdminLayout>;
