import { Head, router, useForm } from '@inertiajs/react';
import { ArrowLeft, Save } from 'lucide-react';
import { Button, Dropdown, Form, Input, Textarea } from '../../../../Components/UI';
import AdminLayout from '../../../../Layouts/AdminLayout';

export default function FormPage({ title, baseUrl, actionUrl, method='post', customers=[], options={}, row={} }) {
    const form=useForm({costumer_id:row?.costumer_id??'',tanggal_follow_up:row?.tanggal_follow_up??new Date().toISOString().slice(0,10),metode_follow_up:row?.metode_follow_up??'chat',status_serius:row?.status_serius??'0',progress_kemampuan:row?.progress_kemampuan??'low',status:row?.status??'selesai',catatan:row?.catatan??'',rencana_follow_up_at:row?.rencana_follow_up_at??''});
    const customerOptions=customers.map((item)=>({value:String(item.id),label:`${item.kode_costumer} — ${item.nama} — ${item.telepon||'-'}`}));
    const submit=(event)=>{event.preventDefault();form[method](actionUrl,{onSuccess:()=>router.visit(baseUrl)});};
    const select=(name,label,items)=><div className="grid gap-2"><span className="text-sm font-extrabold">{label}</span><Dropdown value={form.data[name]} options={items??[]} onChange={(value)=>form.setData(name,value)} />{form.errors[name]&&<span className="text-xs font-bold text-red-600">{form.errors[name]}</span>}</div>;
    return <><Head title={title}/><div className="grid gap-6"><section className="rounded-lg border border-white/80 bg-white/78 p-6 shadow-soft dark:border-white/10 dark:bg-white/8"><p className="text-xs font-extrabold uppercase tracking-widest text-ink-soft">Marketing / Tindak Lanjut</p><h1 className="mt-2 text-3xl font-extrabold">{title}</h1></section><Form title="Data Tindak Lanjut" description="Catat tindak lanjut pelanggan pada halaman khusus." onSubmit={submit} actions={<><Button type="button" variant="outline" onClick={()=>router.visit(baseUrl)}><ArrowLeft size={17}/> Kembali</Button><Button type="submit" disabled={form.processing}><Save size={17}/> Simpan</Button></>}><div className="grid gap-4 md:grid-cols-2">{select('costumer_id','Pelanggan',customerOptions)}<Input type="date" label="Tanggal Tindak Lanjut" value={form.data.tanggal_follow_up} error={form.errors.tanggal_follow_up} onChange={(e)=>form.setData('tanggal_follow_up',e.target.value)}/>{select('metode_follow_up','Metode',options.methodOptions)}{select('status_serius','Keseriusan',options.seriousOptions)}{select('progress_kemampuan','Kemajuan Kemampuan',options.progressOptions)}{select('status','Status Tindak Lanjut',options.statusOptions)}<div className="md:col-span-2"><Textarea label="Catatan" value={form.data.catatan} error={form.errors.catatan} onChange={(e)=>form.setData('catatan',e.target.value)}/></div><Input type="date" label="Rencana Tindak Lanjut Berikutnya" value={form.data.rencana_follow_up_at} error={form.errors.rencana_follow_up_at} onChange={(e)=>form.setData('rencana_follow_up_at',e.target.value)}/></div></Form></div></>;
}
FormPage.layout=(page)=><AdminLayout title={page?.props?.title??'Tindak Lanjut'}>{page}</AdminLayout>;
